@startuml

title __PERMISSIONMANAGEMENT's Class Diagram__\n

  namespace io.radien.ms.permissionmanagement {
    class io.radien.ms.permissionmanagement.RadienApplication {
    }
  }
  

  io.radien.ms.permissionmanagement.RadienApplication -up-|> javax.ws.rs.core.Application







@enduml
