@startuml

title __ACTIVETENANT's Class Diagram__\n

  namespace io.radien.webapp {
    namespace activeTenant {
      class io.radien.webapp.activeTenant.ActiveTenantDataModelManager {
          - activeTenantValue : String
          - userActiveTenants : List<? extends SystemActiveTenant>
          + getActiveTenant()
          + getActiveTenantRESTServiceAccess()
          + getActiveTenantValue()
          + getUserActiveTenants()
          + getUserSession()
          + getUserTenants()
          + init()
          + isTenantActive()
          + setActiveTenant()
          + setActiveTenantRESTServiceAccess()
          + setActiveTenantValue()
          + setUserActiveTenants()
          + setUserSession()
          + tenantChanged()
          + tenantChangedValidationMethod()
          # isOnUsersListingScreen()
          - activateTenant()
          - deactivateTenant()
          - validateCorrectTenantAndActivateItToUser()
      }
    }
  }
  

  namespace io.radien.webapp {
    namespace activeTenant {
      class io.radien.webapp.activeTenant.ActiveTenantInterceptor {
          + manage()
      }
    }
  }
  

  namespace io.radien.webapp {
    namespace activeTenant {
      interface io.radien.webapp.activeTenant.ActiveTenantMandatory {
      }
    }
  }
  

  io.radien.webapp.activeTenant.ActiveTenantDataModelManager .up.|> java.io.Serializable
  io.radien.webapp.activeTenant.ActiveTenantDataModelManager -up-|> io.radien.webapp.AbstractManager
  io.radien.webapp.activeTenant.ActiveTenantDataModelManager o-- io.radien.api.model.tenant.SystemActiveTenant : activeTenant
  io.radien.webapp.activeTenant.ActiveTenantDataModelManager o-- io.radien.api.service.tenant.ActiveTenantRESTServiceAccess : activeTenantRESTServiceAccess
  io.radien.webapp.activeTenant.ActiveTenantDataModelManager o-- io.radien.webapp.security.UserSession : userSession
  io.radien.webapp.activeTenant.ActiveTenantInterceptor .up.|> java.io.Serializable
  io.radien.webapp.activeTenant.ActiveTenantInterceptor -up-|> io.radien.webapp.AbstractManager
  io.radien.webapp.activeTenant.ActiveTenantInterceptor o-- io.radien.webapp.activeTenant.ActiveTenantDataModelManager : activeTenantDataModelManager


 

@enduml
