@startuml

title __ECM's Class Diagram__\n

  namespace io.radien.api {
    namespace service {
      namespace ecm {
        interface io.radien.api.service.ecm.ContentServiceAccess {
            {abstract} + countByTagName()
            {abstract} + delete()
            + exists()
            {abstract} + getAppDesc()
            {abstract} + getAppDescriptions()
            {abstract} + getAppInfoId()
            {abstract} + getByContentType()
            {abstract} + getByViewId()
            {abstract} + getByViewIdLanguage()
            {abstract} + getChildrenFiles()
            {abstract} + getContentVersions()
            {abstract} + getDocumentTreeModel()
            + getFirstByViewIdLanguage()
            {abstract} + getFolderContents()
            {abstract} + getNotificationIdByType()
            {abstract} + getNotificationIdByTypeAndLanguage()
            {abstract} + getOrCreateDocumentsPath()
            {abstract} + loadFile()
            {abstract} + save()
        }
      }
    }
  }
  



 

@enduml
