@startuml

title __AUTHZ's Class Diagram__\n

  namespace io.radien.webapp {
    namespace authz {
      class io.radien.webapp.authz.WebAuthorizationChecker {
          ~ servletRequest : HttpServletRequest
          - log : Logger
          + getCurrentUserId()
          + getServletRequest()
          + hasGrant()
          + hasPermissionAccess()
          + hasPermissionToResetPassword()
          + hasTenantAdministratorRoleAccess()
          + hasUserAdministratorRoleAccess()
          # getInvokerUser()
      }
    }
  }
  

  io.radien.webapp.authz.WebAuthorizationChecker -up-|> io.radien.ms.authz.security.AuthorizationChecker
  io.radien.webapp.authz.WebAuthorizationChecker o-- io.radien.api.service.permission.PermissionRESTServiceAccess : permissionRESTServiceAccess
  io.radien.webapp.authz.WebAuthorizationChecker o-- io.radien.api.security.UserSessionEnabled : userSession







@enduml
