@startuml

title __KERNEL's Class Diagram__\n

  namespace io.radien.kernel {
    abstract class io.radien.kernel.AbstractAppframePlugin {
        {static} - serialVersionUID : long
        {abstract} + getPluginProperties()
        - loadPlugin()
    }
  }
  

  namespace io.radien.kernel {
    abstract class io.radien.kernel.OAF {
        {static} - SYSTEM_CONFIG_FILE : String
        {static} - SYSTEM_EXT_CONFIG_FILE : String
        {static} - SYSTEM_MANIFEST_FILE : String
        {static} - SYSTEM_MARKER : Marker
        {static} - WEB_INF_CLASSES : String
        {static} - log : Logger
        {static} - serialVersionUID : long
        - supportedLocales : Map<String, Locale>
        - systemMessages : SystemMessages[]
        - systemProperties : Properties
        + findLocale()
        + fireEvent()
        + getDefaultLocale()
        + getProperty()
        + getResourceBundle()
        + getSupportedLocales()
        + getSystemAdminUserId()
        + getSystemMessages()
        + getVersion()
        # getProperty()
        # getProperty()
        ~ initApplication()
        ~ loadPlugin()
        ~ loadSystemProperties()
        - getArchivePath()
        - loadManifest()
        - loadPluginManifest()
        - loadPropertiesFromAttributesObject()
        - loadPropertiesFromCatalinaLocation()
        - loadSupportedLocales()
        - readPluginProperties()
    }
  }
  

  namespace io.radien.kernel {
    class io.radien.kernel.OpenAppframe {
        {static} + OAF_EL_RESOLVE_NAME : String
        {static} - serialVersionUID : long
        + OpenAppframe()
    }
  }
  

  namespace io.radien.kernel {
    class io.radien.kernel.UTF8Control {
        {static} - DEFAULT_BUNDLE_EXTENSION : String
        + newBundle()
    }
  }
  

  io.radien.kernel.AbstractAppframePlugin -up-|> io.radien.kernel.OAF
  io.radien.kernel.OAF .up.|> io.radien.api.OAFAccess
  io.radien.kernel.OAF o-- io.radien.kernel.eventbus.EventBus : eventBus
  io.radien.kernel.OpenAppframe -up-|> io.radien.kernel.OAF
  io.radien.kernel.UTF8Control -up-|> java.util.ResourceBundle.Control


 

@enduml
