@startuml

title __CLIENT's Class Diagram__\n

  namespace io.radien.ms.usermanagement.client {
    class io.radien.ms.usermanagement.client.UserResponseExceptionMapper {
        + userHandles()
        + userToThrowable()
    }
  }
  

  io.radien.ms.usermanagement.client.UserResponseExceptionMapper -up-|> io.radien.exception.ModelResponseExceptionMapper







@enduml
