@startuml

title __RD-PERSISTENCE's Class Diagram__\n

  namespace io.radien.persistence.entities.system {
    class io.radien.persistence.entities.system.Appframe {
    }
  }
  

  namespace io.radien.persistence.jdbc {
    abstract class io.radien.persistence.jdbc.AbstractDatasourceFacade {
    }
  }
  

  namespace io.radien.persistence.jdbc {
    class io.radien.persistence.jdbc.DatasourceFacade {
    }
  }
  

  namespace io.radien.persistence.jdbc {
    class io.radien.persistence.jdbc.ResourceUtil {
    }
  }
  

  namespace io.radien.persistence.jmx {
    class io.radien.persistence.jmx.JpaCacheHintsMXBean {
    }
  }
  

  namespace io.radien.persistence.jmx {
    interface io.radien.persistence.jmx.JpaCacheMbean {
    }
  }
  

  namespace io.radien.persistence.jpa {
    enum EntityManagerFactories {
    }
  }
  

  namespace io.radien.persistence.jpa {
    interface io.radien.persistence.jpa.EntityManagerQualifier {
    }
  }
  

  namespace io.radien.persistence.jpa {
    class io.radien.persistence.jpa.EntityManagerUtil {
    }
  }
  

  namespace io.radien.persistence.service.system {
    class io.radien.persistence.service.system.AppframeService {
    }
  }
  

  io.radien.persistence.entities.system.Appframe .up.|> io.radien.api.IAppframe
  io.radien.persistence.entities.system.Appframe -up-|> io.radien.api.model.AbstractModel
  io.radien.persistence.jdbc.AbstractDatasourceFacade .up.|> java.io.Serializable
  io.radien.persistence.jdbc.DatasourceFacade -up-|> io.radien.persistence.jdbc.AbstractDatasourceFacade
  io.radien.persistence.jmx.JpaCacheHintsMXBean .up.|> io.radien.persistence.jmx.JpaCacheMbean


 

@enduml
