@startuml

title __RD-MS-OPENID-CLIENT's Class Diagram__\n

  namespace io.radien.ms.openid.entities {
    class io.radien.ms.openid.entities.GlobalHeaders {
    }
  }
  

  namespace io.radien.ms.openid.entities {
    class io.radien.ms.openid.entities.Principal {
    }
  }
  

  namespace io.radien.ms.openid.service {
    class io.radien.ms.openid.service.PrincipalFactory {
    }
  }
  

  io.radien.ms.openid.entities.GlobalHeaders .up.|> org.eclipse.microprofile.rest.client.ext.ClientHeadersFactory
  io.radien.ms.openid.entities.GlobalHeaders o-- io.radien.api.security.TokensPlaceHolder : tokensPlaceHolder
  io.radien.ms.openid.entities.Principal .up.|> io.radien.api.model.user.SystemUser







@enduml
