@startuml

title __PROVIDERS's Class Diagram__\n

  namespace io.radien.ms.ecm.client.providers {
    class io.radien.ms.ecm.client.providers.I18NPropertyMessageBodyReader {
        + isReadable()
        + readFrom()
    }
  }
  

  namespace io.radien.ms.ecm.client.providers {
    class io.radien.ms.ecm.client.providers.I18NPropertyMessageBodyWriter {
        + getSize()
        + isWriteable()
        + writeTo()
    }
  }
  

  io.radien.ms.ecm.client.providers.I18NPropertyMessageBodyReader .up.|> javax.ws.rs.ext.MessageBodyReader
  io.radien.ms.ecm.client.providers.I18NPropertyMessageBodyWriter .up.|> javax.ws.rs.ext.MessageBodyWriter


 

@enduml
