@startuml

title __TENANT's Class Diagram__\n

  namespace io.radien.api {
    namespace model {
      namespace tenant {
        interface io.radien.api.model.tenant.SystemActiveTenant {
            {abstract} + getIsTenantActive()
            {abstract} + getTenantId()
            {abstract} + getTenantName()
            {abstract} + getUserId()
            {abstract} + setIsTenantActive()
            {abstract} + setTenantId()
            {abstract} + setTenantName()
            {abstract} + setUserId()
        }
      }
    }
  }
  

  namespace io.radien.api {
    namespace model {
      namespace tenant {
        interface io.radien.api.model.tenant.SystemActiveTenantSearchFilter {
            {abstract} + getIsTenantActive()
            {abstract} + getTenantId()
            {abstract} + getTenantName()
            {abstract} + getUserId()
            {abstract} + setIsTenantActive()
            {abstract} + setTenantId()
            {abstract} + setTenantName()
            {abstract} + setUserId()
        }
      }
    }
  }
  

  namespace io.radien.api {
    namespace model {
      namespace tenant {
        interface io.radien.api.model.tenant.SystemContract {
            {abstract} + getEnd()
            {abstract} + getName()
            {abstract} + getStart()
            {abstract} + setEnd()
            {abstract} + setName()
            {abstract} + setStart()
        }
      }
    }
  }
  

  namespace io.radien.api {
    namespace model {
      namespace tenant {
        interface io.radien.api.model.tenant.SystemTenant {
            {abstract} + getClientAddress()
            {abstract} + getClientCity()
            {abstract} + getClientCountry()
            {abstract} + getClientEmail()
            {abstract} + getClientId()
            {abstract} + getClientPhoneNumber()
            {abstract} + getClientZipCode()
            {abstract} + getName()
            {abstract} + getParentId()
            {abstract} + getTenantEnd()
            {abstract} + getTenantKey()
            {abstract} + getTenantStart()
            {abstract} + getTenantType()
            {abstract} + setClientAddress()
            {abstract} + setClientCity()
            {abstract} + setClientCountry()
            {abstract} + setClientEmail()
            {abstract} + setClientId()
            {abstract} + setClientPhoneNumber()
            {abstract} + setClientZipCode()
            {abstract} + setName()
            {abstract} + setParentId()
            {abstract} + setTenantEnd()
            {abstract} + setTenantKey()
            {abstract} + setTenantStart()
            {abstract} + setTenantType()
        }
      }
    }
  }
  

  namespace io.radien.api {
    namespace model {
      namespace tenant {
        interface io.radien.api.model.tenant.SystemTenantSearchFilter {
            {abstract} + getIds()
            {abstract} + getName()
            {abstract} + getTenantType()
            {abstract} + setIds()
            {abstract} + setName()
            {abstract} + setTenantType()
        }
      }
    }
  }
  

  namespace io.radien.api {
    namespace model {
      namespace tenant {
        interface io.radien.api.model.tenant.SystemTenantType {
            {abstract} + getDescription()
            {abstract} + getId()
            {abstract} + setDescription()
            {abstract} + setId()
        }
      }
    }
  }
  








@enduml
