@startuml

title __PERMISSION's Class Diagram__\n

  namespace io.radien.api {
    namespace model {
      namespace permission {
        abstract class io.radien.api.model.permission.AbstractActionModel {
        }
      }
    }
  }
  

  namespace io.radien.api {
    namespace model {
      namespace permission {
        abstract class io.radien.api.model.permission.AbstractPermissionModel {
        }
      }
    }
  }
  

  namespace io.radien.api {
    namespace model {
      namespace permission {
        abstract class io.radien.api.model.permission.AbstractResourceModel {
        }
      }
    }
  }
  

  namespace io.radien.api {
    namespace model {
      namespace permission {
        interface io.radien.api.model.permission.SystemAction {
            {abstract} + getId()
            {abstract} + getName()
            {abstract} + setId()
            {abstract} + setName()
        }
      }
    }
  }
  

  namespace io.radien.api {
    namespace model {
      namespace permission {
        interface io.radien.api.model.permission.SystemActionSearchFilter {
            {abstract} + getName()
            {abstract} + setName()
        }
      }
    }
  }
  

  namespace io.radien.api {
    namespace model {
      namespace permission {
        interface io.radien.api.model.permission.SystemPermission {
            {abstract} + getActionId()
            {abstract} + getName()
            {abstract} + getResourceId()
            {abstract} + setActionId()
            {abstract} + setName()
            {abstract} + setResourceId()
        }
      }
    }
  }
  

  namespace io.radien.api {
    namespace model {
      namespace permission {
        interface io.radien.api.model.permission.SystemPermissionSearchFilter {
            {abstract} + getActionId()
            {abstract} + getName()
            {abstract} + getResourceId()
            {abstract} + setActionId()
            {abstract} + setName()
            {abstract} + setResourceId()
        }
      }
    }
  }
  

  namespace io.radien.api {
    namespace model {
      namespace permission {
        interface io.radien.api.model.permission.SystemResource {
            {abstract} + getId()
            {abstract} + getName()
            {abstract} + setId()
            {abstract} + setName()
        }
      }
    }
  }
  

  namespace io.radien.api {
    namespace model {
      namespace permission {
        interface io.radien.api.model.permission.SystemResourceSearchFilter {
            {abstract} + getName()
            {abstract} + setName()
        }
      }
    }
  }
  

  io.radien.api.model.permission.AbstractActionModel .up.|> io.radien.api.model.permission.SystemAction
  io.radien.api.model.permission.AbstractActionModel -up-|> io.radien.api.model.AbstractModel
  io.radien.api.model.permission.AbstractPermissionModel .up.|> io.radien.api.model.permission.SystemPermission
  io.radien.api.model.permission.AbstractPermissionModel -up-|> io.radien.api.model.AbstractModel
  io.radien.api.model.permission.AbstractResourceModel .up.|> io.radien.api.model.permission.SystemResource
  io.radien.api.model.permission.AbstractResourceModel -up-|> io.radien.api.model.AbstractModel


 

@enduml
