@startuml

title __SERVICES's Class Diagram__\n

  namespace io.radien.ms.ecm.client.services {
    interface io.radien.ms.ecm.client.services.I18NPropertyResourceClient {
        {abstract} + add()
        {abstract} + addAll()
        {abstract} + getKeys()
        {abstract} + getMessage()
        {abstract} + getProperties()
        {abstract} + getProperty()
        {abstract} + initializeProperties()
    }
  }
  

  namespace io.radien.ms.ecm.client.services {
    interface io.radien.ms.ecm.client.services.SystemI18NPropertyService {
        {abstract} + delete()
        {abstract} + getAll()
        {abstract} + getByKey()
        {abstract} + getKeys()
        {abstract} + getLocalizedMessage()
        {abstract} + initializeProperties()
        {abstract} + save()
        {abstract} + save()
    }
  }
  








@enduml
