@startuml

title __ENTITIES's Class Diagram__\n

  namespace io.radien.ms.usermanagement.client {
    namespace entities {
      class io.radien.ms.usermanagement.client.entities.GlobalHeaders {
          + update()
      }
    }
  }
  

  namespace io.radien.ms.usermanagement.client {
    namespace entities {
      class io.radien.ms.usermanagement.client.entities.User {
          - delegatedCreation : boolean
          - enabled : boolean
          - firstname : String
          - id : Long
          - lastname : String
          - logon : String
          {static} - serialVersionUID : long
          - sub : String
          - terminationDate : Date
          - userEmail : String
          + User()
          + User()
          + getFirstname()
          + getId()
          + getLastname()
          + getLogon()
          + getSub()
          + getTerminationDate()
          + getUserEmail()
          + isDelegatedCreation()
          + isEnabled()
          + setDelegatedCreation()
          + setEnabled()
          + setFirstname()
          + setId()
          + setLastname()
          + setLogon()
          + setSub()
          + setTerminationDate()
          + setUserEmail()
      }
    }
  }
  

  namespace io.radien.ms.usermanagement.client {
    namespace entities {
      class io.radien.ms.usermanagement.client.entities.UserSearchFilter {
          - email : String
          - logon : String
          - sub : String
          + UserSearchFilter()
          + UserSearchFilter()
          + getEmail()
          + getLogon()
          + getSub()
          + setEmail()
          + setLogon()
          + setSub()
      }
    }
  }
  

  io.radien.ms.usermanagement.client.entities.GlobalHeaders .up.|> org.eclipse.microprofile.rest.client.ext.ClientHeadersFactory
  io.radien.ms.usermanagement.client.entities.GlobalHeaders o-- io.radien.api.security.TokensPlaceHolder : tokensPlaceHolder
  io.radien.ms.usermanagement.client.entities.User .up.|> io.radien.api.model.user.SystemUser
  io.radien.ms.usermanagement.client.entities.User -up-|> io.radien.api.model.user.AbstractUserModel
  io.radien.ms.usermanagement.client.entities.UserSearchFilter .up.|> io.radien.api.model.user.SystemUserSearchFilter
  io.radien.ms.usermanagement.client.entities.UserSearchFilter -up-|> io.radien.api.search.SearchableByIds


 

@enduml
