@startuml

title __IDENTITY's Class Diagram__\n

  namespace io.radien.api {
    namespace model {
      namespace identity {
        abstract class io.radien.api.model.identity.AbstractContactModel {
            - city : String
            - contactType : String
            - email : String
            - id : Long
            - phoneNumber : String
            - postalCode : String
            {static} - serialVersionUID : long
            - street : String
            + getCity()
            + getContactType()
            + getEmail()
            + getId()
            + getIdentity()
            + getPhoneNumber()
            + getPostalCode()
            + getStreet()
            + setCity()
            + setContactType()
            + setEmail()
            + setId()
            + setIdentity()
            + setPhoneNumber()
            + setPostalCode()
            + setStreet()
        }
      }
    }
  }
  

  namespace io.radien.api {
    namespace model {
      namespace identity {
        abstract class io.radien.api.model.identity.AbstractIdentityModel {
            {static} - serialVersionUID : long
            + getFullname()
            + getFullname()
        }
      }
    }
  }
  

  namespace io.radien.api {
    namespace model {
      namespace identity {
        interface io.radien.api.model.identity.SystemIdentity {
            {abstract} + getFirstname()
            {abstract} + getFullname()
            {abstract} + getFullname()
            {abstract} + getLastname()
            {abstract} + setFirstname()
            {abstract} + setLastname()
        }
      }
    }
  }
  

  namespace io.radien.api {
    namespace model {
      namespace identity {
        interface io.radien.api.model.identity.SystemIdentityContact {
            {abstract} + getCity()
            {abstract} + getEmail()
            {abstract} + getId()
            {abstract} + getIdentity()
            {abstract} + getPhoneNumber()
            {abstract} + getPostalCode()
            {abstract} + getStreet()
            {abstract} + setCity()
            {abstract} + setEmail()
            {abstract} + setId()
            {abstract} + setIdentity()
            {abstract} + setPhoneNumber()
            {abstract} + setPostalCode()
            {abstract} + setStreet()
        }
      }
    }
  }
  

  io.radien.api.model.identity.AbstractContactModel .up.|> io.radien.api.model.identity.SystemIdentityContact
  io.radien.api.model.identity.AbstractContactModel -up-|> io.radien.api.model.AbstractModel
  io.radien.api.model.identity.AbstractContactModel o-- io.radien.api.model.identity.SystemIdentity : identity
  io.radien.api.model.identity.AbstractIdentityModel .up.|> io.radien.api.model.identity.SystemIdentity
  io.radien.api.model.identity.AbstractIdentityModel -up-|> io.radien.api.model.AbstractModel


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
