@startuml

title __EXCEPTION's Class Diagram__\n

  namespace io.radien.ms.rolemanagement.client.exception {
    class io.radien.ms.rolemanagement.client.exception.BadRequestException {
        {static} - serialVersionUID : long
        + BadRequestException()
        + BadRequestException()
    }
  }
  

  namespace io.radien.ms.rolemanagement.client.exception {
    class io.radien.ms.rolemanagement.client.exception.InternalServerErrorException {
        {static} - serialVersionUID : long
        + InternalServerErrorException()
        + InternalServerErrorException()
    }
  }
  

  namespace io.radien.ms.rolemanagement.client.exception {
    class io.radien.ms.rolemanagement.client.exception.RoleResponseExceptionMapper {
        + roleHandles()
        + roleToThrowable()
    }
  }
  

  io.radien.ms.rolemanagement.client.exception.RoleResponseExceptionMapper -up-|> io.radien.exception.ModelResponseExceptionMapper


 

@enduml
