@startuml

title __ROLEMANAGEMENT's Class Diagram__\n

  namespace io.radien.ms.rolemanagement {
    class io.radien.ms.rolemanagement.RoleApplication {
    }
  }
  

  io.radien.ms.rolemanagement.RoleApplication -up-|> javax.ws.rs.core.Application







@enduml
