@startuml

title __MODEL's Class Diagram__\n

  namespace io.radien.api {
    namespace model {
      abstract class io.radien.api.model.AbstractModel {
          - createDate : Date
          - createUser : Long
          - lastUpdate : Date
          - lastUpdateUser : Long
          {static} - serialVersionUID : long
          + getCreateDate()
          + getCreateUser()
          + getLastUpdate()
          + getLastUpdateUser()
          + setCreateDate()
          + setCreateUser()
          + setLastUpdate()
          + setLastUpdateUser()
      }
    }
  }
  

  namespace io.radien.api {
    namespace model {
      interface io.radien.api.model.Model {
          {abstract} + getCreateDate()
          {abstract} + getCreateUser()
          {abstract} + getLastUpdate()
          {abstract} + getLastUpdateUser()
          {abstract} + setCreateDate()
          {abstract} + setCreateUser()
          {abstract} + setLastUpdate()
          {abstract} + setLastUpdateUser()
      }
    }
  }
  

  namespace io.radien.api {
    namespace model {
      class io.radien.api.model.ModelValueId {
          # id : Long
          + getId()
          + setId()
      }
    }
  }
  

  namespace io.radien.api {
    namespace model {
      interface io.radien.api.model.SystemId {
          {abstract} + getId()
          {abstract} + setId()
      }
    }
  }
  

  io.radien.api.model.AbstractModel .up.|> io.radien.api.model.Model
  io.radien.api.model.AbstractModel -up-|> io.radien.api.model.ModelValueId
  io.radien.api.model.ModelValueId .up.|> io.radien.api.model.SystemId







@enduml
