# Copyright (c) 2021-present radien GmbH. All rights reserved.
# <p>
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# <p>
# http://www.apache.org/licenses/LICENSE-2.0
# <p>
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.Ku

version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto8
  pre_build:
    commands:
      - |
        export CODEARTIFACT_AUTH_TOKEN=$( \
          aws codeartifact get-authorization-token \
            --domain radien \
            --domain-owner 625513329897 \
            --query authorizationToken \
            --output text)
      - export JAVA_OPTS="-Xms2G -Xmx2G"
      - export MAVEN_OPTS="-Xms2G -Xmx2G"
  build:
    commands:
      - mvn deploy -T 4C -e -P radien--radien-artifactory -B -s aws-build-settings.xml -DskipTests=true
      #- ls rd-ms-ecm/target/*exec.jar
    finally:
      - rm -r /root/.m2/repository/io/radien/

artifacts:
  files:
    - rd-ms-usermanagement/target/usermanagementservice.war
    - rd-ms-ecm/target/rd-ms-ecm.war
    - rd-web/target/web.war
    - Dockerfile

cache:
  paths:
    - '/root/.m2/**/*'
