@startuml

title __UTIL's Class Diagram__\n

  namespace io.radien.ms.rolemanagement {
    namespace util {
      class io.radien.ms.rolemanagement.util.RoleModelMapper {
          {static} + map()
          {static} + map()
          {static} + map()
          - RoleModelMapper()
      }
    }
  }
  








@enduml
