@startuml

title __SERVICE's Class Diagram__\n

  namespace io.radien.ms.openid.service {
    class io.radien.ms.openid.service.PrincipalFactory {
        {static} + convert()
        {static} + create()
        {static} - getString()
    }
  }
  








@enduml
