@startuml

title __S3's Class Diagram__\n

  namespace io.radien.aws.utils.s3 {
    class io.radien.aws.utils.s3.S3FileUtil {
        {static} - log : Logger
        {static} + deleteIfExists()
        {static} + getS3FileWithName()
        {static} + getS3FilesStartingWith()
        # S3FileUtil()
    }
  }
  



 

@enduml
