@startuml

title __LISTENER's Class Diagram__\n

  namespace io.radien.security.openid.listener {
    class io.radien.security.openid.listener.CustomRequestContextListener {
    }
  }
  

  io.radien.security.openid.listener.CustomRequestContextListener -up-|> org.springframework.web.context.request.RequestContextListener







@enduml
