@startuml

title __CLIENT's Class Diagram__\n

  namespace io.radien.ms.permissionmanagement.client {
    class io.radien.ms.permissionmanagement.client.PermissionResponseExceptionMapper {
        + permissionHandles()
        + permissionToThrowable()
    }
  }
  

  io.radien.ms.permissionmanagement.client.PermissionResponseExceptionMapper -up-|> io.radien.exception.ModelResponseExceptionMapper







@enduml
