@startuml

title __UTIL's Class Diagram__\n

  namespace io.radien.ms.ecm {
    namespace util {
      class io.radien.ms.ecm.util.EntityManagerProducer {
          {static} - DATABASE : String
          - managerFactory : DocumentCollectionManagerFactory<MongoDBDocumentCollectionManager>
          + close()
          + getEntityManager()
      }
    }
  }
  

  namespace io.radien.ms.ecm {
    namespace util {
      class io.radien.ms.ecm.util.I18NPropertyEntityMapper {
          {static} + map()
          {static} + map()
          {static} + mapToDTO()
          {static} + mapToDTO()
          {static} + mapToEntity()
          {static} + mapToEntity()
          {static} - addValue()
      }
    }
  }
  

  namespace io.radien.ms.ecm {
    namespace util {
      class io.radien.ms.ecm.util.OafConstants {
          {static} + OAF_ACTIVE : String
          {static} + OAF_CONTENT_LANG : String
          {static} + OAF_CONTENT_TYPE : String
          {static} + OAF_FILE_SIZE : String
          {static} + OAF_HTML_CONTENT : String
          {static} + OAF_IMAGE : String
          {static} + OAF_IMAGE_MIME_TYPE : String
          {static} + OAF_IMAGE_NAME : String
          {static} + OAF_MIXIN_NODE_PROPS : String
          {static} + OAF_SYSTEM : String
          {static} + OAF_VIEW_ID : String
      }
    }
  }
  

  namespace io.radien.ms.ecm {
    namespace util {
      class io.radien.ms.ecm.util.ResourceBundleLoader {
          {static} + DEFAULT_BUNDLE_NAME : String
          - allProperties : List<I18NProperty>
          - locales : List<Locale>
          {static} - log : Logger
          {static} - serialVersionUID : long
          + ResourceBundleLoader()
          + getAllProperties()
          + getLocales()
      }
    }
  }
  

  namespace io.radien.ms.ecm {
    namespace util {
      class io.radien.ms.ecm.util.TranslationEntityMapper {
          {static} + getJsonArrayFromTranslations()
          {static} + mapToDTO()
          {static} + mapToDTO()
          {static} + mapToEntity()
          {static} + mapToEntity()
          {static} - addValue()
      }
    }
  }
  

  io.radien.ms.ecm.util.ResourceBundleLoader .up.|> java.io.Serializable


 

@enduml
