@startuml

title __CONFIG's Class Diagram__\n

  namespace io.radien.ms.usermanagement {
    namespace config {
      enum KeycloakEmailActions {
        TERMS
        TOTP
        UPDATE_PASSWORD
        UPDATE_PROFILE
        VERIFY_EMAIL
        propKey
      }
    }
  }
  



 

@enduml
