@startuml

title __BATCH's Class Diagram__\n

  namespace io.radien.api {
    namespace service {
      namespace batch {
        class io.radien.api.service.batch.BatchSummary {
            - nonProcessedItems : Collection<DataIssue>
            - total : int
            + BatchSummary()
            + BatchSummary()
            + addNonProcessedItem()
            + addNonProcessedItems()
            + getInternalStatus()
            + getNonProcessedItems()
            + getTotal()
            + getTotalNonProcessed()
            + getTotalProcessed()
            - BatchSummary()
        }
      }
    }
  }
  

  namespace io.radien.api {
    namespace service {
      namespace batch {
        enum ProcessingStatus {
          FAIL
          PARTIAL_SUCCESS
          SUCCESS
        }
      }
    }
  }
  

  namespace io.radien.api {
    namespace service {
      namespace batch {
        class io.radien.api.service.batch.DataIssue {
            - reasons : List<String>
            - rowId : long
            + DataIssue()
            + DataIssue()
            + addReason()
            + getReasons()
            + getRowId()
            - DataIssue()
        }
      }
    }
  }
  

  io.radien.api.service.batch.BatchSummary +-down- io.radien.api.service.batch.BatchSummary.ProcessingStatus


 

@enduml
