@startuml

title __RD-MS-USERMANAGEMENT-CLIENT's Class Diagram__\n

  namespace io.radien.ms.usermanagement.client {
    class io.radien.ms.usermanagement.client.UserResponseExceptionMapper {
    }
  }
  

  namespace io.radien.ms.usermanagement.client {
    namespace entities {
      class io.radien.ms.usermanagement.client.entities.GlobalHeaders {
      }
    }
  }
  

  namespace io.radien.ms.usermanagement.client {
    namespace entities {
      class io.radien.ms.usermanagement.client.entities.User {
      }
    }
  }
  

  namespace io.radien.ms.usermanagement.client {
    namespace entities {
      class io.radien.ms.usermanagement.client.entities.UserSearchFilter {
      }
    }
  }
  

  namespace io.radien.ms.usermanagement.client {
    namespace exceptions {
      class io.radien.ms.usermanagement.client.exceptions.BadRequestException {
      }
    }
  }
  

  namespace io.radien.ms.usermanagement.client {
    namespace exceptions {
      class io.radien.ms.usermanagement.client.exceptions.ForbiddenException {
      }
    }
  }
  

  namespace io.radien.ms.usermanagement.client {
    namespace exceptions {
      class io.radien.ms.usermanagement.client.exceptions.InternalServerErrorException {
      }
    }
  }
  

  namespace io.radien.ms.usermanagement.client {
    namespace exceptions {
      class io.radien.ms.usermanagement.client.exceptions.RemoteResourceException {
      }
    }
  }
  

  namespace io.radien.ms.usermanagement.client {
    namespace providers {
      class io.radien.ms.usermanagement.client.providers.PageMessageBodyReader {
      }
    }
  }
  

  namespace io.radien.ms.usermanagement.client {
    namespace providers {
      class io.radien.ms.usermanagement.client.providers.UserMessageBodyReader {
      }
    }
  }
  

  namespace io.radien.ms.usermanagement.client {
    namespace providers {
      class io.radien.ms.usermanagement.client.providers.UserMessageBodyWriter {
      }
    }
  }
  

  namespace io.radien.ms.usermanagement.client {
    namespace services {
      class io.radien.ms.usermanagement.client.services.UserFactory {
      }
    }
  }
  

  namespace io.radien.ms.usermanagement.client {
    namespace services {
      class io.radien.ms.usermanagement.client.services.UserRESTServiceClient {
      }
    }
  }
  

  namespace io.radien.ms.usermanagement.client {
    namespace services {
      interface io.radien.ms.usermanagement.client.services.UserResourceClient {
      }
    }
  }
  

  namespace io.radien.ms.usermanagement.client {
    namespace util {
      class io.radien.ms.usermanagement.client.util.ClientServiceUtil {
      }
    }
  }
  

  namespace io.radien.ms.usermanagement.client {
    namespace util {
      class io.radien.ms.usermanagement.client.util.ListUserModelMapper {
      }
    }
  }
  

  namespace io.radien.ms.usermanagement.client {
    namespace util {
      class io.radien.ms.usermanagement.client.util.PageModelMapper {
      }
    }
  }
  

  namespace io.radien.ms.usermanagement.client {
    namespace util {
      class io.radien.ms.usermanagement.client.util.UserFactoryUtil {
      }
    }
  }
  

  namespace io.radien.ms.usermanagement.client {
    namespace util {
      class io.radien.ms.usermanagement.client.util.UserModelMapper {
      }
    }
  }
  

  io.radien.ms.usermanagement.client.UserResponseExceptionMapper -up-|> io.radien.exception.ModelResponseExceptionMapper
  io.radien.ms.usermanagement.client.entities.GlobalHeaders .up.|> org.eclipse.microprofile.rest.client.ext.ClientHeadersFactory
  io.radien.ms.usermanagement.client.entities.GlobalHeaders o-- io.radien.api.security.TokensPlaceHolder : tokensPlaceHolder
  io.radien.ms.usermanagement.client.entities.User .up.|> io.radien.api.model.user.SystemUser
  io.radien.ms.usermanagement.client.entities.User -up-|> io.radien.api.model.user.AbstractUserModel
  io.radien.ms.usermanagement.client.entities.UserSearchFilter .up.|> io.radien.api.model.user.SystemUserSearchFilter
  io.radien.ms.usermanagement.client.entities.UserSearchFilter -up-|> io.radien.api.search.SearchableByIds
  io.radien.ms.usermanagement.client.providers.PageMessageBodyReader .up.|> javax.ws.rs.ext.MessageBodyReader
  io.radien.ms.usermanagement.client.providers.UserMessageBodyReader .up.|> javax.ws.rs.ext.MessageBodyReader
  io.radien.ms.usermanagement.client.providers.UserMessageBodyWriter .up.|> javax.ws.rs.ext.MessageBodyWriter
  io.radien.ms.usermanagement.client.services.UserFactory -up-|> io.radien.ms.usermanagement.client.util.UserFactoryUtil
  io.radien.ms.usermanagement.client.services.UserRESTServiceClient .up.|> io.radien.api.service.user.UserRESTServiceAccess
  io.radien.ms.usermanagement.client.services.UserRESTServiceClient -up-|> io.radien.ms.authz.security.AuthorizationChecker
  io.radien.ms.usermanagement.client.services.UserRESTServiceClient o-- io.radien.ms.usermanagement.client.util.ClientServiceUtil : clientServiceUtil
  io.radien.ms.usermanagement.client.services.UserRESTServiceClient o-- io.radien.api.OAFAccess : oaf
  io.radien.ms.usermanagement.client.services.UserRESTServiceClient o-- io.radien.api.security.TokensPlaceHolder : tokensPlaceHolder
  io.radien.ms.usermanagement.client.util.UserFactoryUtil .up.|> java.io.Serializable


 

@enduml
