@startuml

title __UTIL's Class Diagram__\n

  namespace io.radien.ms.rolemanagement.client.util {
    class io.radien.ms.rolemanagement.client.util.ClientServiceUtil {
        {static} - log : Logger
        + getRoleResourceClient()
        + getTenantResourceClient()
        + getTenantRolePermissionResourceClient()
        + getTenantRoleUserResourceClient()
    }
  }
  

  namespace io.radien.ms.rolemanagement.client.util {
    class io.radien.ms.rolemanagement.client.util.ListRoleModelMapper {
        {static} + map()
        - ListRoleModelMapper()
    }
  }
  

  namespace io.radien.ms.rolemanagement.client.util {
    class io.radien.ms.rolemanagement.client.util.RoleModelMapper {
        {static} + map()
        {static} + map()
        {static} + map()
        {static} + mapList()
        {static} + mapToPage()
        - RoleModelMapper()
    }
  }
  

  namespace io.radien.ms.rolemanagement.client.util {
    class io.radien.ms.rolemanagement.client.util.TenantRoleModelMapper {
        {static} + map()
        {static} + map()
        {static} + mapList()
        {static} + mapToPage()
        - TenantRoleModelMapper()
    }
  }
  

  namespace io.radien.ms.rolemanagement.client.util {
    class io.radien.ms.rolemanagement.client.util.TenantRolePermissionModelMapper {
        {static} + map()
        {static} + map()
        {static} + mapList()
        {static} + mapToPage()
        - TenantRolePermissionModelMapper()
    }
  }
  

  namespace io.radien.ms.rolemanagement.client.util {
    class io.radien.ms.rolemanagement.client.util.TenantRoleUserModelMapper {
        {static} + map()
        {static} + map()
        {static} + mapList()
        {static} + mapToPage()
        - TenantRoleUserModelMapper()
    }
  }
  








@enduml
