@startuml

title __PROVIDERS's Class Diagram__\n

  namespace io.radien.ms.tenantmanagement {
    namespace providers {
      class io.radien.ms.tenantmanagement.providers.SystemContractMessageBodyReader {
          + isReadable()
          + readFrom()
      }
    }
  }
  

  io.radien.ms.tenantmanagement.providers.SystemContractMessageBodyReader .up.|> javax.ws.rs.ext.MessageBodyReader







@enduml
