@startuml

title __EXCEPTION's Class Diagram__\n

  namespace io.radien.api {
    namespace service {
      namespace ecm {
        namespace exception {
          class io.radien.api.service.ecm.exception.ContentNotAvailableException {
              {static} - serialVersionUID : long
              + ContentNotAvailableException()
              + ContentNotAvailableException()
          }
        }
      }
    }
  }
  

  namespace io.radien.api {
    namespace service {
      namespace ecm {
        namespace exception {
          class io.radien.api.service.ecm.exception.ContentRepositoryNotAvailableException {
              {static} - serialVersionUID : long
          }
        }
      }
    }
  }
  

  namespace io.radien.api {
    namespace service {
      namespace ecm {
        namespace exception {
          class io.radien.api.service.ecm.exception.ElementNotFoundException {
              {static} - serialVersionUID : long
              + ElementNotFoundException()
          }
        }
      }
    }
  }
  

  namespace io.radien.api {
    namespace service {
      namespace ecm {
        namespace exception {
          class io.radien.api.service.ecm.exception.NameNotValidException {
              {static} - serialVersionUID : long
              + NameNotValidException()
          }
        }
      }
    }
  }
  

  io.radien.api.service.ecm.exception.ContentNotAvailableException -up-|> io.radien.exception.SystemException
  io.radien.api.service.ecm.exception.ContentRepositoryNotAvailableException -up-|> io.radien.exception.SystemException
  io.radien.api.service.ecm.exception.ElementNotFoundException -up-|> io.radien.exception.SystemException
  io.radien.api.service.ecm.exception.NameNotValidException -up-|> io.radien.exception.SystemException


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
