@startuml

title __JMX's Class Diagram__\n

  namespace io.radien.persistence.jmx {
    class io.radien.persistence.jmx.JpaCacheHintsMXBean {
        - value : int
        + getValue()
        + setValue()
        + tryValue()
    }
  }
  

  namespace io.radien.persistence.jmx {
    interface io.radien.persistence.jmx.JpaCacheMbean {
    }
  }
  

  io.radien.persistence.jmx.JpaCacheHintsMXBean .up.|> io.radien.persistence.jmx.JpaCacheMbean







@enduml
