@startuml

title __RD-MS-ECM-CLIENT's Class Diagram__\n

  namespace io.radien.ms.ecm.client.entities {
    class io.radien.ms.ecm.client.entities.I18NProperty {
    }
  }
  

  namespace io.radien.ms.ecm.client.entities {
    enum LabelTypeEnum {
    }
  }
  

  namespace io.radien.ms.ecm.client.entities {
    class io.radien.ms.ecm.client.entities.Translation {
    }
  }
  

  namespace io.radien.ms.ecm.client.providers {
    class io.radien.ms.ecm.client.providers.I18NPropertyMessageBodyReader {
    }
  }
  

  namespace io.radien.ms.ecm.client.providers {
    class io.radien.ms.ecm.client.providers.I18NPropertyMessageBodyWriter {
    }
  }
  

  namespace io.radien.ms.ecm.client.services {
    interface io.radien.ms.ecm.client.services.I18NPropertyResourceClient {
    }
  }
  

  namespace io.radien.ms.ecm.client.services {
    interface io.radien.ms.ecm.client.services.SystemI18NPropertyService {
    }
  }
  

  namespace io.radien.ms.ecm.client.util {
    class io.radien.ms.ecm.client.util.I18NPropertyMapper {
    }
  }
  

  namespace io.radien.ms.ecm.client.util {
    class io.radien.ms.ecm.client.util.TranslationMapper {
    }
  }
  

  io.radien.ms.ecm.client.entities.I18NProperty .up.|> java.io.Serializable
  io.radien.ms.ecm.client.entities.I18NProperty o-- io.radien.ms.ecm.client.entities.LabelTypeEnum : type
  io.radien.ms.ecm.client.providers.I18NPropertyMessageBodyReader .up.|> javax.ws.rs.ext.MessageBodyReader
  io.radien.ms.ecm.client.providers.I18NPropertyMessageBodyWriter .up.|> javax.ws.rs.ext.MessageBodyWriter







@enduml
