@startuml

title __TENANTROLE's Class Diagram__\n

  namespace io.radien.api {
    namespace model {
      namespace tenant {
        namespace ole {
          interface io.radien.api.model.tenantrole.SystemTenantRole {
              {abstract} + getRoleId()
              {abstract} + getTenantId()
              {abstract} + setRoleId()
              {abstract} + setTenantId()
          }
        }
      }
    }
  }
  

  namespace io.radien.api {
    namespace model {
      namespace tenant {
        namespace ole {
          interface io.radien.api.model.tenantrole.SystemTenantRolePermission {
              {abstract} + getPermissionId()
              {abstract} + getTenantRoleId()
              {abstract} + setPermissionId()
              {abstract} + setTenantRoleId()
          }
        }
      }
    }
  }
  

  namespace io.radien.api {
    namespace model {
      namespace tenant {
        namespace ole {
          interface io.radien.api.model.tenantrole.SystemTenantRolePermissionSearchFilter {
              {abstract} + getPermissionId()
              {abstract} + getTenantRoleId()
              {abstract} + setPermissionId()
              {abstract} + setTenantRoleId()
          }
        }
      }
    }
  }
  

  namespace io.radien.api {
    namespace model {
      namespace tenant {
        namespace ole {
          interface io.radien.api.model.tenantrole.SystemTenantRoleSearchFilter {
              {abstract} + getRoleId()
              {abstract} + getTenantId()
              {abstract} + setRoleId()
              {abstract} + setTenantId()
          }
        }
      }
    }
  }
  

  namespace io.radien.api {
    namespace model {
      namespace tenant {
        namespace ole {
          interface io.radien.api.model.tenantrole.SystemTenantRoleUser {
              {abstract} + getTenantRoleId()
              {abstract} + getUserId()
              {abstract} + setTenantRoleId()
              {abstract} + setUserId()
          }
        }
      }
    }
  }
  

  namespace io.radien.api {
    namespace model {
      namespace tenant {
        namespace ole {
          interface io.radien.api.model.tenantrole.SystemTenantRoleUserSearchFilter {
              {abstract} + getTenantRoleId()
              {abstract} + getUserId()
              {abstract} + setTenantRoleId()
              {abstract} + setUserId()
          }
        }
      }
    }
  }
  








@enduml
