@startuml

title __RD-WEB-IMPL's Class Diagram__\n

  namespace io.radien.webapp {
    abstract class io.radien.webapp.AbstractManager {
    }
  }
  

  namespace io.radien.webapp {
    enum DataModelEnum {
    }
  }
  

  namespace io.radien.webapp {
    abstract class io.radien.webapp.LazyAbstractDataModel {
    }
  }
  

  namespace io.radien.webapp {
    class io.radien.webapp.OafThemeManager {
    }
  }
  

  namespace io.radien.webapp {
    abstract class io.radien.webapp.PluginBridgingManager {
    }
  }
  

  namespace io.radien.webapp {
    class io.radien.webapp.WebApp {
    }
  }
  

  namespace io.radien.webapp {
    namespace action {
      class io.radien.webapp.action.ActionConverter {
      }
    }
  }
  

  namespace io.radien.webapp {
    namespace action {
      class io.radien.webapp.action.ActionDataModel {
      }
    }
  }
  

  namespace io.radien.webapp {
    namespace action {
      class io.radien.webapp.action.LazyActionsDataModel {
      }
    }
  }
  

  namespace io.radien.webapp {
    namespace activeTenant {
      class io.radien.webapp.activeTenant.ActiveTenantDataModelManager {
      }
    }
  }
  

  namespace io.radien.webapp {
    namespace activeTenant {
      class io.radien.webapp.activeTenant.ActiveTenantInterceptor {
      }
    }
  }
  

  namespace io.radien.webapp {
    namespace activeTenant {
      interface io.radien.webapp.activeTenant.ActiveTenantMandatory {
      }
    }
  }
  

  namespace io.radien.webapp {
    namespace authz {
      class io.radien.webapp.authz.WebAuthorizationChecker {
      }
    }
  }
  

  namespace io.radien.webapp {
    namespace contract {
      class io.radien.webapp.contract.ContractDataModel {
      }
    }
  }
  

  namespace io.radien.webapp {
    namespace contract {
      class io.radien.webapp.contract.ContractManager {
      }
    }
  }
  

  namespace io.radien.webapp {
    namespace contract {
      class io.radien.webapp.contract.LazyContractDataModel {
      }
    }
  }
  

  namespace io.radien.webapp {
    namespace i18n {
      class io.radien.webapp.i18n.LocaleManager {
      }
    }
  }
  

  namespace io.radien.webapp {
    namespace permission {
      class io.radien.webapp.permission.LazyPermissionDataModel {
      }
    }
  }
  

  namespace io.radien.webapp {
    namespace permission {
      class io.radien.webapp.permission.PermissionConverter {
      }
    }
  }
  

  namespace io.radien.webapp {
    namespace permission {
      class io.radien.webapp.permission.PermissionDataModel {
      }
    }
  }
  

  namespace io.radien.webapp {
    namespace permission {
      class io.radien.webapp.permission.PermissionManager {
      }
    }
  }
  

  namespace io.radien.webapp {
    namespace resource {
      class io.radien.webapp.resource.LazyResourcesDataModel {
      }
    }
  }
  

  namespace io.radien.webapp {
    namespace resource {
      class io.radien.webapp.resource.ResourceConverter {
      }
    }
  }
  

  namespace io.radien.webapp {
    namespace resource {
      class io.radien.webapp.resource.ResourceDataModel {
      }
    }
  }
  

  namespace io.radien.webapp {
    namespace role {
      class io.radien.webapp.role.LazyRoleDataModel {
      }
    }
  }
  

  namespace io.radien.webapp {
    namespace role {
      class io.radien.webapp.role.RoleConverter {
      }
    }
  }
  

  namespace io.radien.webapp {
    namespace role {
      class io.radien.webapp.role.RoleDataModel {
      }
    }
  }
  

  namespace io.radien.webapp {
    namespace role {
      namespace permission {
        class io.radien.webapp.role.permission.RolePermissionManager {
        }
      }
    }
  }
  

  namespace io.radien.webapp {
    namespace tenant {
      class io.radien.webapp.tenant.LazyTenantDataModel {
      }
    }
  }
  

  namespace io.radien.webapp {
    namespace tenant {
      class io.radien.webapp.tenant.TenantConverter {
      }
    }
  }
  

  namespace io.radien.webapp {
    namespace tenant {
      class io.radien.webapp.tenant.TenantDataModel {
      }
    }
  }
  

  namespace io.radien.webapp {
    namespace tenant {
      namespace ole {
        class io.radien.webapp.tenantrole.LazyTenantRoleAssociationDataModel {
        }
      }
    }
  }
  

  namespace io.radien.webapp {
    namespace tenant {
      namespace ole {
        class io.radien.webapp.tenantrole.LazyTenantRoleUserDataModel {
        }
      }
    }
  }
  

  namespace io.radien.webapp {
    namespace tenant {
      namespace ole {
        class io.radien.webapp.tenantrole.LazyTenantingUserDataModel {
        }
      }
    }
  }
  

  namespace io.radien.webapp {
    namespace tenant {
      namespace ole {
        class io.radien.webapp.tenantrole.TenantRoleAssociationDataModel {
        }
      }
    }
  }
  

  namespace io.radien.webapp {
    namespace tenant {
      namespace ole {
        class io.radien.webapp.tenantrole.TenantRoleAssociationManager {
        }
      }
    }
  }
  

  namespace io.radien.webapp {
    namespace user {
      class io.radien.webapp.user.UserDataModel {
      }
    }
  }
  

  namespace io.radien.webapp {
    namespace user {
      class io.radien.webapp.user.UserProfileManager {
      }
    }
  }
  

  namespace io.radien.webapp {
    namespace user {
      namespace tenant {
        class io.radien.webapp.user.tenant.UnAssignTenantUser {
        }
      }
    }
  }
  

  namespace io.radien.webapp {
    namespace user {
      namespace tenant {
        namespace role {
          class io.radien.webapp.user.tenant.role.UserTenantGlobalRolesManager {
          }
        }
      }
    }
  }
  

  namespace io.radien.webapp {
    namespace user {
      namespace tenant {
        namespace role {
          class io.radien.webapp.user.tenant.role.UserTenantRolesManager {
          }
        }
      }
    }
  }
  

  namespace io.radien.webapp {
    namespace util {
      class io.radien.webapp.util.DateValidator {
      }
    }
  }
  

  namespace io.radien.webapp {
    namespace util {
      class io.radien.webapp.util.EntityFilterUtil {
      }
    }
  }
  

  namespace io.radien.webapp {
    namespace util {
      class io.radien.webapp.util.TenantRoleUtil {
      }
    }
  }
  

  namespace io.radien.webapp {
    namespace util {
      namespace jsf.handler {
        class io.radien.webapp.util.jsf.handler.UnmappedResourceHandler {
        }
      }
    }
  }
  

  io.radien.webapp.AbstractManager .up.|> java.io.Serializable
  io.radien.webapp.LazyAbstractDataModel -up-|> org.primefaces.model.LazyDataModel
  io.radien.webapp.OafThemeManager .up.|> java.io.Serializable
  io.radien.webapp.OafThemeManager -up-|> io.radien.webapp.PluginBridgingManager
  io.radien.webapp.OafThemeManager o-- io.radien.api.OAFAccess : oaf
  io.radien.webapp.PluginBridgingManager .up.|> java.io.Serializable
  io.radien.webapp.PluginBridgingManager o-- io.radien.api.OAFAccess : oaf
  io.radien.webapp.PluginBridgingManager o-- io.radien.webapp.security.UserSession : userSession
  io.radien.webapp.WebApp -up-|> io.radien.webapp.AbstractWebapp
  io.radien.webapp.WebApp o-- io.radien.api.OAFAccess : oaf
  io.radien.webapp.action.ActionConverter .up.|> javax.faces.convert.Converter
  io.radien.webapp.action.ActionConverter o-- io.radien.api.service.permission.ActionRESTServiceAccess : actionRESTServiceAccess
  io.radien.webapp.action.ActionDataModel .up.|> java.io.Serializable
  io.radien.webapp.action.ActionDataModel -up-|> io.radien.webapp.AbstractManager
  io.radien.webapp.action.ActionDataModel o-- io.radien.api.model.permission.SystemAction : action
  io.radien.webapp.action.ActionDataModel o-- io.radien.webapp.activeTenant.ActiveTenantDataModelManager : activeTenantDataModelManager
  io.radien.webapp.action.ActionDataModel o-- io.radien.api.model.permission.SystemAction : selectedAction
  io.radien.webapp.action.ActionDataModel o-- io.radien.api.service.permission.ActionRESTServiceAccess : service
  io.radien.webapp.action.LazyActionsDataModel -up-|> io.radien.webapp.LazyAbstractDataModel
  io.radien.webapp.action.LazyActionsDataModel o-- io.radien.api.service.permission.ActionRESTServiceAccess : service
  io.radien.webapp.activeTenant.ActiveTenantDataModelManager .up.|> java.io.Serializable
  io.radien.webapp.activeTenant.ActiveTenantDataModelManager -up-|> io.radien.webapp.AbstractManager
  io.radien.webapp.activeTenant.ActiveTenantDataModelManager o-- io.radien.api.model.tenant.SystemActiveTenant : activeTenant
  io.radien.webapp.activeTenant.ActiveTenantDataModelManager o-- io.radien.api.service.tenant.ActiveTenantRESTServiceAccess : activeTenantRESTServiceAccess
  io.radien.webapp.activeTenant.ActiveTenantDataModelManager o-- io.radien.webapp.security.UserSession : userSession
  io.radien.webapp.activeTenant.ActiveTenantInterceptor .up.|> java.io.Serializable
  io.radien.webapp.activeTenant.ActiveTenantInterceptor -up-|> io.radien.webapp.AbstractManager
  io.radien.webapp.activeTenant.ActiveTenantInterceptor o-- io.radien.webapp.activeTenant.ActiveTenantDataModelManager : activeTenantDataModelManager
  io.radien.webapp.authz.WebAuthorizationChecker -up-|> io.radien.ms.authz.security.AuthorizationChecker
  io.radien.webapp.authz.WebAuthorizationChecker o-- io.radien.api.service.permission.PermissionRESTServiceAccess : permissionRESTServiceAccess
  io.radien.webapp.authz.WebAuthorizationChecker o-- io.radien.api.security.UserSessionEnabled : userSession
  io.radien.webapp.contract.ContractDataModel .up.|> java.io.Serializable
  io.radien.webapp.contract.ContractDataModel o-- io.radien.api.model.tenant.SystemContract : selectedContract
  io.radien.webapp.contract.ContractDataModel o-- io.radien.api.service.tenant.ContractRESTServiceAccess : service
  io.radien.webapp.contract.ContractManager -up-|> io.radien.webapp.AbstractManager
  io.radien.webapp.contract.ContractManager o-- io.radien.api.model.tenant.SystemContract : contract
  io.radien.webapp.contract.ContractManager o-- io.radien.api.service.tenant.ContractRESTServiceAccess : contractRESTServiceAccess
  io.radien.webapp.contract.LazyContractDataModel -up-|> io.radien.webapp.LazyAbstractDataModel
  io.radien.webapp.contract.LazyContractDataModel o-- io.radien.api.service.tenant.ContractRESTServiceAccess : service
  io.radien.webapp.i18n.LocaleManager .up.|> io.radien.api.webapp.i18n.LocaleManagerAccess
  io.radien.webapp.i18n.LocaleManager -up-|> io.radien.webapp.AbstractLocaleManager
  io.radien.webapp.i18n.LocaleManager o-- io.radien.api.OAFAccess : oaf
  io.radien.webapp.permission.LazyPermissionDataModel -up-|> io.radien.webapp.LazyAbstractDataModel
  io.radien.webapp.permission.LazyPermissionDataModel o-- io.radien.api.service.permission.ActionRESTServiceAccess : actionRESTServiceAccess
  io.radien.webapp.permission.LazyPermissionDataModel o-- io.radien.api.service.permission.ResourceRESTServiceAccess : resourceRESTServiceAccess
  io.radien.webapp.permission.LazyPermissionDataModel o-- io.radien.api.service.permission.PermissionRESTServiceAccess : service
  io.radien.webapp.permission.PermissionConverter .up.|> javax.faces.convert.Converter
  io.radien.webapp.permission.PermissionConverter o-- io.radien.api.service.permission.PermissionRESTServiceAccess : permissionRESTServiceAccess
  io.radien.webapp.permission.PermissionDataModel .up.|> java.io.Serializable
  io.radien.webapp.permission.PermissionDataModel -up-|> io.radien.webapp.AbstractManager
  io.radien.webapp.permission.PermissionDataModel o-- io.radien.api.service.permission.ActionRESTServiceAccess : actionRESTServiceAccess
  io.radien.webapp.permission.PermissionDataModel o-- io.radien.webapp.activeTenant.ActiveTenantDataModelManager : activeTenantDataModelManager
  io.radien.webapp.permission.PermissionDataModel o-- io.radien.webapp.permission.PermissionManager : permissionManager
  io.radien.webapp.permission.PermissionDataModel o-- io.radien.api.model.permission.SystemPermission : previousSelectedPermission
  io.radien.webapp.permission.PermissionDataModel o-- io.radien.api.service.permission.ResourceRESTServiceAccess : resourceRESTServiceAccess
  io.radien.webapp.permission.PermissionDataModel o-- io.radien.api.model.permission.SystemPermission : selectedPermission
  io.radien.webapp.permission.PermissionDataModel o-- io.radien.api.service.permission.PermissionRESTServiceAccess : service
  io.radien.webapp.permission.PermissionManager -up-|> io.radien.webapp.AbstractManager
  io.radien.webapp.permission.PermissionManager o-- io.radien.api.model.permission.SystemPermission : permission
  io.radien.webapp.permission.PermissionManager o-- io.radien.api.model.permission.SystemAction : selectedAction
  io.radien.webapp.permission.PermissionManager o-- io.radien.api.model.permission.SystemResource : selectedResource
  io.radien.webapp.permission.PermissionManager o-- io.radien.api.service.permission.ActionRESTServiceAccess : actionRESTServiceAccess
  io.radien.webapp.permission.PermissionManager o-- io.radien.api.service.permission.PermissionRESTServiceAccess : permissionRESTServiceAccess
  io.radien.webapp.permission.PermissionManager o-- io.radien.api.service.permission.ResourceRESTServiceAccess : resourceRESTServiceAccess
  io.radien.webapp.resource.LazyResourcesDataModel -up-|> io.radien.webapp.LazyAbstractDataModel
  io.radien.webapp.resource.LazyResourcesDataModel o-- io.radien.api.service.permission.ResourceRESTServiceAccess : service
  io.radien.webapp.resource.ResourceConverter .up.|> javax.faces.convert.Converter
  io.radien.webapp.resource.ResourceConverter o-- io.radien.api.service.permission.ResourceRESTServiceAccess : resourceRESTServiceAccess
  io.radien.webapp.resource.ResourceDataModel .up.|> java.io.Serializable
  io.radien.webapp.resource.ResourceDataModel -up-|> io.radien.webapp.AbstractManager
  io.radien.webapp.resource.ResourceDataModel o-- io.radien.webapp.activeTenant.ActiveTenantDataModelManager : activeTenantDataModelManager
  io.radien.webapp.resource.ResourceDataModel o-- io.radien.api.model.permission.SystemResource : resource
  io.radien.webapp.resource.ResourceDataModel o-- io.radien.api.model.permission.SystemResource : selectedResource
  io.radien.webapp.resource.ResourceDataModel o-- io.radien.api.service.permission.ResourceRESTServiceAccess : service
  io.radien.webapp.role.LazyRoleDataModel -up-|> io.radien.webapp.LazyAbstractDataModel
  io.radien.webapp.role.LazyRoleDataModel o-- io.radien.api.service.role.RoleRESTServiceAccess : service
  io.radien.webapp.role.RoleConverter .up.|> javax.faces.convert.Converter
  io.radien.webapp.role.RoleConverter o-- io.radien.api.service.role.RoleRESTServiceAccess : roleRESTServiceAccess
  io.radien.webapp.role.RoleDataModel .up.|> java.io.Serializable
  io.radien.webapp.role.RoleDataModel -up-|> io.radien.webapp.AbstractManager
  io.radien.webapp.role.RoleDataModel o-- io.radien.webapp.activeTenant.ActiveTenantDataModelManager : activeTenantDataModelManager
  io.radien.webapp.role.RoleDataModel o-- io.radien.api.model.role.SystemRole : role
  io.radien.webapp.role.RoleDataModel o-- io.radien.api.model.role.SystemRole : selectedRole
  io.radien.webapp.role.RoleDataModel o-- io.radien.api.service.role.RoleRESTServiceAccess : service
  io.radien.webapp.role.permission.RolePermissionManager .up.|> java.io.Serializable
  io.radien.webapp.role.permission.RolePermissionManager -up-|> io.radien.webapp.AbstractManager
  io.radien.webapp.role.permission.RolePermissionManager o-- io.radien.webapp.activeTenant.ActiveTenantDataModelManager : activeTenantDataModelManager
  io.radien.webapp.role.permission.RolePermissionManager o-- io.radien.api.model.tenant.SystemActiveTenant : systemActiveTenant
  io.radien.webapp.role.permission.RolePermissionManager o-- io.radien.api.model.role.SystemRole : systemRole
  io.radien.webapp.role.permission.RolePermissionManager o-- io.radien.api.service.tenantrole.TenantRolePermissionRESTServiceAccess : tenantRolePermissionRESTServiceAccess
  io.radien.webapp.role.permission.RolePermissionManager o-- io.radien.api.service.tenantrole.TenantRoleRESTServiceAccess : tenantRoleRESTServiceAccess
  io.radien.webapp.role.permission.RolePermissionManager o-- io.radien.webapp.util.TenantRoleUtil : tenantRoleUtil
  io.radien.webapp.tenant.LazyTenantDataModel -up-|> io.radien.webapp.LazyAbstractDataModel
  io.radien.webapp.tenant.LazyTenantDataModel o-- io.radien.api.service.tenant.TenantRESTServiceAccess : service
  io.radien.webapp.tenant.TenantConverter .up.|> javax.faces.convert.Converter
  io.radien.webapp.tenant.TenantConverter o-- io.radien.api.service.tenant.TenantRESTServiceAccess : tenantRESTServiceAccess
  io.radien.webapp.tenant.TenantDataModel .up.|> java.io.Serializable
  io.radien.webapp.tenant.TenantDataModel -up-|> io.radien.webapp.AbstractManager
  io.radien.webapp.tenant.TenantDataModel o-- io.radien.webapp.activeTenant.ActiveTenantDataModelManager : activeTenantDataModelManager
  io.radien.webapp.tenant.TenantDataModel o-- io.radien.api.service.tenant.ActiveTenantRESTServiceAccess : activeTenantRESTServiceAccess
  io.radien.webapp.tenant.TenantDataModel o-- io.radien.api.model.tenant.SystemTenant : selectedTenant
  io.radien.webapp.tenant.TenantDataModel o-- io.radien.api.service.tenant.TenantRESTServiceAccess : service
  io.radien.webapp.tenant.TenantDataModel o-- io.radien.api.model.tenant.SystemTenant : tenant
  io.radien.webapp.tenant.TenantDataModel o-- io.radien.webapp.security.UserSession : userSession
  io.radien.webapp.tenantrole.LazyTenantRoleAssociationDataModel -up-|> io.radien.webapp.LazyAbstractDataModel
  io.radien.webapp.tenantrole.LazyTenantRoleAssociationDataModel o-- io.radien.api.service.role.RoleRESTServiceAccess : roleService
  io.radien.webapp.tenantrole.LazyTenantRoleAssociationDataModel o-- io.radien.api.service.tenantrole.TenantRoleRESTServiceAccess : service
  io.radien.webapp.tenantrole.LazyTenantRoleAssociationDataModel o-- io.radien.api.service.tenant.TenantRESTServiceAccess : tenantService
  io.radien.webapp.tenantrole.LazyTenantRoleUserDataModel -up-|> io.radien.webapp.LazyAbstractDataModel
  io.radien.webapp.tenantrole.LazyTenantRoleUserDataModel o-- io.radien.api.service.tenantrole.TenantRoleUserRESTServiceAccess : service
  io.radien.webapp.tenantrole.LazyTenantRoleUserDataModel o-- io.radien.api.service.user.UserRESTServiceAccess : userService
  io.radien.webapp.tenantrole.LazyTenantingUserDataModel -up-|> io.radien.webapp.LazyAbstractDataModel
  io.radien.webapp.tenantrole.LazyTenantingUserDataModel o-- io.radien.api.service.tenantrole.TenantRoleUserRESTServiceAccess : service
  io.radien.webapp.tenantrole.LazyTenantingUserDataModel o-- io.radien.api.service.user.UserRESTServiceAccess : userService
  io.radien.webapp.tenantrole.TenantRoleAssociationDataModel -up-|> io.radien.webapp.AbstractManager
  io.radien.webapp.tenantrole.TenantRoleAssociationDataModel o-- io.radien.webapp.activeTenant.ActiveTenantDataModelManager : activeTenantDataModelManager
  io.radien.webapp.tenantrole.TenantRoleAssociationDataModel o-- io.radien.api.service.role.RoleRESTServiceAccess : roleRESTServiceAccess
  io.radien.webapp.tenantrole.TenantRoleAssociationDataModel o-- io.radien.api.model.tenantrole.SystemTenantRole : selectedAssociation
  io.radien.webapp.tenantrole.TenantRoleAssociationDataModel o-- io.radien.api.service.tenantrole.TenantRoleRESTServiceAccess : service
  io.radien.webapp.tenantrole.TenantRoleAssociationDataModel o-- io.radien.api.service.tenant.TenantRESTServiceAccess : tenantRESTServiceAccess
  io.radien.webapp.tenantrole.TenantRoleAssociationManager -up-|> io.radien.webapp.AbstractManager
  io.radien.webapp.tenantrole.TenantRoleAssociationManager o-- io.radien.webapp.activeTenant.ActiveTenantDataModelManager : activeTenantDataModelManager
  io.radien.webapp.tenantrole.TenantRoleAssociationManager o-- io.radien.webapp.tenantrole.LazyTenantRoleUserDataModel : lazyModel
  io.radien.webapp.tenantrole.TenantRoleAssociationManager o-- io.radien.api.model.permission.SystemPermission : permission
  io.radien.webapp.tenantrole.TenantRoleAssociationManager o-- io.radien.api.model.permission.SystemPermission : previousSelectedPermissionToUnAssign
  io.radien.webapp.tenantrole.TenantRoleAssociationManager o-- io.radien.api.model.tenantrole.SystemTenantRoleUser : previousSelectedUserToUnAssign
  io.radien.webapp.tenantrole.TenantRoleAssociationManager o-- io.radien.api.model.role.SystemRole : role
  io.radien.webapp.tenantrole.TenantRoleAssociationManager o-- io.radien.api.service.role.RoleRESTServiceAccess : roleRESTServiceAccess
  io.radien.webapp.tenantrole.TenantRoleAssociationManager o-- io.radien.api.model.permission.SystemPermission : selectedPermissionToUnAssign
  io.radien.webapp.tenantrole.TenantRoleAssociationManager o-- io.radien.api.model.tenantrole.SystemTenantRoleUser : selectedUserToUnAssign
  io.radien.webapp.tenantrole.TenantRoleAssociationManager o-- io.radien.api.model.tenant.SystemTenant : tenant
  io.radien.webapp.tenantrole.TenantRoleAssociationManager o-- io.radien.api.service.tenant.TenantRESTServiceAccess : tenantRESTServiceAccess
  io.radien.webapp.tenantrole.TenantRoleAssociationManager o-- io.radien.api.model.tenantrole.SystemTenantRole : tenantRole
  io.radien.webapp.tenantrole.TenantRoleAssociationManager o-- io.radien.api.service.tenantrole.TenantRolePermissionRESTServiceAccess : tenantRolePermissionRESTServiceAccess
  io.radien.webapp.tenantrole.TenantRoleAssociationManager o-- io.radien.api.service.tenantrole.TenantRoleRESTServiceAccess : tenantRoleRESTServiceAccess
  io.radien.webapp.tenantrole.TenantRoleAssociationManager o-- io.radien.api.service.tenantrole.TenantRoleUserRESTServiceAccess : tenantRoleUserRESTServiceAccess
  io.radien.webapp.tenantrole.TenantRoleAssociationManager o-- io.radien.webapp.util.TenantRoleUtil : tenantRoleUtil
  io.radien.webapp.tenantrole.TenantRoleAssociationManager o-- io.radien.api.model.user.SystemUser : user
  io.radien.webapp.tenantrole.TenantRoleAssociationManager o-- io.radien.api.service.user.UserRESTServiceAccess : userRESTServiceAccess
  io.radien.webapp.tenantrole.TenantRoleAssociationManager o-- io.radien.webapp.authz.WebAuthorizationChecker : webAuthorizationChecker
  io.radien.webapp.user.UserDataModel .up.|> java.io.Serializable
  io.radien.webapp.user.UserDataModel -up-|> io.radien.webapp.AbstractManager
  io.radien.webapp.user.UserDataModel o-- io.radien.api.service.permission.ActionRESTServiceAccess : actionRESTServiceAccess
  io.radien.webapp.user.UserDataModel o-- io.radien.webapp.activeTenant.ActiveTenantDataModelManager : activeTenantDataModelManager
  io.radien.webapp.user.UserDataModel o-- io.radien.api.service.permission.PermissionRESTServiceAccess : permissionRESTServiceAccess
  io.radien.webapp.user.UserDataModel o-- io.radien.api.service.permission.ResourceRESTServiceAccess : resourceRESTServiceAccess
  io.radien.webapp.user.UserDataModel o-- io.radien.api.model.user.SystemUser : selectedUser
  io.radien.webapp.user.UserDataModel o-- io.radien.api.service.user.UserRESTServiceAccess : service
  io.radien.webapp.user.UserDataModel o-- io.radien.api.service.tenantrole.TenantRoleUserRESTServiceAccess : tenantRoleUserRESTServiceAccess
  io.radien.webapp.user.UserDataModel o-- io.radien.api.model.user.SystemUser : user
  io.radien.webapp.user.UserDataModel o-- io.radien.api.model.user.SystemUser : userForTenantAssociation
  io.radien.webapp.user.UserDataModel o-- io.radien.api.security.UserSessionEnabled : userSessionEnabled
  io.radien.webapp.user.UserDataModel o-- io.radien.webapp.authz.WebAuthorizationChecker : webAuthorizationChecker
  io.radien.webapp.user.UserProfileManager -up-|> io.radien.webapp.AbstractManager
  io.radien.webapp.user.UserProfileManager o-- io.radien.api.model.user.SystemUser : clonedLogInUser
  io.radien.webapp.user.UserProfileManager o-- io.radien.api.model.tenant.SystemTenant : selectedTenantToUnAssign
  io.radien.webapp.user.UserProfileManager o-- io.radien.api.service.tenantrole.TenantRoleRESTServiceAccess : tenantRoleRESTServiceAccess
  io.radien.webapp.user.UserProfileManager o-- io.radien.api.service.tenantrole.TenantRoleUserRESTServiceAccess : tenantRoleUserRESTServiceAccess
  io.radien.webapp.user.UserProfileManager o-- io.radien.api.service.user.UserRESTServiceAccess : userService
  io.radien.webapp.user.UserProfileManager o-- io.radien.webapp.security.UserSession : userSession
  io.radien.webapp.user.tenant.UnAssignTenantUser -up-|> io.radien.webapp.AbstractManager
  io.radien.webapp.user.tenant.UnAssignTenantUser o-- io.radien.webapp.activeTenant.ActiveTenantDataModelManager : activeTenantDataModelManager
  io.radien.webapp.user.tenant.UnAssignTenantUser o-- io.radien.api.service.tenantrole.TenantRoleUserRESTServiceAccess : tenantRoleUserRESTServiceAccess
  io.radien.webapp.user.tenant.UnAssignTenantUser o-- io.radien.webapp.user.UserDataModel : userDataModel
  io.radien.webapp.user.tenant.role.UserTenantGlobalRolesManager -up-|> io.radien.webapp.AbstractManager
  io.radien.webapp.user.tenant.role.UserTenantGlobalRolesManager o-- io.radien.webapp.activeTenant.ActiveTenantDataModelManager : activeTenantDataModelManager
  io.radien.webapp.user.tenant.role.UserTenantGlobalRolesManager o-- io.radien.api.model.tenant.SystemActiveTenant : systemActiveTenant
  io.radien.webapp.user.tenant.role.UserTenantGlobalRolesManager o-- io.radien.api.service.tenant.TenantRESTServiceAccess : tenantRESTServiceAccess
  io.radien.webapp.user.tenant.role.UserTenantGlobalRolesManager o-- io.radien.webapp.authz.WebAuthorizationChecker : webAuthorizationChecker
  io.radien.webapp.user.tenant.role.UserTenantRolesManager .up.|> java.io.Serializable
  io.radien.webapp.user.tenant.role.UserTenantRolesManager -up-|> io.radien.webapp.AbstractManager
  io.radien.webapp.user.tenant.role.UserTenantRolesManager o-- io.radien.api.model.tenant.SystemTenant : tenant
  io.radien.webapp.user.tenant.role.UserTenantRolesManager o-- io.radien.api.service.tenantrole.TenantRoleRESTServiceAccess : tenantRoleRESTServiceAccess
  io.radien.webapp.user.tenant.role.UserTenantRolesManager o-- io.radien.api.service.tenantrole.TenantRoleUserRESTServiceAccess : tenantRoleUserRESTServiceAccess
  io.radien.webapp.user.tenant.role.UserTenantRolesManager o-- io.radien.webapp.util.TenantRoleUtil : tenantRoleUtil
  io.radien.webapp.user.tenant.role.UserTenantRolesManager o-- io.radien.webapp.user.UserDataModel : userDataModel
  io.radien.webapp.util.DateValidator .up.|> javax.faces.validator.Validator
  io.radien.webapp.util.EntityFilterUtil -up-|> io.radien.webapp.AbstractManager
  io.radien.webapp.util.EntityFilterUtil o-- io.radien.api.service.permission.PermissionRESTServiceAccess : permissionRESTServiceAccess
  io.radien.webapp.util.EntityFilterUtil o-- io.radien.api.service.role.RoleRESTServiceAccess : roleRESTServiceAccess
  io.radien.webapp.util.EntityFilterUtil o-- io.radien.api.service.tenant.TenantRESTServiceAccess : tenantRESTServiceAccess
  io.radien.webapp.util.TenantRoleUtil -up-|> io.radien.webapp.AbstractManager
  io.radien.webapp.util.TenantRoleUtil o-- io.radien.api.service.tenantrole.TenantRoleRESTServiceAccess : tenantRoleRESTServiceAccess
  io.radien.webapp.util.jsf.handler.UnmappedResourceHandler -up-|> javax.faces.application.ResourceHandlerWrapper


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
