@startuml

title __ENTITIES's Class Diagram__\n

  namespace io.radien.ms.ecm {
    namespace entities {
      class io.radien.ms.ecm.entities.I18NPropertyEntity {
          - key : String
          - translations : List<TranslationEntity>
          + equals()
          + getKey()
          + getTranslations()
          + getType()
          + hashCode()
          + setKey()
          + setTranslations()
          + setType()
      }
    }
  }
  

  namespace io.radien.ms.ecm {
    namespace entities {
      class io.radien.ms.ecm.entities.TranslationEntity {
          - description : String
          - language : String
          + equals()
          + getDescription()
          + getLanguage()
          + hashCode()
          + setDescription()
          + setLanguage()
      }
    }
  }
  

  io.radien.ms.ecm.entities.I18NPropertyEntity .up.|> java.io.Serializable
  io.radien.ms.ecm.entities.I18NPropertyEntity o-- io.radien.ms.ecm.client.entities.LabelTypeEnum : type


 

@enduml
