@startuml

title __SERVICE's Class Diagram__\n

  namespace io.radien.ms.tenantmanagement {
    namespace service {
      class io.radien.ms.tenantmanagement.service.ActiveTenantResource {
          {static} - log : Logger
          + create()
          + delete()
          + delete()
          + exists()
          + get()
          + getAll()
          + getById()
          + getByUserAndTenant()
          + update()
      }
    }
  }
  

  namespace io.radien.ms.tenantmanagement {
    namespace service {
      class io.radien.ms.tenantmanagement.service.ActiveTenantService {
          {static} - serialVersionUID : long
          + create()
          + delete()
          + delete()
          + delete()
          + exists()
          + get()
          + get()
          + getAll()
          + getByUserAndTenant()
          + update()
          # delete()
          - getCount()
          - getFieldPredicate()
          - getFilteredPredicate()
      }
    }
  }
  

  namespace io.radien.ms.tenantmanagement {
    namespace service {
      class io.radien.ms.tenantmanagement.service.ContractResource {
          {static} - log : Logger
          + create()
          + delete()
          + exists()
          + get()
          + getAll()
          + getById()
          + getTotalRecordsCount()
          + update()
      }
    }
  }
  

  namespace io.radien.ms.tenantmanagement {
    namespace service {
      class io.radien.ms.tenantmanagement.service.ContractService {
          {static} - log : Logger
          {static} - serialVersionUID : long
          + create()
          + delete()
          + delete()
          + exists()
          + get()
          + get()
          + getAll()
          + getTotalRecordsCount()
          + update()
          - getCount()
          - searchDuplicatedFields()
      }
    }
  }
  

  namespace io.radien.ms.tenantmanagement {
    namespace service {
      class io.radien.ms.tenantmanagement.service.EntityManagerHolder {
          - em : EntityManager
          + getEm()
      }
    }
  }
  

  namespace io.radien.ms.tenantmanagement {
    namespace service {
      class io.radien.ms.tenantmanagement.service.TenantResource {
          {static} - log : Logger
          + create()
          + delete()
          + deleteTenantHierarchy()
          + exists()
          + get()
          + getAll()
          + getById()
          + update()
      }
    }
  }
  

  namespace io.radien.ms.tenantmanagement {
    namespace service {
      class io.radien.ms.tenantmanagement.service.TenantService {
          {static} - log : Logger
          {static} - serialVersionUID : long
          + create()
          + delete()
          + delete()
          + deleteTenantHierarchy()
          + exists()
          + get()
          + get()
          + getAll()
          + update()
          # delete()
          # deleteChildren()
          # getChildren()
          - getCount()
          - getFieldPredicate()
          - getFilteredPredicate()
          - searchDuplicatedFields()
          - validateClientTenant()
          - validateIfFieldsAreEmpty()
          - validateRootTenant()
          - validateSubTenant()
          - validateTenant()
      }
    }
  }
  

  io.radien.ms.tenantmanagement.service.ActiveTenantResource .up.|> io.radien.ms.tenantmanagement.client.services.ActiveTenantResourceClient
  io.radien.ms.tenantmanagement.service.ActiveTenantResource o-- io.radien.api.service.tenant.ActiveTenantServiceAccess : activeTenantServiceAccess
  io.radien.ms.tenantmanagement.service.ActiveTenantService .up.|> io.radien.api.service.tenant.ActiveTenantServiceAccess
  io.radien.ms.tenantmanagement.service.ActiveTenantService o-- io.radien.ms.tenantmanagement.service.EntityManagerHolder : emh
  io.radien.ms.tenantmanagement.service.ContractResource .up.|> io.radien.ms.tenantmanagement.client.services.ContractResourceClient
  io.radien.ms.tenantmanagement.service.ContractResource o-- io.radien.api.service.tenant.ContractServiceAccess : contractService
  io.radien.ms.tenantmanagement.service.ContractService .up.|> io.radien.api.service.tenant.ContractServiceAccess
  io.radien.ms.tenantmanagement.service.ContractService o-- io.radien.ms.tenantmanagement.service.EntityManagerHolder : emh
  io.radien.ms.tenantmanagement.service.TenantResource .up.|> io.radien.ms.tenantmanagement.client.services.TenantResourceClient
  io.radien.ms.tenantmanagement.service.TenantResource o-- io.radien.api.service.tenant.TenantServiceAccess : tenantService
  io.radien.ms.tenantmanagement.service.TenantService .up.|> io.radien.api.service.tenant.TenantServiceAccess
  io.radien.ms.tenantmanagement.service.TenantService o-- io.radien.ms.tenantmanagement.service.EntityManagerHolder : emh







@enduml
