@startuml

title __ACTION's Class Diagram__\n

  namespace io.radien.webapp {
    namespace action {
      class io.radien.webapp.action.ActionConverter {
          + getAsObject()
          + getAsString()
      }
    }
  }
  

  namespace io.radien.webapp {
    namespace action {
      class io.radien.webapp.action.ActionDataModel {
          - lazyModel : LazyDataModel<? extends SystemAction>
          + delete()
          + edit()
          + editRecords()
          + getAction()
          + getLazyModel()
          + getSelectedAction()
          + getService()
          + init()
          + onRowSelect()
          + onload()
          + returnToDataTableRecords()
          + save()
          + setAction()
          + setLazyModel()
          + setSelectedAction()
          + setService()
      }
    }
  }
  

  namespace io.radien.webapp {
    namespace action {
      class io.radien.webapp.action.LazyActionsDataModel {
          {static} - serialVersionUID : long
          + LazyActionsDataModel()
          + getData()
      }
    }
  }
  

  io.radien.webapp.action.ActionConverter .up.|> javax.faces.convert.Converter
  io.radien.webapp.action.ActionConverter o-- io.radien.api.service.permission.ActionRESTServiceAccess : actionRESTServiceAccess
  io.radien.webapp.action.ActionDataModel .up.|> java.io.Serializable
  io.radien.webapp.action.ActionDataModel -up-|> io.radien.webapp.AbstractManager
  io.radien.webapp.action.ActionDataModel o-- io.radien.api.model.permission.SystemAction : action
  io.radien.webapp.action.ActionDataModel o-- io.radien.webapp.activeTenant.ActiveTenantDataModelManager : activeTenantDataModelManager
  io.radien.webapp.action.ActionDataModel o-- io.radien.api.model.permission.SystemAction : selectedAction
  io.radien.webapp.action.ActionDataModel o-- io.radien.api.service.permission.ActionRESTServiceAccess : service
  io.radien.webapp.action.LazyActionsDataModel -up-|> io.radien.webapp.LazyAbstractDataModel
  io.radien.webapp.action.LazyActionsDataModel o-- io.radien.api.service.permission.ActionRESTServiceAccess : service


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
