@startuml

title __RD-MS-ECM's Class Diagram__\n

  namespace io.radien.ms.ecm {
    class io.radien.ms.ecm.ContentRepository {
    }
  }
  

  namespace io.radien.ms.ecm {
    class io.radien.ms.ecm.ECMApplication {
    }
  }
  

  namespace io.radien.ms.ecm {
    namespace config {
      class io.radien.ms.ecm.config.ConfigController {
      }
    }
  }
  

  namespace io.radien.ms.ecm {
    namespace constants {
      class io.radien.ms.ecm.constants.CmsConstants {
      }
    }
  }
  

  namespace io.radien.ms.ecm {
    namespace entities {
      class io.radien.ms.ecm.entities.I18NPropertyEntity {
      }
    }
  }
  

  namespace io.radien.ms.ecm {
    namespace entities {
      class io.radien.ms.ecm.entities.TranslationEntity {
      }
    }
  }
  

  namespace io.radien.ms.ecm {
    namespace factory {
      class io.radien.ms.ecm.factory.ContentFactory {
      }
    }
  }
  

  namespace io.radien.ms.ecm {
    namespace factory {
      class io.radien.ms.ecm.factory.I18NPropertyEntityFactory {
      }
    }
  }
  

  namespace io.radien.ms.ecm {
    namespace factory {
      class io.radien.ms.ecm.factory.TranslationEntityFactory {
      }
    }
  }
  

  namespace io.radien.ms.ecm {
    namespace jcr {
      class io.radien.ms.ecm.jcr.JCRRepositoryProducer {
      }
    }
  }
  

  namespace io.radien.ms.ecm {
    namespace jcr {
      class io.radien.ms.ecm.jcr.JCRSessionProducer {
      }
    }
  }
  

  namespace io.radien.ms.ecm {
    namespace resource {
      class io.radien.ms.ecm.resource.I18NPropertyResource {
      }
    }
  }
  

  namespace io.radien.ms.ecm {
    namespace service {
      class io.radien.ms.ecm.service.ContentService {
      }
    }
  }
  

  namespace io.radien.ms.ecm {
    namespace service {
      class io.radien.ms.ecm.service.I18NPropertyService {
      }
    }
  }
  

  namespace io.radien.ms.ecm {
    namespace util {
      class io.radien.ms.ecm.util.EntityManagerProducer {
      }
    }
  }
  

  namespace io.radien.ms.ecm {
    namespace util {
      class io.radien.ms.ecm.util.I18NPropertyEntityMapper {
      }
    }
  }
  

  namespace io.radien.ms.ecm {
    namespace util {
      class io.radien.ms.ecm.util.OafConstants {
      }
    }
  }
  

  namespace io.radien.ms.ecm {
    namespace util {
      class io.radien.ms.ecm.util.ResourceBundleLoader {
      }
    }
  }
  

  namespace io.radien.ms.ecm {
    namespace util {
      class io.radien.ms.ecm.util.TranslationEntityMapper {
      }
    }
  }
  

  io.radien.ms.ecm.ContentRepository .up.|> io.radien.api.Appframeable
  io.radien.ms.ecm.ContentRepository .up.|> java.io.Serializable
  io.radien.ms.ecm.ContentRepository o-- io.radien.ms.ecm.factory.ContentFactory : contentFactory
  io.radien.ms.ecm.ContentRepository o-- io.radien.api.OAFAccess : oaf
  io.radien.ms.ecm.ECMApplication -up-|> javax.ws.rs.core.Application
  io.radien.ms.ecm.config.ConfigController .up.|> io.radien.api.OAFAccess
  io.radien.ms.ecm.entities.I18NPropertyEntity .up.|> java.io.Serializable
  io.radien.ms.ecm.entities.I18NPropertyEntity o-- io.radien.ms.ecm.client.entities.LabelTypeEnum : type
  io.radien.ms.ecm.factory.ContentFactory .up.|> java.io.Serializable
  io.radien.ms.ecm.jcr.JCRRepositoryProducer .up.|> java.io.Serializable
  io.radien.ms.ecm.jcr.JCRRepositoryProducer o-- io.radien.api.OAFAccess : oaf
  io.radien.ms.ecm.jcr.JCRSessionProducer .up.|> java.io.Serializable
  io.radien.ms.ecm.resource.I18NPropertyResource .up.|> io.radien.ms.ecm.client.services.I18NPropertyResourceClient
  io.radien.ms.ecm.resource.I18NPropertyResource o-- io.radien.api.OAFAccess : oafAccess
  io.radien.ms.ecm.resource.I18NPropertyResource o-- io.radien.ms.ecm.client.services.SystemI18NPropertyService : propertyManager
  io.radien.ms.ecm.service.ContentService .up.|> io.radien.api.service.ecm.ContentServiceAccess
  io.radien.ms.ecm.service.ContentService o-- io.radien.ms.ecm.ContentRepository : contentRepository
  io.radien.ms.ecm.service.ContentService o-- io.radien.ms.ecm.factory.ContentFactory : factory
  io.radien.ms.ecm.service.I18NPropertyService .up.|> io.radien.ms.ecm.client.services.SystemI18NPropertyService
  io.radien.ms.ecm.service.I18NPropertyService o-- io.radien.api.OAFAccess : oafAccess
  io.radien.ms.ecm.util.ResourceBundleLoader .up.|> java.io.Serializable


 

@enduml
