@startuml

title __BATCH's Class Diagram__\n

  namespace io.radien.ms.usermanagement {
    namespace batch {
      class io.radien.ms.usermanagement.batch.BatchResponse {
          {static} + get()
      }
    }
  }
  



 

@enduml
