@startuml

title __CONSTANTS's Class Diagram__\n

  namespace io.radien.ms.ecm {
    namespace constants {
      class io.radien.ms.ecm.constants.CmsConstants {
          {static} + ATTR_EDIT_ENABLED : String
          {static} + COMPONENT_TYPE_PAGE : String
          {static} + JCR_CREATED : String
          {static} + NN_METADATA : String
          {static} + NT_NOTIFICATION : String
          {static} + NT_STATIC_CONTENT : String
          {static} + OAF_ACTIVE : String
          {static} + OAF_APP : String
          {static} + OAF_CONTENT_AUTHOR : String
          {static} + OAF_CONTENT_LANG : String
          {static} + OAF_CONTENT_PERMISSIONS : String
          {static} + OAF_CONTENT_TYPE : String
          {static} + OAF_CREATED : String
          {static} + OAF_FILE_SIZE : String
          {static} + OAF_HTML_CONTENT : String
          {static} + OAF_IMAGE : String
          {static} + OAF_IMAGE_MIME_TYPE : String
          {static} + OAF_IMAGE_NAME : String
          {static} + OAF_LAST_EDIT_DATE : String
          {static} + OAF_MANDATORY_APPROVAL : String
          {static} + OAF_MANDATORY_VIEW : String
          {static} + OAF_MIXIN_MANDATORY_CONTENT : String
          {static} + OAF_MIXIN_NODE_PROPS : String
          {static} + OAF_MIXIN_VERSION : String
          {static} + OAF_MIXIN_VERSIONABLE : String
          {static} + OAF_MIXIN_VERSIONABLE_CREATE : String
          {static} + OAF_NAME : String
          {static} + OAF_STEP : String
          {static} + OAF_SYSTEM : String
          {static} + OAF_TAGS : String
          {static} + OAF_VALID_DATE : String
          {static} + OAF_VERSION : String
          {static} + OAF_VERSION_COMMENT : String
          {static} + OAF_VIEW_ID : String
          {static} + PN_LAST_MODIFIED_BY : String
          {static} + USER_ADMIN : String
          {static} # PUBLISHABLE_TYPES : String[]
          {static} - NAMESPACE : String
          {static} - NT_APP_INFO : String
          {static} - NT_FILE : String
          {static} - NT_NEWS_FEED : String
          {static} - NT_VIDEO : String
          - CmsConstants()
      }
    }
  }
  

  namespace io.radien.ms.ecm {
    namespace constants {
      class io.radien.ms.ecm.constants.CmsConstants.PropertyKeys {
          {static} + OAF_NODE_TYPES : String
          {static} + SYSTEM_CMS_CFG_NODE_APP_INFO : String
          {static} + SYSTEM_CMS_CFG_NODE_DOCS : String
          {static} + SYSTEM_CMS_CFG_NODE_HTML : String
          {static} + SYSTEM_CMS_CFG_NODE_IFRAME : String
          {static} + SYSTEM_CMS_CFG_NODE_IMAGE : String
          {static} + SYSTEM_CMS_CFG_NODE_NEWS_FEED : String
          {static} + SYSTEM_CMS_CFG_NODE_NOTIFICATION : String
          {static} + SYSTEM_CMS_CFG_NODE_ROOT : String
          {static} + SYSTEM_CMS_CFG_NODE_STATIC_CONTENT : String
          {static} + SYSTEM_CMS_CFG_NODE_TAG : String
          {static} + SYSTEM_DMS_CFG_AUTO_CREATE_FOLDERS : String
          - PropertyKeys()
      }
    }
  }
  

  io.radien.ms.ecm.constants.CmsConstants +-down- io.radien.ms.ecm.constants.CmsConstants.PropertyKeys


 

@enduml
