@startuml

title __MAIL's Class Diagram__\n

  namespace io.radien.api {
    namespace service {
      namespace mail {
        interface io.radien.api.service.mail.MailServiceAccess {
            {abstract} + create()
            {abstract} + create()
            {abstract} + create()
            {abstract} + create()
            {abstract} + create()
            {abstract} + create()
            {abstract} + send()
            {abstract} + sendMailAsync()
        }
      }
    }
  }
  

  namespace io.radien.api {
    namespace service {
      namespace mail {
        interface io.radien.api.service.mail.MailTemplateAccess {
        }
      }
    }
  }
  








@enduml
