FROM jboss/keycloak:15.0.1
#ENV KEYCLOAK_USER=raiden \
#    KEYCLOAK_PASSWORD=brutality
#    KEYCLOAK_IMPORT=/tmp/master.json
#    KEYCLOAK_WELCOME_THEME=
#    KEYCLOAK_DEFAULT_THEME=

#https://www.baeldung.com/spring-keycloak-custom-themes
#COPY themes /opt/jboss/keycloak/themes


# kcadm.sh config credentials --server http://localhost:8080/auth --realm master --user raiden brutality

# Deploy Keycloak custom themes
# Refer the file in the microservice rd-ms-keycloak-themes/README.md


