@startuml

title __API's Class Diagram__\n

  namespace io.radien.api {
    interface io.radien.api.Appframeable {
        {abstract} + getOAF()
    }
  }
  

  namespace io.radien.api {
    interface io.radien.api.Configurable {
        {abstract} + getProperty()
    }
  }
  

  namespace io.radien.api {
    interface io.radien.api.Event {
    }
  }
  

  namespace io.radien.api {
    interface io.radien.api.IAppframe {
        {abstract} + getLog()
        {abstract} + getVersion()
        {abstract} + setLog()
        {abstract} + setVersion()
    }
  }
  

  namespace io.radien.api {
    enum KeycloakConfigs {
      ADMIN_CLIENT_ID
      ADMIN_PASSWORD
      ADMIN_REALM
      ADMIN_URL
      ADMIN_USER
      APP_REALM
      IDP_URL
      RADIEN_CLIENT_ID
      RADIEN_PASSWORD
      RADIEN_SECRET
      RADIEN_TOKEN_PATH
      RADIEN_USERNAME
      TOKEN_PATH
      USER_PATH
      propKey
    }
  }
  

  namespace io.radien.api {
    interface io.radien.api.Model {
        {abstract} + getCreateDate()
        {abstract} + getCreateUser()
        {abstract} + getId()
        {abstract} + getLastUpdate()
        {abstract} + getLastUpdateUser()
        {abstract} + setCreateDate()
        {abstract} + setCreateUser()
        {abstract} + setId()
        {abstract} + setLastUpdate()
        {abstract} + setLastUpdateUser()
    }
  }
  

  namespace io.radien.api {
    interface io.radien.api.OAFAccess {
        {abstract} + findLocale()
        {abstract} + fireEvent()
        {abstract} + getDefaultLocale()
        {abstract} + getProperty()
        {abstract} + getResourceBundle()
        {abstract} + getSupportedLocales()
        {abstract} + getSystemAdminUserId()
        {abstract} + getVersion()
    }
  }
  

  namespace io.radien.api {
    enum OAFProperties {
      AUTH_LOGOUT_URI
      CMS_MS_URL
      INITIALIZER_DYNAMODB_HEARTBEAT_PERIOD
      INITIALIZER_DYNAMODB_LEASE_DURATION
      INITIALIZER_DYNAMODB_LOCAL
      INITIALIZER_DYNAMODB_REGION
      INITIALIZER_DYNAMODB_TABLE_NAME
      MODULE_CMS_DYNAMIC_CONTENT_MENU_ENABLED
      MODULE_CMS_ENABLED
      MODULE_MONGODB_ENABLED
      MODULE_SAML_ENABLED
      OAF_NODE_TYPES
      PLUGIN_INITIALIZER_CONNECTION_TIMEOUT
      PLUGIN_INITIALIZER_READ_TIMEOUT
      PLUGIN_INITIALIZER_URL
      SCHEDULER_MS_CONN_TIMEOUT
      SCHEDULER_MS_READ_TIMEOUT
      SCHEDULER_MS_URL
      SCHEDULER_MS_URL_DELETE
      SCHEDULER_MS_URL_REGISTER
      SYSTEM_CFG_SCIM_ENABLED
      SYSTEM_CFG_SCIM_USER_ENDPOINT
      SYSTEM_CMS_CFG_NODE_APP_INFO
      SYSTEM_CMS_CFG_NODE_DOCS
      SYSTEM_CMS_CFG_NODE_HTML
      SYSTEM_CMS_CFG_NODE_IFRAME
      SYSTEM_CMS_CFG_NODE_IMAGE
      SYSTEM_CMS_CFG_NODE_NEWS_FEED
      SYSTEM_CMS_CFG_NODE_NOTIFICATION
      SYSTEM_CMS_CFG_NODE_ROOT
      SYSTEM_CMS_CFG_NODE_STATIC_CONTENT
      SYSTEM_CMS_CFG_NODE_TAG
      SYSTEM_CMS_REPO_CONF_DIR
      SYSTEM_CMS_REPO_HOME_DIR
      SYSTEM_CONFIGURATION_CAPTCHA
      SYSTEM_CONFIGURATION_CAPTCHA_ENABLED
      SYSTEM_DMS_CFG_AUTO_CREATE_FOLDERS
      SYSTEM_MS_CONFIG_DEFAULT_LANG_ECM
      SYSTEM_MS_CONFIG_SUPPORTED_LANG_ECM
      SYSTEM_MS_ENDPOINT_ECM
      SYSTEM_MS_ENDPOINT_PERMISSIONMANAGEMENT
      SYSTEM_MS_ENDPOINT_ROLEMANAGEMENT
      SYSTEM_MS_ENDPOINT_TENANTMANAGEMENT
      SYSTEM_MS_ENDPOINT_USERMANAGEMENT
      SYSTEM_MS_SECRET_ECM
      SYS_APPLICATION_CONTEXT
      SYS_APP_NAME
      SYS_AUTHENTICATION_CHECK_TERMDATE
      SYS_AUTHENTICATION_ENABLED
      SYS_AUTHENTICATION_LOGOUT_REDIRECT_URL
      SYS_AUTHENTICATION_LOGOUT_REDIRECT_URL_ENABLED
      SYS_AUTHENTICATION_OIDC_ENABLED
      SYS_AUTHENTICATION_OIDC_PUBLIC_REQUIRED
      SYS_AUTO_LOGIN_ENABLED
      SYS_CFG_CONTEXT_PAGE
      SYS_CFG_DEFAULT_LANDING_PAGE
      SYS_CFG_JSF_MAPPING
      SYS_CFG_LOGIN_PAGE
      SYS_CFG_TERM_PAGE
      SYS_DATASOURCE
      SYS_DATASOURCE_CUSTOM1
      SYS_DATASOURCE_CUSTOM2
      SYS_DB_DATA_AUTOLOAD
      SYS_DB_TABLES_AUTOCREATE
      SYS_DEFAULT_LOCALE
      SYS_DOCUMENT_SHARE
      SYS_DYNAMIC_APPMENU_DISPLAY_ENABLED
      SYS_HOSTNAME
      SYS_HTTP_HEADER_X_UA_COMPATIBLE
      SYS_MAIL_BODY
      SYS_MAIL_FROM_SYSTEM_ADMIN
      SYS_MAIL_HOST
      SYS_MAIL_PASSWORD
      SYS_MAIL_SMTP_AUTH
      SYS_MAIL_SMTP_PORT
      SYS_MAIL_STARTTLS_ENABLE
      SYS_MAIL_SUBJECT
      SYS_MAIL_TO_SYSTEM_ADMIN
      SYS_MAIL_TRANSPORT_PROTOCOL
      SYS_MAIL_USER
      SYS_MF_APP_VERSION
      SYS_MF_BUILD_NUMBER
      SYS_MF_WEBAPP_VERSION
      SYS_PERSISTENCE_UNIT
      SYS_PERSISTENCE_UNIT_CUSTOM1
      SYS_PERSISTENCE_UNIT_CUSTOM2
      SYS_PRETTY_FACES_ENABLED
      SYS_RUNTIME_MODE
      SYS_SERVER_RUNTIME
      SYS_SUPPORTED_LOCALES
      SYS_USERS_DEFAULT_PWD
      SYS_USER_CONTEXT_DEFAULT_PUBLIC_CONTEXT
      SYS_USER_CONTEXT_REQUIRED
      propKey
    }
  }
  

  namespace io.radien.api {
    interface io.radien.api.SystemProperties {
        {abstract} + propKey()
    }
  }
  

  namespace io.radien.api {
    enum SystemVariables {
      ACTION_ID
      ACTION_NAME
      CREATE_USER
      FIRST_NAME
      ID
      LAST_NAME
      LAST_UPDATE_USER
      LOGON
      NAME
      PAGE_CURRENT
      PAGE_RESULTS
      PAGE_TOTALS
      PAGE_TOTAL_RESULTS
      PERMISSION_ID
      RESOURCE_ID
      RESOURCE_NAME
      ROLE_ID
      ROLE_NAME
      ROLE_TENANT_ID
      SUB
      TENANT_ID
      TENANT_NAME
      TENANT_ROLE_ID
      USER_DELEGATION
      USER_EMAIL
      USER_ENABLED
      USER_ID
      fieldName
      label
    }
  }
  

  io.radien.api.KeycloakConfigs .up.|> io.radien.api.SystemProperties
  io.radien.api.OAFProperties .up.|> io.radien.api.SystemProperties


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
