AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  # See https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-function.html
  # for more info to see how to tune the lambda function configs based on your use case.
  AppFunction:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: java8.al2
      Handler: io.radien.lambda.notificationmanagement.App::handleRequest
      Timeout: 60
      MemorySize: 512
      CodeUri: ./target/rd-lambda-notificationmanagement.jar
      # Attach policies here to give the function permission to access other AWS resources if needed
      # See: https://github.com/awslabs/serverless-application-model/blob/master/docs/policy_templates.rst
      # eg:
      #Policies:
      # - S3ReadPolicy:
      #     BucketName: test-bucket
      Environment:
        Variables:
          #Keycloak
          KEYCLOAK_IDP_URL: https://host.docker.internal:8343
          KEYCLOAK_TOKEN_PATH: /auth/realms/radien/protocol/openid-connect/token
          KEYCLOAK_CLIENT_ID: radien
          KEYCLOAK_SECRET: 86c27042-b3a2-48ea-a936-025103144844
          RADIEN_ENV: LOCAL
          SCRIPT_USERNAME_VALUE: scorpion
          SCRIPT_PASSWORD_VALUE: brutality
          #endpoints
          system.ms.endpoint.ecm: http://host.docker.internal:8081/cms/v1
          # Email
          system.mail.host: host.docker.internal
          system.mail.user: admin@dev-mailhog.com
          system.mail.password: password
          system.mail.smtp.auth: false
          system.mail.smtp.port: 1025
          system.mail.smtp.starttls.enable: false
          system.mail.transport.protocol: smtp
          system.mail.from.system.admin: admin@dev-mailhog.com
          system.mail.to.system.admin: openappframe@re-think.consulting
          MAIL_LOG_ENABLED: true