@startuml

title __PROVIDERS's Class Diagram__\n

  namespace  {
    namespace o.radien.ms.tenantmanagement.client {
      namespace providers {
        class io.radien.ms.tenantmanagement.client.providers.ActiveTenantMessageBodyReader {
            + isReadable()
            + readFrom()
        }
      }
    }
  }
  

  namespace  {
    namespace o.radien.ms.tenantmanagement.client {
      namespace providers {
        class io.radien.ms.tenantmanagement.client.providers.ActiveTenantMessageBodyWriter {
            + getSize()
            + isWriteable()
            + writeTo()
        }
      }
    }
  }
  

  namespace  {
    namespace o.radien.ms.tenantmanagement.client {
      namespace providers {
        class io.radien.ms.tenantmanagement.client.providers.ContractMessageBodyReader {
            + isReadable()
            + readFrom()
        }
      }
    }
  }
  

  namespace  {
    namespace o.radien.ms.tenantmanagement.client {
      namespace providers {
        class io.radien.ms.tenantmanagement.client.providers.ContractMessageBodyWriter {
            + getSize()
            + isWriteable()
            + writeTo()
        }
      }
    }
  }
  

  namespace  {
    namespace o.radien.ms.tenantmanagement.client {
      namespace providers {
        class io.radien.ms.tenantmanagement.client.providers.TenantMessageBodyReader {
            {static} # log : Logger
            + isReadable()
            + readFrom()
        }
      }
    }
  }
  

  namespace  {
    namespace o.radien.ms.tenantmanagement.client {
      namespace providers {
        class io.radien.ms.tenantmanagement.client.providers.TenantMessageBodyWriter {
            + getSize()
            + isWriteable()
            + writeTo()
        }
      }
    }
  }
  

  io.radien.ms.tenantmanagement.client.providers.ActiveTenantMessageBodyReader .up.|> javax.ws.rs.ext.MessageBodyReader
  io.radien.ms.tenantmanagement.client.providers.ActiveTenantMessageBodyWriter .up.|> javax.ws.rs.ext.MessageBodyWriter
  io.radien.ms.tenantmanagement.client.providers.ContractMessageBodyReader .up.|> javax.ws.rs.ext.MessageBodyReader
  io.radien.ms.tenantmanagement.client.providers.ContractMessageBodyWriter .up.|> javax.ws.rs.ext.MessageBodyWriter
  io.radien.ms.tenantmanagement.client.providers.TenantMessageBodyReader .up.|> javax.ws.rs.ext.MessageBodyReader
  io.radien.ms.tenantmanagement.client.providers.TenantMessageBodyWriter .up.|> javax.ws.rs.ext.MessageBodyWriter







@enduml
