@startuml

title __RESOURCE's Class Diagram__\n

  namespace io.radien.webapp {
    namespace resource {
      class io.radien.webapp.resource.LazyResourcesDataModel {
          {static} - serialVersionUID : long
          + LazyResourcesDataModel()
          + getData()
      }
    }
  }
  

  namespace io.radien.webapp {
    namespace resource {
      class io.radien.webapp.resource.ResourceConverter {
          + getAsObject()
          + getAsString()
      }
    }
  }
  

  namespace io.radien.webapp {
    namespace resource {
      class io.radien.webapp.resource.ResourceDataModel {
          - lazyModel : LazyDataModel<? extends SystemResource>
          + delete()
          + edit()
          + editRecords()
          + getLazyModel()
          + getResource()
          + getSelectedResource()
          + getService()
          + init()
          + onRowSelect()
          + onload()
          + returnToDataTableRecords()
          + save()
          + setLazyModel()
          + setResource()
          + setSelectedResource()
          + setService()
      }
    }
  }
  

  io.radien.webapp.resource.LazyResourcesDataModel -up-|> io.radien.webapp.LazyAbstractDataModel
  io.radien.webapp.resource.LazyResourcesDataModel o-- io.radien.api.service.permission.ResourceRESTServiceAccess : service
  io.radien.webapp.resource.ResourceConverter .up.|> javax.faces.convert.Converter
  io.radien.webapp.resource.ResourceConverter o-- io.radien.api.service.permission.ResourceRESTServiceAccess : resourceRESTServiceAccess
  io.radien.webapp.resource.ResourceDataModel .up.|> java.io.Serializable
  io.radien.webapp.resource.ResourceDataModel -up-|> io.radien.webapp.AbstractManager
  io.radien.webapp.resource.ResourceDataModel o-- io.radien.webapp.activeTenant.ActiveTenantDataModelManager : activeTenantDataModelManager
  io.radien.webapp.resource.ResourceDataModel o-- io.radien.api.model.permission.SystemResource : resource
  io.radien.webapp.resource.ResourceDataModel o-- io.radien.api.model.permission.SystemResource : selectedResource
  io.radien.webapp.resource.ResourceDataModel o-- io.radien.api.service.permission.ResourceRESTServiceAccess : service


 

@enduml
