@startuml

title __ENTITIES's Class Diagram__\n

  namespace  {
    namespace o.radien.ms.tenantmanagement.client {
      namespace entities {
        class io.radien.ms.tenantmanagement.client.entities.ActiveTenant {
            - id : Long
            - isTenantActive : boolean
            - tenantId : Long
            - tenantName : String
            - userId : Long
            + ActiveTenant()
            + ActiveTenant()
            + ActiveTenant()
            + getId()
            + getIsTenantActive()
            + getTenantId()
            + getTenantName()
            + getUserId()
            + setId()
            + setIsTenantActive()
            + setTenantId()
            + setTenantName()
            + setUserId()
        }
      }
    }
  }
  

  namespace  {
    namespace o.radien.ms.tenantmanagement.client {
      namespace entities {
        class io.radien.ms.tenantmanagement.client.entities.ActiveTenantSearchFilter {
            - isTenantActive : boolean
            - tenantId : Long
            - tenantName : String
            - userId : Long
            + ActiveTenantSearchFilter()
            + getIsTenantActive()
            + getTenantId()
            + getTenantName()
            + getUserId()
            + setIsTenantActive()
            + setTenantId()
            + setTenantName()
            + setUserId()
        }
      }
    }
  }
  

  namespace  {
    namespace o.radien.ms.tenantmanagement.client {
      namespace entities {
        class io.radien.ms.tenantmanagement.client.entities.Contract {
            - end : LocalDateTime
            - id : Long
            - name : String
            {static} - serialVersionUID : long
            - start : LocalDateTime
            + Contract()
            + Contract()
            + getEnd()
            + getId()
            + getName()
            + getStart()
            + setEnd()
            + setId()
            + setName()
            + setStart()
        }
      }
    }
  }
  

  namespace  {
    namespace o.radien.ms.tenantmanagement.client {
      namespace entities {
        class io.radien.ms.tenantmanagement.client.entities.GlobalHeaders {
            + update()
        }
      }
    }
  }
  

  namespace  {
    namespace o.radien.ms.tenantmanagement.client {
      namespace entities {
        class io.radien.ms.tenantmanagement.client.entities.Tenant {
            - clientAddress : String
            - clientCity : String
            - clientCountry : String
            - clientEmail : String
            - clientId : Long
            - clientPhoneNumber : Long
            - clientZipCode : String
            - id : Long
            - name : String
            - parentId : Long
            - tenantEnd : LocalDate
            - tenantKey : String
            - tenantStart : LocalDate
            + Tenant()
            + Tenant()
            + Tenant()
            + getClientAddress()
            + getClientCity()
            + getClientCountry()
            + getClientEmail()
            + getClientId()
            + getClientPhoneNumber()
            + getClientZipCode()
            + getId()
            + getName()
            + getParentId()
            + getTenantEnd()
            + getTenantKey()
            + getTenantStart()
            + getTenantType()
            + setClientAddress()
            + setClientCity()
            + setClientCountry()
            + setClientEmail()
            + setClientId()
            + setClientPhoneNumber()
            + setClientZipCode()
            + setId()
            + setName()
            + setParentId()
            + setTenantEnd()
            + setTenantKey()
            + setTenantStart()
            + setTenantType()
            + setTenantType()
            - isClientTenant()
            - isClientTenantWithMultipleFields()
        }
      }
    }
  }
  

  namespace  {
    namespace o.radien.ms.tenantmanagement.client {
      namespace entities {
        class io.radien.ms.tenantmanagement.client.entities.TenantSearchFilter {
            - ids : Collection<Long>
            - name : String
            + TenantSearchFilter()
            + getIds()
            + getName()
            + getTenantType()
            + setIds()
            + setName()
            + setTenantType()
        }
      }
    }
  }
  

  namespace  {
    namespace o.radien.ms.tenantmanagement.client {
      namespace entities {
        enum TenantType {
          CLIENT
          ROOT
          SUB
          description
          id
        }
      }
    }
  }
  

  io.radien.ms.tenantmanagement.client.entities.ActiveTenant .up.|> io.radien.api.model.tenant.SystemActiveTenant
  io.radien.ms.tenantmanagement.client.entities.ActiveTenant -up-|> io.radien.api.model.AbstractModel
  io.radien.ms.tenantmanagement.client.entities.ActiveTenantSearchFilter .up.|> io.radien.api.model.tenant.SystemActiveTenantSearchFilter
  io.radien.ms.tenantmanagement.client.entities.ActiveTenantSearchFilter -up-|> io.radien.api.search.SearchFilterCriteria
  io.radien.ms.tenantmanagement.client.entities.Contract .up.|> io.radien.api.model.tenant.SystemContract
  io.radien.ms.tenantmanagement.client.entities.Contract -up-|> io.radien.api.model.AbstractModel
  io.radien.ms.tenantmanagement.client.entities.GlobalHeaders .up.|> org.eclipse.microprofile.rest.client.ext.ClientHeadersFactory
  io.radien.ms.tenantmanagement.client.entities.GlobalHeaders o-- io.radien.api.security.TokensPlaceHolder : tokensPlaceHolder
  io.radien.ms.tenantmanagement.client.entities.Tenant .up.|> io.radien.api.model.tenant.SystemTenant
  io.radien.ms.tenantmanagement.client.entities.Tenant -up-|> io.radien.api.model.AbstractModel
  io.radien.ms.tenantmanagement.client.entities.Tenant o-- io.radien.ms.tenantmanagement.client.entities.TenantType : tenantType
  io.radien.ms.tenantmanagement.client.entities.TenantSearchFilter .up.|> io.radien.api.model.tenant.SystemTenantSearchFilter
  io.radien.ms.tenantmanagement.client.entities.TenantSearchFilter -up-|> io.radien.api.search.SearchFilterCriteria
  io.radien.ms.tenantmanagement.client.entities.TenantSearchFilter o-- io.radien.api.model.tenant.SystemTenantType : tenantType
  io.radien.ms.tenantmanagement.client.entities.TenantType .up.|> io.radien.api.model.tenant.SystemTenantType


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
