@startuml

title __PROVIDERS's Class Diagram__\n

  namespace io.radien.ms.rolemanagement {
    namespace providers {
      class io.radien.ms.rolemanagement.providers.RoleModelMessageBodyWriter {
          + getSize()
          + isWriteable()
          + writeTo()
      }
    }
  }
  

  namespace io.radien.ms.rolemanagement {
    namespace providers {
      class io.radien.ms.rolemanagement.providers.SystemRoleMessageBodyReader {
          + isReadable()
          + readFrom()
      }
    }
  }
  

  io.radien.ms.rolemanagement.providers.RoleModelMessageBodyWriter .up.|> javax.ws.rs.ext.MessageBodyWriter
  io.radien.ms.rolemanagement.providers.SystemRoleMessageBodyReader .up.|> javax.ws.rs.ext.MessageBodyReader







@enduml
