@startuml

title __EXCEPTIONS's Class Diagram__\n

  namespace io.radien.aws.utils.s3 {
    namespace exceptions {
      class io.radien.aws.utils.s3.exceptions.RemoteResourceNotAvailableException {
          + RemoteResourceNotAvailableException()
          + RemoteResourceNotAvailableException()
      }
    }
  }
  



 

@enduml
