@startuml

title __TENANTROLE's Class Diagram__\n

  namespace io.radien.webapp {
    namespace tenant {
      namespace ole {
        class io.radien.webapp.tenantrole.LazyTenantRoleAssociationDataModel {
            {static} - EMPTY_ROLE : SystemRole
            {static} - EMPTY_TENANT : SystemTenant
            - roleMapRef : Map<Long, SystemRole>
            {static} - serialVersionUID : long
            - tenantMapRef : Map<Long, SystemTenant>
            + LazyTenantRoleAssociationDataModel()
            + getData()
            + getRoleName()
            + getTenantName()
            # getNonMappedIds()
            # updateRoleReferencesForExhibition()
            # updateTenantReferencesForExhibition()
        }
      }
    }
  }
  

  namespace io.radien.webapp {
    namespace tenant {
      namespace ole {
        class io.radien.webapp.tenantrole.LazyTenantRoleUserDataModel {
            {static} - DEFAULT_USER : SystemUser
            {static} - log : Logger
            - roleId : Long
            {static} - serialVersionUID : long
            - tenantId : Long
            - userMapRef : Map<Long, SystemUser>
            + LazyTenantRoleUserDataModel()
            + getData()
            + getRoleId()
            + getRowData()
            + getTenantId()
            + getUser()
            + setRoleId()
            + setTenantId()
            # getNonMappedIds()
            # updateUserReferencesForExhibition()
        }
      }
    }
  }
  

  namespace io.radien.webapp {
    namespace tenant {
      namespace ole {
        class io.radien.webapp.tenantrole.LazyTenantingUserDataModel {
            {static} - serialVersionUID : long
            - tenantId : Long
            + LazyTenantingUserDataModel()
            + getData()
            + getRowData()
            + getTenantId()
            + setTenantId()
        }
      }
    }
  }
  

  namespace io.radien.webapp {
    namespace tenant {
      namespace ole {
        class io.radien.webapp.tenantrole.TenantRoleAssociationDataModel {
            - lazyModel : LazyDataModel<? extends SystemTenantRole>
            + getLazyModel()
            + getRoleRESTServiceAccess()
            + getSelectedAssociation()
            + getService()
            + getTenantRESTServiceAccess()
            + init()
            + onRowSelect()
            + onload()
            + setLazyModel()
            + setRoleRESTServiceAccess()
            + setSelectedAssociation()
            + setService()
            + setTenantRESTServiceAccess()
            # buildLazyModel()
        }
      }
    }
  }
  

  namespace io.radien.webapp {
    namespace tenant {
      namespace ole {
        class io.radien.webapp.tenantrole.TenantRoleAssociationManager {
            - assignedPermissions : List<? extends SystemPermission>
            - tabIndex : Long
            - tenantRoleAssociationCreated : Boolean
            + assignPermission()
            + assignUser()
            + associateTenantRole()
            + associateUser()
            + calculatePermissions()
            + edit()
            + getAssignedPermissions()
            + getInitialRolesAllowedForAssociation()
            + getLazyModel()
            + getPermission()
            + getPreviousSelectedPermissionToUnAssign()
            + getPreviousSelectedUserToUnAssign()
            + getRole()
            + getRoles()
            + getSelectedPermissionToUnAssign()
            + getSelectedUserToUnAssign()
            + getTabIndex()
            + getTenant()
            + getTenantRole()
            + getTenantRoleUtil()
            + getTenants()
            + getTenantsFromCurrentUser()
            + getUser()
            + isExistsTenantRoleCreated()
            + onPermissionSelect()
            + onUserSelect()
            + prepareToCreateTenantRole()
            + prepareUserDataTable()
            + setAssignedPermissions()
            + setPermission()
            + setPreviousSelectedPermissionToUnAssign()
            + setPreviousSelectedUserToUnAssign()
            + setRole()
            + setSelectedPermissionToUnAssign()
            + setSelectedUserToUnAssign()
            + setTabIndex()
            + setTenant()
            + setTenantRole()
            + setTenantRoleUtil()
            + setUser()
            + unAssignPermission()
            + unAssignUser()
            - addRoleByName()
        }
      }
    }
  }
  

  io.radien.webapp.tenantrole.LazyTenantRoleAssociationDataModel -up-|> io.radien.webapp.LazyAbstractDataModel
  io.radien.webapp.tenantrole.LazyTenantRoleAssociationDataModel o-- io.radien.api.service.role.RoleRESTServiceAccess : roleService
  io.radien.webapp.tenantrole.LazyTenantRoleAssociationDataModel o-- io.radien.api.service.tenantrole.TenantRoleRESTServiceAccess : service
  io.radien.webapp.tenantrole.LazyTenantRoleAssociationDataModel o-- io.radien.api.service.tenant.TenantRESTServiceAccess : tenantService
  io.radien.webapp.tenantrole.LazyTenantRoleUserDataModel -up-|> io.radien.webapp.LazyAbstractDataModel
  io.radien.webapp.tenantrole.LazyTenantRoleUserDataModel o-- io.radien.api.service.tenantrole.TenantRoleUserRESTServiceAccess : service
  io.radien.webapp.tenantrole.LazyTenantRoleUserDataModel o-- io.radien.api.service.user.UserRESTServiceAccess : userService
  io.radien.webapp.tenantrole.LazyTenantingUserDataModel -up-|> io.radien.webapp.LazyAbstractDataModel
  io.radien.webapp.tenantrole.LazyTenantingUserDataModel o-- io.radien.api.service.tenantrole.TenantRoleUserRESTServiceAccess : service
  io.radien.webapp.tenantrole.LazyTenantingUserDataModel o-- io.radien.api.service.user.UserRESTServiceAccess : userService
  io.radien.webapp.tenantrole.TenantRoleAssociationDataModel -up-|> io.radien.webapp.AbstractManager
  io.radien.webapp.tenantrole.TenantRoleAssociationDataModel o-- io.radien.webapp.activeTenant.ActiveTenantDataModelManager : activeTenantDataModelManager
  io.radien.webapp.tenantrole.TenantRoleAssociationDataModel o-- io.radien.api.service.role.RoleRESTServiceAccess : roleRESTServiceAccess
  io.radien.webapp.tenantrole.TenantRoleAssociationDataModel o-- io.radien.api.model.tenantrole.SystemTenantRole : selectedAssociation
  io.radien.webapp.tenantrole.TenantRoleAssociationDataModel o-- io.radien.api.service.tenantrole.TenantRoleRESTServiceAccess : service
  io.radien.webapp.tenantrole.TenantRoleAssociationDataModel o-- io.radien.api.service.tenant.TenantRESTServiceAccess : tenantRESTServiceAccess
  io.radien.webapp.tenantrole.TenantRoleAssociationManager -up-|> io.radien.webapp.AbstractManager
  io.radien.webapp.tenantrole.TenantRoleAssociationManager o-- io.radien.webapp.activeTenant.ActiveTenantDataModelManager : activeTenantDataModelManager
  io.radien.webapp.tenantrole.TenantRoleAssociationManager o-- io.radien.webapp.tenantrole.LazyTenantRoleUserDataModel : lazyModel
  io.radien.webapp.tenantrole.TenantRoleAssociationManager o-- io.radien.api.model.permission.SystemPermission : permission
  io.radien.webapp.tenantrole.TenantRoleAssociationManager o-- io.radien.api.model.permission.SystemPermission : previousSelectedPermissionToUnAssign
  io.radien.webapp.tenantrole.TenantRoleAssociationManager o-- io.radien.api.model.tenantrole.SystemTenantRoleUser : previousSelectedUserToUnAssign
  io.radien.webapp.tenantrole.TenantRoleAssociationManager o-- io.radien.api.model.role.SystemRole : role
  io.radien.webapp.tenantrole.TenantRoleAssociationManager o-- io.radien.api.service.role.RoleRESTServiceAccess : roleRESTServiceAccess
  io.radien.webapp.tenantrole.TenantRoleAssociationManager o-- io.radien.api.model.permission.SystemPermission : selectedPermissionToUnAssign
  io.radien.webapp.tenantrole.TenantRoleAssociationManager o-- io.radien.api.model.tenantrole.SystemTenantRoleUser : selectedUserToUnAssign
  io.radien.webapp.tenantrole.TenantRoleAssociationManager o-- io.radien.api.model.tenant.SystemTenant : tenant
  io.radien.webapp.tenantrole.TenantRoleAssociationManager o-- io.radien.api.service.tenant.TenantRESTServiceAccess : tenantRESTServiceAccess
  io.radien.webapp.tenantrole.TenantRoleAssociationManager o-- io.radien.api.model.tenantrole.SystemTenantRole : tenantRole
  io.radien.webapp.tenantrole.TenantRoleAssociationManager o-- io.radien.api.service.tenantrole.TenantRolePermissionRESTServiceAccess : tenantRolePermissionRESTServiceAccess
  io.radien.webapp.tenantrole.TenantRoleAssociationManager o-- io.radien.api.service.tenantrole.TenantRoleRESTServiceAccess : tenantRoleRESTServiceAccess
  io.radien.webapp.tenantrole.TenantRoleAssociationManager o-- io.radien.api.service.tenantrole.TenantRoleUserRESTServiceAccess : tenantRoleUserRESTServiceAccess
  io.radien.webapp.tenantrole.TenantRoleAssociationManager o-- io.radien.webapp.util.TenantRoleUtil : tenantRoleUtil
  io.radien.webapp.tenantrole.TenantRoleAssociationManager o-- io.radien.api.model.user.SystemUser : user
  io.radien.webapp.tenantrole.TenantRoleAssociationManager o-- io.radien.api.service.user.UserRESTServiceAccess : userRESTServiceAccess
  io.radien.webapp.tenantrole.TenantRoleAssociationManager o-- io.radien.webapp.authz.WebAuthorizationChecker : webAuthorizationChecker







@enduml
