@startuml

title __TENANTROLE's Class Diagram__\n

  namespace io.radien.api {
    namespace service {
      namespace tenant {
        namespace ole {
          interface io.radien.api.service.tenantrole.TenantRolePermissionRESTServiceAccess {
              {abstract} + assignPermission()
              {abstract} + getPermissions()
              {abstract} + unAssignPermission()
              {abstract} + unAssignPermission()
          }
        }
      }
    }
  }
  

  namespace io.radien.api {
    namespace service {
      namespace tenant {
        namespace ole {
          interface io.radien.api.service.tenantrole.TenantRolePermissionServiceAccess {
              {abstract} + create()
              {abstract} + delete()
              {abstract} + get()
              {abstract} + get()
              {abstract} + getAll()
              {abstract} + getTenantRolePermissionId()
              {abstract} + isAssociationAlreadyExistent()
          }
        }
      }
    }
  }
  

  namespace io.radien.api {
    namespace service {
      namespace tenant {
        namespace ole {
          interface io.radien.api.service.tenantrole.TenantRoleRESTServiceAccess {
              {abstract} + exists()
              {abstract} + getAll()
              {abstract} + getIdByTenantRole()
              {abstract} + getPermissions()
              {abstract} + getRolesForUserTenant()
              {abstract} + getTenantRoleById()
              {abstract} + getTenantRoles()
              {abstract} + getTenants()
              {abstract} + save()
          }
        }
      }
    }
  }
  

  namespace io.radien.api {
    namespace service {
      namespace tenant {
        namespace ole {
          interface io.radien.api.service.tenantrole.TenantRoleServiceAccess {
              {abstract} + delete()
              {abstract} + get()
              {abstract} + get()
              {abstract} + getAll()
              {abstract} + getPermissions()
              {abstract} + getRoleIdsForUserTenant()
              {abstract} + getTenantRoleId()
              {abstract} + getTenantRoleIds()
              {abstract} + getTenants()
              {abstract} + hasAnyRole()
              {abstract} + hasPermission()
              {abstract} + isAssociationAlreadyExistent()
              {abstract} + save()
          }
        }
      }
    }
  }
  

  namespace io.radien.api {
    namespace service {
      namespace tenant {
        namespace ole {
          interface io.radien.api.service.tenantrole.TenantRoleUserRESTServiceAccess {
              {abstract} + assignUser()
              {abstract} + delete()
              {abstract} + getUsers()
              {abstract} + getUsersIds()
              {abstract} + unAssignUser()
          }
        }
      }
    }
  }
  

  namespace io.radien.api {
    namespace service {
      namespace tenant {
        namespace ole {
          interface io.radien.api.service.tenantrole.TenantRoleUserServiceAccess {
              {abstract} + create()
              {abstract} + delete()
              {abstract} + delete()
              {abstract} + get()
              {abstract} + get()
              {abstract} + getAll()
              {abstract} + getAllUserIds()
              {abstract} + getTenantRoleUserId()
              {abstract} + getTenantRoleUserIds()
              {abstract} + getTenantRoleUserIds()
              {abstract} + isAssociatedWithTenant()
              {abstract} + isAssociationAlreadyExistent()
          }
        }
      }
    }
  }
  



 

@enduml
