@startuml

title __ENTITIES's Class Diagram__\n

  namespace io.radien.ms.openid.entities {
    class io.radien.ms.openid.entities.GlobalHeaders {
        + update()
    }
  }
  

  namespace io.radien.ms.openid.entities {
    class io.radien.ms.openid.entities.Principal {
        - createDate : Date
        - createUser : Long
        - delegatedCreation : boolean
        - enabled : boolean
        - firstname : String
        - id : Long
        - lastUpdate : Date
        - lastUpdateUser : Long
        - lastname : String
        - logon : String
        - sub : String
        - terminationDate : Date
        - userEmail : String
        + Principal()
        + Principal()
        + getCreateDate()
        + getCreateUser()
        + getFirstname()
        + getId()
        + getLastUpdate()
        + getLastUpdateUser()
        + getLastname()
        + getLogon()
        + getSub()
        + getTerminationDate()
        + getUserEmail()
        + isDelegatedCreation()
        + isEnabled()
        + setCreateDate()
        + setCreateUser()
        + setDelegatedCreation()
        + setEnabled()
        + setFirstname()
        + setId()
        + setLastUpdate()
        + setLastUpdateUser()
        + setLastname()
        + setLogon()
        + setSub()
        + setTerminationDate()
        + setUserEmail()
    }
  }
  

  io.radien.ms.openid.entities.GlobalHeaders .up.|> org.eclipse.microprofile.rest.client.ext.ClientHeadersFactory
  io.radien.ms.openid.entities.GlobalHeaders o-- io.radien.api.security.TokensPlaceHolder : tokensPlaceHolder
  io.radien.ms.openid.entities.Principal .up.|> io.radien.api.model.user.SystemUser


 

@enduml
