@startuml

title __CONFIG's Class Diagram__\n

  namespace io.radien.ms.tenantmanagement {
    namespace config {
      class io.radien.ms.tenantmanagement.config.TenantConfiguration {
          - config : Config
          - log : Logger
          - supportedLocales : Map<String, Locale>
          + TenantConfiguration()
          + findLocale()
          + fireEvent()
          + getDefaultLocale()
          + getProperty()
          + getResourceBundle()
          + getSupportedLocales()
          + getSystemAdminUserId()
          + getVersion()
          - loadSupportedLocales()
      }
    }
  }
  

  io.radien.ms.tenantmanagement.config.TenantConfiguration .up.|> io.radien.api.OAFAccess







@enduml
