@startuml

title __TENANT's Class Diagram__\n

  namespace io.radien.webapp {
    namespace tenant {
      class io.radien.webapp.tenant.LazyTenantDataModel {
          {static} - serialVersionUID : long
          + LazyTenantDataModel()
          + getData()
      }
    }
  }
  

  namespace io.radien.webapp {
    namespace tenant {
      class io.radien.webapp.tenant.TenantConverter {
          + getAsObject()
          + getAsString()
      }
    }
  }
  

  namespace io.radien.webapp {
    namespace tenant {
      class io.radien.webapp.tenant.TenantDataModel {
          # tenantEndDate : Date
          # tenantStartDate : Date
          - lazyModel : LazyDataModel<? extends SystemTenant>
          + deleteTenantHierarchy()
          + edit()
          + editRecords()
          + getLazyModel()
          + getParents()
          + getSelectedTenant()
          + getService()
          + getTenant()
          + getTenantEndDate()
          + getTenantStartDate()
          + getTenantTypes()
          + init()
          + onRowSelect()
          + onload()
          + returnToDataTableRecords()
          + save()
          + setLazyModel()
          + setSelectedTenant()
          + setService()
          + setTenant()
          + setTenantEndDate()
          + setTenantStartDate()
          # convertAndSetDates()
          - clientAddressValidation()
          - clientCityValidation()
          - clientCountryValidation()
          - clientEmailValidation()
          - clientPhoneNumberValidation()
          - clientZipCodeValidation()
          - fillParentClientId()
          - requestUpperTenant()
          - retrieveClientTenantId()
          - retrieveParentTenantId()
          - sendErrorMessage()
          - validateMandatoryFields()
      }
    }
  }
  

  io.radien.webapp.tenant.LazyTenantDataModel -up-|> io.radien.webapp.LazyAbstractDataModel
  io.radien.webapp.tenant.LazyTenantDataModel o-- io.radien.api.service.tenant.TenantRESTServiceAccess : service
  io.radien.webapp.tenant.TenantConverter .up.|> javax.faces.convert.Converter
  io.radien.webapp.tenant.TenantConverter o-- io.radien.api.service.tenant.TenantRESTServiceAccess : tenantRESTServiceAccess
  io.radien.webapp.tenant.TenantDataModel .up.|> java.io.Serializable
  io.radien.webapp.tenant.TenantDataModel -up-|> io.radien.webapp.AbstractManager
  io.radien.webapp.tenant.TenantDataModel o-- io.radien.webapp.activeTenant.ActiveTenantDataModelManager : activeTenantDataModelManager
  io.radien.webapp.tenant.TenantDataModel o-- io.radien.api.service.tenant.ActiveTenantRESTServiceAccess : activeTenantRESTServiceAccess
  io.radien.webapp.tenant.TenantDataModel o-- io.radien.api.model.tenant.SystemTenant : selectedTenant
  io.radien.webapp.tenant.TenantDataModel o-- io.radien.api.service.tenant.TenantRESTServiceAccess : service
  io.radien.webapp.tenant.TenantDataModel o-- io.radien.api.model.tenant.SystemTenant : tenant
  io.radien.webapp.tenant.TenantDataModel o-- io.radien.webapp.security.UserSession : userSession







@enduml
