@startuml

title __RD-MS-ROLEMANAGEMENT-CLIENT's Class Diagram__\n

  namespace io.radien.ms.rolemanagement.client.entities {
    class io.radien.ms.rolemanagement.client.entities.GlobalHeaders {
    }
  }
  

  namespace io.radien.ms.rolemanagement.client.entities {
    class io.radien.ms.rolemanagement.client.entities.Role {
    }
  }
  

  namespace io.radien.ms.rolemanagement.client.entities {
    class io.radien.ms.rolemanagement.client.entities.RoleSearchFilter {
    }
  }
  

  namespace io.radien.ms.rolemanagement.client.entities {
    class io.radien.ms.rolemanagement.client.entities.TenantRole {
    }
  }
  

  namespace io.radien.ms.rolemanagement.client.entities {
    class io.radien.ms.rolemanagement.client.entities.TenantRolePermission {
    }
  }
  

  namespace io.radien.ms.rolemanagement.client.entities {
    class io.radien.ms.rolemanagement.client.entities.TenantRolePermissionSearchFilter {
    }
  }
  

  namespace io.radien.ms.rolemanagement.client.entities {
    class io.radien.ms.rolemanagement.client.entities.TenantRoleSearchFilter {
    }
  }
  

  namespace io.radien.ms.rolemanagement.client.entities {
    class io.radien.ms.rolemanagement.client.entities.TenantRoleUser {
    }
  }
  

  namespace io.radien.ms.rolemanagement.client.entities {
    class io.radien.ms.rolemanagement.client.entities.TenantRoleUserSearchFilter {
    }
  }
  

  namespace io.radien.ms.rolemanagement.client.exception {
    class io.radien.ms.rolemanagement.client.exception.BadRequestException {
    }
  }
  

  namespace io.radien.ms.rolemanagement.client.exception {
    class io.radien.ms.rolemanagement.client.exception.InternalServerErrorException {
    }
  }
  

  namespace io.radien.ms.rolemanagement.client.exception {
    class io.radien.ms.rolemanagement.client.exception.RoleResponseExceptionMapper {
    }
  }
  

  namespace io.radien.ms.rolemanagement.client.providers {
    class io.radien.ms.rolemanagement.client.providers.RoleMessageBodyReader {
    }
  }
  

  namespace io.radien.ms.rolemanagement.client.providers {
    class io.radien.ms.rolemanagement.client.providers.RoleMessageBodyWriter {
    }
  }
  

  namespace io.radien.ms.rolemanagement.client.providers {
    class io.radien.ms.rolemanagement.client.providers.TenantRoleMessageBodyReader {
    }
  }
  

  namespace io.radien.ms.rolemanagement.client.providers {
    class io.radien.ms.rolemanagement.client.providers.TenantRoleMessageBodyWriter {
    }
  }
  

  namespace io.radien.ms.rolemanagement.client.providers {
    class io.radien.ms.rolemanagement.client.providers.TenantRolePermissionMessageBodyReader {
    }
  }
  

  namespace io.radien.ms.rolemanagement.client.providers {
    class io.radien.ms.rolemanagement.client.providers.TenantRolePermissionMessageBodyWriter {
    }
  }
  

  namespace io.radien.ms.rolemanagement.client.providers {
    class io.radien.ms.rolemanagement.client.providers.TenantRoleUserMessageBodyReader {
    }
  }
  

  namespace io.radien.ms.rolemanagement.client.providers {
    class io.radien.ms.rolemanagement.client.providers.TenantRoleUserMessageBodyWriter {
    }
  }
  

  namespace io.radien.ms.rolemanagement.client.services {
    class io.radien.ms.rolemanagement.client.services.RoleFactory {
    }
  }
  

  namespace io.radien.ms.rolemanagement.client.services {
    class io.radien.ms.rolemanagement.client.services.RoleRESTServiceClient {
    }
  }
  

  namespace io.radien.ms.rolemanagement.client.services {
    interface io.radien.ms.rolemanagement.client.services.RoleResourceClient {
    }
  }
  

  namespace io.radien.ms.rolemanagement.client.services {
    class io.radien.ms.rolemanagement.client.services.TenantRoleFactory {
    }
  }
  

  namespace io.radien.ms.rolemanagement.client.services {
    class io.radien.ms.rolemanagement.client.services.TenantRolePermissionFactory {
    }
  }
  

  namespace io.radien.ms.rolemanagement.client.services {
    class io.radien.ms.rolemanagement.client.services.TenantRolePermissionRESTServiceClient {
    }
  }
  

  namespace io.radien.ms.rolemanagement.client.services {
    interface io.radien.ms.rolemanagement.client.services.TenantRolePermissionResourceClient {
    }
  }
  

  namespace io.radien.ms.rolemanagement.client.services {
    class io.radien.ms.rolemanagement.client.services.TenantRoleRESTServiceClient {
    }
  }
  

  namespace io.radien.ms.rolemanagement.client.services {
    interface io.radien.ms.rolemanagement.client.services.TenantRoleResourceClient {
    }
  }
  

  namespace io.radien.ms.rolemanagement.client.services {
    class io.radien.ms.rolemanagement.client.services.TenantRoleUserFactory {
    }
  }
  

  namespace io.radien.ms.rolemanagement.client.services {
    class io.radien.ms.rolemanagement.client.services.TenantRoleUserRESTServiceClient {
    }
  }
  

  namespace io.radien.ms.rolemanagement.client.services {
    interface io.radien.ms.rolemanagement.client.services.TenantRoleUserResourceClient {
    }
  }
  

  namespace io.radien.ms.rolemanagement.client.util {
    class io.radien.ms.rolemanagement.client.util.ClientServiceUtil {
    }
  }
  

  namespace io.radien.ms.rolemanagement.client.util {
    class io.radien.ms.rolemanagement.client.util.ListRoleModelMapper {
    }
  }
  

  namespace io.radien.ms.rolemanagement.client.util {
    class io.radien.ms.rolemanagement.client.util.RoleModelMapper {
    }
  }
  

  namespace io.radien.ms.rolemanagement.client.util {
    class io.radien.ms.rolemanagement.client.util.TenantRoleModelMapper {
    }
  }
  

  namespace io.radien.ms.rolemanagement.client.util {
    class io.radien.ms.rolemanagement.client.util.TenantRolePermissionModelMapper {
    }
  }
  

  namespace io.radien.ms.rolemanagement.client.util {
    class io.radien.ms.rolemanagement.client.util.TenantRoleUserModelMapper {
    }
  }
  

  io.radien.ms.rolemanagement.client.entities.GlobalHeaders .up.|> org.eclipse.microprofile.rest.client.ext.ClientHeadersFactory
  io.radien.ms.rolemanagement.client.entities.GlobalHeaders o-- io.radien.api.security.TokensPlaceHolder : tokensPlaceHolder
  io.radien.ms.rolemanagement.client.entities.Role .up.|> io.radien.api.model.role.SystemRole
  io.radien.ms.rolemanagement.client.entities.Role -up-|> io.radien.api.model.role.AbstractRoleModel
  io.radien.ms.rolemanagement.client.entities.RoleSearchFilter .up.|> io.radien.api.model.role.SystemRoleSearchFilter
  io.radien.ms.rolemanagement.client.entities.RoleSearchFilter -up-|> io.radien.api.search.SearchableByIds
  io.radien.ms.rolemanagement.client.entities.TenantRole .up.|> io.radien.api.model.tenantrole.SystemTenantRole
  io.radien.ms.rolemanagement.client.entities.TenantRole -up-|> io.radien.api.model.AbstractModel
  io.radien.ms.rolemanagement.client.entities.TenantRolePermission .up.|> io.radien.api.model.tenantrole.SystemTenantRolePermission
  io.radien.ms.rolemanagement.client.entities.TenantRolePermission -up-|> io.radien.api.model.AbstractModel
  io.radien.ms.rolemanagement.client.entities.TenantRolePermissionSearchFilter .up.|> io.radien.api.model.tenantrole.SystemTenantRolePermissionSearchFilter
  io.radien.ms.rolemanagement.client.entities.TenantRolePermissionSearchFilter -up-|> io.radien.api.search.SearchFilterCriteria
  io.radien.ms.rolemanagement.client.entities.TenantRoleSearchFilter .up.|> io.radien.api.model.tenantrole.SystemTenantRoleSearchFilter
  io.radien.ms.rolemanagement.client.entities.TenantRoleSearchFilter -up-|> io.radien.api.search.SearchFilterCriteria
  io.radien.ms.rolemanagement.client.entities.TenantRoleUser .up.|> io.radien.api.model.tenantrole.SystemTenantRoleUser
  io.radien.ms.rolemanagement.client.entities.TenantRoleUser -up-|> io.radien.api.model.AbstractModel
  io.radien.ms.rolemanagement.client.entities.TenantRoleUserSearchFilter .up.|> io.radien.api.model.tenantrole.SystemTenantRoleUserSearchFilter
  io.radien.ms.rolemanagement.client.entities.TenantRoleUserSearchFilter -up-|> io.radien.api.search.SearchFilterCriteria
  io.radien.ms.rolemanagement.client.exception.RoleResponseExceptionMapper -up-|> io.radien.exception.ModelResponseExceptionMapper
  io.radien.ms.rolemanagement.client.providers.RoleMessageBodyReader .up.|> javax.ws.rs.ext.MessageBodyReader
  io.radien.ms.rolemanagement.client.providers.RoleMessageBodyWriter .up.|> javax.ws.rs.ext.MessageBodyWriter
  io.radien.ms.rolemanagement.client.providers.TenantRoleMessageBodyReader .up.|> javax.ws.rs.ext.MessageBodyReader
  io.radien.ms.rolemanagement.client.providers.TenantRoleMessageBodyWriter .up.|> javax.ws.rs.ext.MessageBodyWriter
  io.radien.ms.rolemanagement.client.providers.TenantRolePermissionMessageBodyReader .up.|> javax.ws.rs.ext.MessageBodyReader
  io.radien.ms.rolemanagement.client.providers.TenantRolePermissionMessageBodyWriter .up.|> javax.ws.rs.ext.MessageBodyWriter
  io.radien.ms.rolemanagement.client.providers.TenantRoleUserMessageBodyReader .up.|> javax.ws.rs.ext.MessageBodyReader
  io.radien.ms.rolemanagement.client.providers.TenantRoleUserMessageBodyWriter .up.|> javax.ws.rs.ext.MessageBodyWriter
  io.radien.ms.rolemanagement.client.services.RoleRESTServiceClient .up.|> io.radien.api.service.role.RoleRESTServiceAccess
  io.radien.ms.rolemanagement.client.services.RoleRESTServiceClient -up-|> io.radien.ms.authz.security.AuthorizationChecker
  io.radien.ms.rolemanagement.client.services.RoleRESTServiceClient o-- io.radien.ms.rolemanagement.client.util.ClientServiceUtil : clientServiceUtil
  io.radien.ms.rolemanagement.client.services.RoleRESTServiceClient o-- io.radien.api.OAFAccess : oaf
  io.radien.ms.rolemanagement.client.services.TenantRolePermissionRESTServiceClient .up.|> io.radien.api.service.tenantrole.TenantRolePermissionRESTServiceAccess
  io.radien.ms.rolemanagement.client.services.TenantRolePermissionRESTServiceClient -up-|> io.radien.ms.authz.security.AuthorizationChecker
  io.radien.ms.rolemanagement.client.services.TenantRolePermissionRESTServiceClient o-- io.radien.ms.rolemanagement.client.util.ClientServiceUtil : clientServiceUtil
  io.radien.ms.rolemanagement.client.services.TenantRolePermissionRESTServiceClient o-- io.radien.api.OAFAccess : oaf
  io.radien.ms.rolemanagement.client.services.TenantRoleRESTServiceClient .up.|> io.radien.api.service.tenantrole.TenantRoleRESTServiceAccess
  io.radien.ms.rolemanagement.client.services.TenantRoleRESTServiceClient -up-|> io.radien.ms.authz.security.AuthorizationChecker
  io.radien.ms.rolemanagement.client.services.TenantRoleRESTServiceClient o-- io.radien.ms.rolemanagement.client.util.ClientServiceUtil : clientServiceUtil
  io.radien.ms.rolemanagement.client.services.TenantRoleRESTServiceClient o-- io.radien.api.OAFAccess : oaf
  io.radien.ms.rolemanagement.client.services.TenantRoleUserRESTServiceClient .up.|> io.radien.api.service.tenantrole.TenantRoleUserRESTServiceAccess
  io.radien.ms.rolemanagement.client.services.TenantRoleUserRESTServiceClient -up-|> io.radien.ms.authz.security.AuthorizationChecker
  io.radien.ms.rolemanagement.client.services.TenantRoleUserRESTServiceClient o-- io.radien.ms.rolemanagement.client.util.ClientServiceUtil : clientServiceUtil
  io.radien.ms.rolemanagement.client.services.TenantRoleUserRESTServiceClient o-- io.radien.api.OAFAccess : oaf


 

@enduml
