@startuml

title __CLIENT's Class Diagram__\n

  namespace io.radien.ms.authz.client {
    interface io.radien.ms.authz.client.TenantRoleClient {
        {abstract} + checkPermissions()
        {abstract} + isPermissionExistentForUser()
        {abstract} + isRoleExistentForUser()
    }
  }
  

  namespace io.radien.ms.authz.client {
    interface io.radien.ms.authz.client.UserClient {
        {abstract} + getUserIdBySub()
        {abstract} + refreshToken()
    }
  }
  



 

@enduml
