@startuml

title __ROLE's Class Diagram__\n

  namespace io.radien.api {
    namespace service {
      namespace role {
        interface io.radien.api.service.role.RoleRESTServiceAccess {
            {abstract} + create()
            {abstract} + delete()
            {abstract} + getAll()
            {abstract} + getRoleById()
            {abstract} + getRoleByName()
            {abstract} + getRolesByDescription()
            {abstract} + getRolesByIds()
            {abstract} + getTotalRecordsCount()
        }
      }
    }
  }
  

  namespace io.radien.api {
    namespace service {
      namespace role {
        interface io.radien.api.service.role.RoleServiceAccess {
            {abstract} + checkIfRolesExist()
            {abstract} + delete()
            {abstract} + get()
            {abstract} + getAll()
            {abstract} + getSpecificRoles()
            {abstract} + getTotalRecordsCount()
            {abstract} + save()
        }
      }
    }
  }
  

  namespace io.radien.api {
    namespace service {
      namespace role {
        enum SystemRolesEnum {
          APPROVER
          AUTHOR
          CLIENT_TENANT_ADMINISTRATOR
          GUEST
          PERMISSION_ADMINISTRATOR
          PUBLISHER
          ROLE_ADMINISTRATOR
          SUB_TENANT_ADMINISTRATOR
          SYSTEM_ADMINISTRATOR
          TENANT_ADMINISTRATOR
          USER_ADMINISTRATOR
          roleName
        }
      }
    }
  }
  








@enduml
