@startuml

title __RD-MS-PERMISSIONMANAGEMENT's Class Diagram__\n

  namespace io.radien.ms.permissionmanagement {
    class io.radien.ms.permissionmanagement.RadienApplication {
    }
  }
  

  namespace io.radien.ms.permissionmanagement {
    namespace model {
      class io.radien.ms.permissionmanagement.model.ActionEntity {
      }
    }
  }
  

  namespace io.radien.ms.permissionmanagement {
    namespace model {
      class io.radien.ms.permissionmanagement.model.PermissionEntity {
      }
    }
  }
  

  namespace io.radien.ms.permissionmanagement {
    namespace model {
      class io.radien.ms.permissionmanagement.model.ResourceEntity {
      }
    }
  }
  

  namespace io.radien.ms.permissionmanagement {
    namespace service {
      class io.radien.ms.permissionmanagement.service.ActionResource {
      }
    }
  }
  

  namespace io.radien.ms.permissionmanagement {
    namespace service {
      class io.radien.ms.permissionmanagement.service.ActionService {
      }
    }
  }
  

  namespace io.radien.ms.permissionmanagement {
    namespace service {
      class io.radien.ms.permissionmanagement.service.EntityManagerHolder {
      }
    }
  }
  

  namespace io.radien.ms.permissionmanagement {
    namespace service {
      class io.radien.ms.permissionmanagement.service.PermissionBusinessService {
      }
    }
  }
  

  namespace io.radien.ms.permissionmanagement {
    namespace service {
      class io.radien.ms.permissionmanagement.service.PermissionResource {
      }
    }
  }
  

  namespace io.radien.ms.permissionmanagement {
    namespace service {
      class io.radien.ms.permissionmanagement.service.PermissionService {
      }
    }
  }
  

  namespace io.radien.ms.permissionmanagement {
    namespace service {
      class io.radien.ms.permissionmanagement.service.ResourceResource {
      }
    }
  }
  

  namespace io.radien.ms.permissionmanagement {
    namespace service {
      class io.radien.ms.permissionmanagement.service.ResourceService {
      }
    }
  }
  

  io.radien.ms.permissionmanagement.RadienApplication -up-|> javax.ws.rs.core.Application
  io.radien.ms.permissionmanagement.model.ActionEntity -up-|> io.radien.ms.permissionmanagement.client.entities.Action
  io.radien.ms.permissionmanagement.model.PermissionEntity -up-|> io.radien.ms.permissionmanagement.client.entities.Permission
  io.radien.ms.permissionmanagement.model.ResourceEntity -up-|> io.radien.ms.permissionmanagement.client.entities.Resource
  io.radien.ms.permissionmanagement.service.ActionResource .up.|> io.radien.ms.permissionmanagement.client.services.ActionResourceClient
  io.radien.ms.permissionmanagement.service.ActionResource o-- io.radien.api.service.permission.ActionServiceAccess : actionServiceAccess
  io.radien.ms.permissionmanagement.service.ActionService .up.|> io.radien.api.service.permission.ActionServiceAccess
  io.radien.ms.permissionmanagement.service.ActionService o-- io.radien.ms.permissionmanagement.service.EntityManagerHolder : holder
  io.radien.ms.permissionmanagement.service.PermissionBusinessService o-- io.radien.api.service.permission.PermissionServiceAccess : permissionServiceAccess
  io.radien.ms.permissionmanagement.service.PermissionResource .up.|> io.radien.ms.permissionmanagement.client.services.PermissionResourceClient
  io.radien.ms.permissionmanagement.service.PermissionResource o-- io.radien.ms.permissionmanagement.service.PermissionBusinessService : businessService
  io.radien.ms.permissionmanagement.service.PermissionResource o-- io.radien.api.service.permission.PermissionServiceAccess : permissionServiceAccess
  io.radien.ms.permissionmanagement.service.PermissionService .up.|> io.radien.api.service.permission.PermissionServiceAccess
  io.radien.ms.permissionmanagement.service.PermissionService o-- io.radien.ms.permissionmanagement.service.EntityManagerHolder : holder
  io.radien.ms.permissionmanagement.service.ResourceResource .up.|> io.radien.ms.permissionmanagement.client.services.ResourceResourceClient
  io.radien.ms.permissionmanagement.service.ResourceResource o-- io.radien.api.service.permission.ResourceServiceAccess : resourceServiceAccess
  io.radien.ms.permissionmanagement.service.ResourceService .up.|> io.radien.api.service.permission.ResourceServiceAccess
  io.radien.ms.permissionmanagement.service.ResourceService o-- io.radien.ms.permissionmanagement.service.EntityManagerHolder : holder


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
