@startuml

title __UTIL's Class Diagram__\n

  namespace io.radien.api {
    namespace service {
      namespace ecm {
        namespace util {
          class io.radien.api.service.ecm.util.EnterpriseContentDeserializer {
              + deserialize()
          }
        }
      }
    }
  }
  

  io.radien.api.service.ecm.util.EnterpriseContentDeserializer -up-|> com.fasterxml.jackson.databind.JsonDeserializer


 

@enduml
