@startuml

title __PROVIDERS's Class Diagram__\n

  namespace io.radien.ms.usermanagement.client {
    namespace providers {
      class io.radien.ms.usermanagement.client.providers.PageMessageBodyReader {
          + isReadable()
          + readFrom()
      }
    }
  }
  

  namespace io.radien.ms.usermanagement.client {
    namespace providers {
      class io.radien.ms.usermanagement.client.providers.UserMessageBodyReader {
          + isReadable()
          + readFrom()
      }
    }
  }
  

  namespace io.radien.ms.usermanagement.client {
    namespace providers {
      class io.radien.ms.usermanagement.client.providers.UserMessageBodyWriter {
          + getSize()
          + isWriteable()
          + writeTo()
      }
    }
  }
  

  io.radien.ms.usermanagement.client.providers.PageMessageBodyReader .up.|> javax.ws.rs.ext.MessageBodyReader
  io.radien.ms.usermanagement.client.providers.UserMessageBodyReader .up.|> javax.ws.rs.ext.MessageBodyReader
  io.radien.ms.usermanagement.client.providers.UserMessageBodyWriter .up.|> javax.ws.rs.ext.MessageBodyWriter







@enduml
