@startuml

title __INTERCEPTOR's Class Diagram__\n

  namespace io.radien.kernel {
    namespace interceptor {
      class io.radien.kernel.interceptor.MethodRuntimeInterceptor {
          {static} - counter : long
          {static} - log : Logger
          + around()
      }
    }
  }
  

  namespace io.radien.kernel {
    namespace interceptor {
      interface io.radien.kernel.interceptor.RuntimeIntercepted {
      }
    }
  }
  








@enduml
