@startuml

title __OIDC's Class Diagram__\n

  namespace io.radien.security.oidc {
    class io.radien.security.oidc.CorsFilter {
        {static} - log : Logger
        + destroy()
        + doFilter()
        + init()
    }
  }
  

  io.radien.security.oidc.CorsFilter .up.|> javax.servlet.Filter


 

@enduml
