@startuml

title __SERVICES's Class Diagram__\n

  namespace  {
    namespace o.radien.ms.tenantmanagement.client {
      namespace services {
        class io.radien.ms.tenantmanagement.client.services.ActiveTenantFactory {
            {static} + convert()
            {static} + convert()
            {static} + convertJsonToPage()
            {static} + convertToJsonObject()
            {static} + create()
        }
      }
    }
  }
  

  namespace  {
    namespace o.radien.ms.tenantmanagement.client {
      namespace services {
        class io.radien.ms.tenantmanagement.client.services.ActiveTenantRESTServiceClient {
            {static} - log : Logger
            {static} - serialVersionUID : long
            + create()
            + delete()
            + deleteByTenantAndUser()
            + getActiveTenantByFilter()
            + getActiveTenantById()
            + getActiveTenantByUserAndTenant()
            + getAll()
            + isActiveTenantExistent()
            + update()
            - createActiveTenant()
            - deleteByTenantAndUserRequester()
            - deleteRequester()
            - getActiveTenantByFilterRequester()
            - getActiveTenantByUserAndTenantRequester()
            - getActiveTenantPage()
            - getSystemActiveTenant()
            - isActiveTenantExistentRequester()
            - updateActiveTenant()
        }
      }
    }
  }
  

  namespace  {
    namespace o.radien.ms.tenantmanagement.client {
      namespace services {
        interface io.radien.ms.tenantmanagement.client.services.ActiveTenantResourceClient {
            {abstract} + create()
            {abstract} + delete()
            {abstract} + delete()
            {abstract} + exists()
            {abstract} + get()
            {abstract} + getAll()
            {abstract} + getById()
            {abstract} + getByUserAndTenant()
            {abstract} + update()
        }
      }
    }
  }
  

  namespace  {
    namespace o.radien.ms.tenantmanagement.client {
      namespace services {
        class io.radien.ms.tenantmanagement.client.services.ContractFactory {
            {static} - DATE_FORMAT : String
            {static} + convert()
            {static} + convert()
            {static} + convertJsonToPage()
            {static} + convertToJsonObject()
            {static} + create()
        }
      }
    }
  }
  

  namespace  {
    namespace o.radien.ms.tenantmanagement.client {
      namespace services {
        class io.radien.ms.tenantmanagement.client.services.ContractRESTServiceClient {
            {static} - UNABLE_TO_RECOVER_TOKEN : String
            {static} - serialVersionUID : long
            + create()
            + delete()
            + getAll()
            + getContractByName()
            + getTotalRecordsCount()
            + isContractExistent()
            + update()
            - createRequester()
            - deleteRequest()
            - getAlRequester()
            - getContractByNameRequest()
            - getTotalRecordsCountRequester()
            - isContractExistentRequester()
            - updateRequester()
        }
      }
    }
  }
  

  namespace  {
    namespace o.radien.ms.tenantmanagement.client {
      namespace services {
        interface io.radien.ms.tenantmanagement.client.services.ContractResourceClient {
            {abstract} + create()
            {abstract} + delete()
            {abstract} + exists()
            {abstract} + get()
            {abstract} + getAll()
            {abstract} + getById()
            {abstract} + getTotalRecordsCount()
            {abstract} + update()
        }
      }
    }
  }
  

  namespace  {
    namespace o.radien.ms.tenantmanagement.client {
      namespace services {
        class io.radien.ms.tenantmanagement.client.services.TenantFactory {
            {static} - DATE_FORMAT : String
            {static} - log : Logger
            {static} + convert()
            {static} + convert()
            {static} + convertJsonToPage()
            {static} + convertToJsonObject()
            {static} + create()
            {static} - getTypeFromJson()
        }
      }
    }
  }
  

  namespace  {
    namespace o.radien.ms.tenantmanagement.client {
      namespace services {
        class io.radien.ms.tenantmanagement.client.services.TenantRESTServiceClient {
            {static} - log : Logger
            {static} - serialVersionUID : long
            + create()
            + delete()
            + deleteTenantHierarchy()
            + getAll()
            + getTenantById()
            + getTenantByName()
            + getTenantsByIds()
            + isTenantExistent()
            + update()
            - createTenant()
            - delTenantHierarchy()
            - deleteRequester()
            - getSystemTenant()
            - getSystemTenants()
            - getTenantPage()
            - getTenantsByName()
            - isTenantExistentRequester()
            - updateTenant()
        }
      }
    }
  }
  

  namespace  {
    namespace o.radien.ms.tenantmanagement.client {
      namespace services {
        interface io.radien.ms.tenantmanagement.client.services.TenantResourceClient {
            {abstract} + create()
            {abstract} + delete()
            {abstract} + deleteTenantHierarchy()
            {abstract} + exists()
            {abstract} + get()
            {abstract} + getAll()
            {abstract} + getById()
            {abstract} + update()
        }
      }
    }
  }
  

  io.radien.ms.tenantmanagement.client.services.ActiveTenantRESTServiceClient .up.|> io.radien.api.service.tenant.ActiveTenantRESTServiceAccess
  io.radien.ms.tenantmanagement.client.services.ActiveTenantRESTServiceClient -up-|> io.radien.ms.authz.security.AuthorizationChecker
  io.radien.ms.tenantmanagement.client.services.ActiveTenantRESTServiceClient o-- io.radien.ms.tenantmanagement.client.util.ClientServiceUtil : clientServiceUtil
  io.radien.ms.tenantmanagement.client.services.ActiveTenantRESTServiceClient o-- io.radien.api.OAFAccess : oafAccess
  io.radien.ms.tenantmanagement.client.services.ContractRESTServiceClient .up.|> io.radien.api.service.tenant.ContractRESTServiceAccess
  io.radien.ms.tenantmanagement.client.services.ContractRESTServiceClient -up-|> io.radien.ms.authz.security.AuthorizationChecker
  io.radien.ms.tenantmanagement.client.services.ContractRESTServiceClient o-- io.radien.ms.tenantmanagement.client.util.ClientServiceUtil : clientServiceUtil
  io.radien.ms.tenantmanagement.client.services.ContractRESTServiceClient o-- io.radien.api.OAFAccess : oafAccess
  io.radien.ms.tenantmanagement.client.services.TenantRESTServiceClient .up.|> io.radien.api.service.tenant.TenantRESTServiceAccess
  io.radien.ms.tenantmanagement.client.services.TenantRESTServiceClient -up-|> io.radien.ms.authz.security.AuthorizationChecker
  io.radien.ms.tenantmanagement.client.services.TenantRESTServiceClient o-- io.radien.ms.tenantmanagement.client.util.ClientServiceUtil : clientServiceUtil
  io.radien.ms.tenantmanagement.client.services.TenantRESTServiceClient o-- io.radien.api.OAFAccess : oafAccess


 

@enduml
