@startuml

title __SERVICES's Class Diagram__\n

  namespace io.radien.ms.usermanagement.client {
    namespace services {
      class io.radien.ms.usermanagement.client.services.UserFactory {
          {static} + convert()
          {static} + convert()
          {static} + convertJsonToPage()
          {static} + convertToJsonObject()
          {static} + create()
      }
    }
  }
  

  namespace io.radien.ms.usermanagement.client {
    namespace services {
      class io.radien.ms.usermanagement.client.services.UserRESTServiceClient {
          {static} - log : Logger
          {static} - serialVersionUID : long
          + create()
          + create()
          + deleteUser()
          + getAll()
          + getOAF()
          + getUserById()
          + getUserByLogon()
          + getUserBySub()
          + getUsersByIds()
          + sendUpdatePasswordEmail()
          + updateUser()
          - createBatch()
          - createUser()
          - delUser()
          - getPageUsers()
          - getSystemUser()
          - getSystemUser()
          - getSystemUserByLogon()
          - getSystemUsers()
          - logErrorEnabledResponse()
          - updatePasswordEmail()
          - updateUser()
      }
    }
  }
  

  namespace io.radien.ms.usermanagement.client {
    namespace services {
      interface io.radien.ms.usermanagement.client.services.UserResourceClient {
          {abstract} + create()
          {abstract} + delete()
          {abstract} + getAll()
          {abstract} + getById()
          {abstract} + getUserIdBySub()
          {abstract} + getUsers()
          {abstract} + refreshToken()
          {abstract} + save()
          {abstract} + sendUpdatePasswordEmail()
      }
    }
  }
  

  io.radien.ms.usermanagement.client.services.UserFactory -up-|> io.radien.ms.usermanagement.client.util.UserFactoryUtil
  io.radien.ms.usermanagement.client.services.UserRESTServiceClient .up.|> io.radien.api.service.user.UserRESTServiceAccess
  io.radien.ms.usermanagement.client.services.UserRESTServiceClient -up-|> io.radien.ms.authz.security.AuthorizationChecker
  io.radien.ms.usermanagement.client.services.UserRESTServiceClient o-- io.radien.ms.usermanagement.client.util.ClientServiceUtil : clientServiceUtil
  io.radien.ms.usermanagement.client.services.UserRESTServiceClient o-- io.radien.api.OAFAccess : oaf
  io.radien.ms.usermanagement.client.services.UserRESTServiceClient o-- io.radien.api.security.TokensPlaceHolder : tokensPlaceHolder


 

@enduml
