@startuml

title __RD-MS-USERMANAGEMENT's Class Diagram__\n

  namespace io.radien.ms.usermanagement {
    class io.radien.ms.usermanagement.UserManagementApplication {
    }
  }
  

  namespace io.radien.ms.usermanagement {
    namespace batch {
      class io.radien.ms.usermanagement.batch.BatchResponse {
      }
    }
  }
  

  namespace io.radien.ms.usermanagement {
    namespace config {
      enum KeycloakEmailActions {
      }
    }
  }
  

  namespace io.radien.ms.usermanagement {
    namespace entities {
      class io.radien.ms.usermanagement.entities.UserEntity {
      }
    }
  }
  

  namespace io.radien.ms.usermanagement {
    namespace legacy {
      class io.radien.ms.usermanagement.legacy.UserFactory {
      }
    }
  }
  

  namespace io.radien.ms.usermanagement {
    namespace mdb {
      class io.radien.ms.usermanagement.mdb.SpiderMDB {
      }
    }
  }
  

  namespace io.radien.ms.usermanagement {
    namespace providers {
      class io.radien.ms.usermanagement.providers.SystemUserMessageBodyReader {
      }
    }
  }
  

  namespace io.radien.ms.usermanagement {
    namespace providers {
      class io.radien.ms.usermanagement.providers.UserModelListMessageBodyWriter {
      }
    }
  }
  

  namespace io.radien.ms.usermanagement {
    namespace providers {
      class io.radien.ms.usermanagement.providers.UserModelMessageBodyWriter {
      }
    }
  }
  

  namespace io.radien.ms.usermanagement {
    namespace service {
      class io.radien.ms.usermanagement.service.KeycloakClient {
      }
    }
  }
  

  namespace io.radien.ms.usermanagement {
    namespace service {
      class io.radien.ms.usermanagement.service.KeycloakFactory {
      }
    }
  }
  

  namespace io.radien.ms.usermanagement {
    namespace service {
      class io.radien.ms.usermanagement.service.KeycloakService {
      }
    }
  }
  

  namespace io.radien.ms.usermanagement {
    namespace service {
      class io.radien.ms.usermanagement.service.UserBusinessService {
      }
    }
  }
  

  namespace io.radien.ms.usermanagement {
    namespace service {
      class io.radien.ms.usermanagement.service.UserResource {
      }
    }
  }
  

  namespace io.radien.ms.usermanagement {
    namespace service {
      class io.radien.ms.usermanagement.service.UserService {
      }
    }
  }
  

  namespace io.radien.ms.usermanagement {
    namespace util {
      class io.radien.ms.usermanagement.util.UserModelMapper {
      }
    }
  }
  

  io.radien.ms.usermanagement.UserManagementApplication -up-|> javax.ws.rs.core.Application
  io.radien.ms.usermanagement.entities.UserEntity -up-|> io.radien.ms.usermanagement.client.entities.User
  io.radien.ms.usermanagement.legacy.UserFactory -up-|> io.radien.ms.usermanagement.client.util.UserFactoryUtil
  io.radien.ms.usermanagement.mdb.SpiderMDB .up.|> javax.jms.MessageListener
  io.radien.ms.usermanagement.providers.SystemUserMessageBodyReader .up.|> javax.ws.rs.ext.MessageBodyReader
  io.radien.ms.usermanagement.providers.UserModelListMessageBodyWriter .up.|> javax.ws.rs.ext.MessageBodyWriter
  io.radien.ms.usermanagement.providers.UserModelMessageBodyWriter .up.|> javax.ws.rs.ext.MessageBodyWriter
  io.radien.ms.usermanagement.service.UserBusinessService .up.|> java.io.Serializable
  io.radien.ms.usermanagement.service.UserBusinessService o-- io.radien.ms.usermanagement.service.KeycloakService : keycloakService
  io.radien.ms.usermanagement.service.UserBusinessService o-- io.radien.api.service.user.UserServiceAccess : userServiceAccess
  io.radien.ms.usermanagement.service.UserResource .up.|> io.radien.ms.usermanagement.client.services.UserResourceClient
  io.radien.ms.usermanagement.service.UserResource -up-|> io.radien.ms.authz.security.AuthorizationChecker
  io.radien.ms.usermanagement.service.UserResource o-- io.radien.ms.usermanagement.service.UserBusinessService : userBusinessService
  io.radien.ms.usermanagement.service.UserService .up.|> io.radien.api.service.user.UserServiceAccess
  io.radien.ms.usermanagement.service.UserService -up-|> io.radien.api.util.ModelServiceUtil







@enduml
