@startuml

title __ENTITIES's Class Diagram__\n

  namespace io.radien.ms.rolemanagement {
    namespace entities {
      class io.radien.ms.rolemanagement.entities.RoleEntity {
          {static} - serialVersionUID : long
          + RoleEntity()
          + RoleEntity()
          + getDescription()
          + getId()
          + getName()
          + getTerminationDate()
      }
    }
  }
  

  namespace io.radien.ms.rolemanagement {
    namespace entities {
      class io.radien.ms.rolemanagement.entities.TenantRoleEntity {
          + TenantRoleEntity()
          + TenantRoleEntity()
          + getId()
          + getRoleId()
          + getTenantId()
      }
    }
  }
  

  namespace io.radien.ms.rolemanagement {
    namespace entities {
      class io.radien.ms.rolemanagement.entities.TenantRolePermissionEntity {
          + TenantRolePermissionEntity()
          + TenantRolePermissionEntity()
          + getId()
          + getPermissionId()
          + getTenantRoleId()
      }
    }
  }
  

  namespace io.radien.ms.rolemanagement {
    namespace entities {
      class io.radien.ms.rolemanagement.entities.TenantRoleUserEntity {
          + TenantRoleUserEntity()
          + TenantRoleUserEntity()
          + getId()
          + getTenantRoleId()
          + getUserId()
      }
    }
  }
  

  io.radien.ms.rolemanagement.entities.RoleEntity -up-|> io.radien.ms.rolemanagement.client.entities.Role
  io.radien.ms.rolemanagement.entities.TenantRoleEntity -up-|> io.radien.ms.rolemanagement.client.entities.TenantRole
  io.radien.ms.rolemanagement.entities.TenantRolePermissionEntity -up-|> io.radien.ms.rolemanagement.client.entities.TenantRolePermission
  io.radien.ms.rolemanagement.entities.TenantRoleUserEntity -up-|> io.radien.ms.rolemanagement.client.entities.TenantRoleUser


 

@enduml
