@startuml

title __ENTITIES's Class Diagram__\n

  namespace io.radien.ms.usermanagement {
    namespace entities {
      class io.radien.ms.usermanagement.entities.UserEntity {
          {static} - serialVersionUID : long
          + UserEntity()
          + UserEntity()
          + getFirstname()
          + getId()
          + getLastname()
          + getLogon()
          + getSub()
          + getTerminationDate()
          + getUserEmail()
          + isEnabled()
      }
    }
  }
  

  io.radien.ms.usermanagement.entities.UserEntity -up-|> io.radien.ms.usermanagement.client.entities.User







@enduml
