@startuml

title __JPA's Class Diagram__\n

  namespace io.radien.persistence.jpa {
    enum EntityManagerFactories {
      APPFRAME
      INTEGRATION_1
      INTEGRATION_2
    }
  }
  

  namespace io.radien.persistence.jpa {
    interface io.radien.persistence.jpa.EntityManagerQualifier {
        {abstract} + factory()
    }
  }
  

  namespace io.radien.persistence.jpa {
    class io.radien.persistence.jpa.EntityManagerUtil {
        {static} - log : Logger
        {static} + attach()
        {static} + delete()
        {static} + delete()
        {static} + isDetached()
        {static} + save()
        {static} + saveOrUpdate()
        {static} + saveOrUpdate()
        {static} + saveOrUpdateAndReturn()
    }
  }
  



 

@enduml
