export enum LOCAL {
  CURRENT_USER = 'PH__u_data',
  ROLE_USER = 'PH__role',
  EMAIL = 'PH__re',
  JWTOKEN = 'PH__t',
  LOCALE = 'PH__lang_locale',
  REMEMBER_ME = 'PH__remember',
  TOKEN = 'PH__st',
  TRANSLATE_FILE = 'PH__tf',
  COOKIE_DECISION = 'PH__cd',
  ACCIDENT_TYPE = 'PH__at',
  BODY_PART = 'PH__bp',
  OCCUPATION_POSTCODE = 'PH__occ_plz',
  OCCUPATION = 'PH__occ',
  CLAIMS_LIST = 'PH_cl',
  ADDITIONAL_INSURANCE_FORM = 'PH__add_info',
  ADDITIONAL_INSURANCE_FORM_SECOND = 'PH__add_info_second',
  PRIVATE_ACCIDENT_FORM = 'PH__data_private_acc',
  ILLNESS_DIAGNOSTIC_FORM = 'PH__data_illness_diag',
  WORK_ACCIDENT_FORM = 'PH_work_acc',
  ACCIDENT_DATE_FORM = 'PH__acc_date',
  PERSONAL_DATA_PERSON = 'PH__data_person',
  PERSONAL_DATA_CONTACT = 'PH__data_contact'
}
