@startuml

title __TENANT's Class Diagram__\n

  namespace io.radien.webapp {
    namespace user {
      namespace tenant {
        class io.radien.webapp.user.tenant.UnAssignTenantUser {
            {static} - serialVersionUID : long
            - userSelectedAndHasUserAdminRoleAccess : boolean
            + isUserSelectedAndHasUserAdminRoleAccess()
            + setTenantUserFieldsAsNull()
            + setUserSelectedAndHasUserAdminRoleAccess()
            + unAssignSelectedTenantUser()
        }
      }
    }
  }
  

  io.radien.webapp.user.tenant.UnAssignTenantUser -up-|> io.radien.webapp.AbstractManager
  io.radien.webapp.user.tenant.UnAssignTenantUser o-- io.radien.webapp.activeTenant.ActiveTenantDataModelManager : activeTenantDataModelManager
  io.radien.webapp.user.tenant.UnAssignTenantUser o-- io.radien.api.service.tenantrole.TenantRoleUserRESTServiceAccess : tenantRoleUserRESTServiceAccess
  io.radien.webapp.user.tenant.UnAssignTenantUser o-- io.radien.webapp.user.UserDataModel : userDataModel


 

@enduml
