@startuml

title __RD-OPENID's Class Diagram__\n

  namespace io.radien.security.oidc {
    class io.radien.security.oidc.CorsFilter {
    }
  }
  

  namespace io.radien.security.openid.config {
    class io.radien.security.openid.config.AjaxAwareAuthenticationEntryPoint {
    }
  }
  

  namespace io.radien.security.openid.config {
    class io.radien.security.openid.config.AppInitializer {
    }
  }
  

  namespace io.radien.security.openid.config {
    class io.radien.security.openid.config.AuthenticationManagerSwitchOff {
    }
  }
  

  namespace io.radien.security.openid.config {
    class io.radien.security.openid.config.SecurityConfig {
    }
  }
  

  namespace io.radien.security.openid.config {
    class io.radien.security.openid.config.SecurityInitializer {
    }
  }
  

  namespace io.radien.security.openid.config {
    class io.radien.security.openid.config.SpringConfig {
    }
  }
  

  namespace io.radien.security.openid.config {
    class io.radien.security.openid.config.WebConfig {
    }
  }
  

  namespace io.radien.security.openid.controller {
    class io.radien.security.openid.controller.PrivateController {
    }
  }
  

  namespace io.radien.security.openid.controller {
    class io.radien.security.openid.controller.PublicController {
    }
  }
  

  namespace io.radien.security.openid.controller {
    class io.radien.security.openid.controller.TokenController {
    }
  }
  

  namespace io.radien.security.openid.filter {
    class io.radien.security.openid.filter.OpenIdConnectFilter {
    }
  }
  

  namespace io.radien.security.openid.listener {
    class io.radien.security.openid.listener.CustomRequestContextListener {
    }
  }
  

  namespace io.radien.security.openid.model {
    class io.radien.security.openid.model.OpenIdConnectUserDetails {
    }
  }
  

  namespace io.radien.security.openid.service {
    interface io.radien.security.openid.service.AuthenticationService {
    }
  }
  

  namespace io.radien.security.openid.service {
    class io.radien.security.openid.service.PrivateService {
    }
  }
  

  namespace io.radien.security.openid.service {
    class io.radien.security.openid.service.PublicService {
    }
  }
  

  io.radien.security.oidc.CorsFilter .up.|> javax.servlet.Filter
  io.radien.security.openid.config.AjaxAwareAuthenticationEntryPoint -up-|> org.springframework.security.web.authentication.LoginUrlAuthenticationEntryPoint
  io.radien.security.openid.config.AppInitializer -up-|> org.springframework.web.servlet.support.AbstractAnnotationConfigDispatcherServletInitializer
  io.radien.security.openid.config.AuthenticationManagerSwitchOff .up.|> org.springframework.security.authentication.AuthenticationManager
  io.radien.security.openid.config.SecurityConfig -up-|> org.springframework.security.config.annotation.web.configuration.WebSecurityConfigurerAdapter
  io.radien.security.openid.config.SecurityInitializer -up-|> org.springframework.security.web.context.AbstractSecurityWebApplicationInitializer
  io.radien.security.openid.config.WebConfig .up.|> org.springframework.web.servlet.config.annotation.WebMvcConfigurer
  io.radien.security.openid.controller.PrivateController o-- io.radien.security.openid.service.PrivateService : privateService
  io.radien.security.openid.controller.PublicController o-- io.radien.security.openid.service.PublicService : publicService
  io.radien.security.openid.filter.OpenIdConnectFilter -up-|> org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter
  io.radien.security.openid.listener.CustomRequestContextListener -up-|> org.springframework.web.context.request.RequestContextListener
  io.radien.security.openid.model.OpenIdConnectUserDetails .up.|> org.springframework.security.core.userdetails.UserDetails


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
