@startuml

title __UTIL's Class Diagram__\n

  namespace io.radien.util {
    abstract class io.radien.util.AbstractOAFHTTPServlet {
        {static} # log : Logger
        {static} - serialVersionUID : long
        # doGet()
        # doPost()
        # getBytes()
        {abstract} # process()
        # service()
        - processRequestAndResponse()
    }
  }
  

  namespace io.radien.util {
    class io.radien.util.HttpConnectionUtil {
        {static} - BUFFER_SIZE : int
        {static} - log : Logger
        - response : HttpResponse
        + getAllHeaders()
        + getHTTPResponseContent()
        + getResponseCode()
        + post()
    }
  }
  

  namespace io.radien.util {
    class io.radien.util.HttpConnectionUtil.HeaderObj {
        - name : String
        - value : String
        + toString()
        ~ HeaderObj()
    }
  }
  

  namespace io.radien.util {
    class io.radien.util.OAFHttpRequest {
        - customHeaders : Map<String, String>
        + getHeader()
        + getHeaderNames()
        + putHeader()
        ~ OAFHttpRequest()
    }
  }
  

  namespace io.radien.util {
    class io.radien.util.OAFHttpResponse {
        - customHeaders : Map<String, String>
        + getHeader()
        + getHeaderNames()
        ~ OAFHttpResponse()
        ~ putHeader()
    }
  }
  

  namespace io.radien.util {
    class io.radien.util.StringFormatUtil {
        {static} - EMPTY_PLACEHOLDER : Pattern
        {static} - VALID_PLACEHOLDER : Pattern
        {static} - log : Logger
        {static} + format()
        {static} - emptyPLaceHolderValidator()
        {static} - validPlaceHolderValidator()
        {static} - validate()
    }
  }
  

  namespace io.radien.util {
    class io.radien.util.ZoneComparator {
        + compare()
    }
  }
  

  io.radien.util.AbstractOAFHTTPServlet .up.|> io.radien.api.Appframeable
  io.radien.util.AbstractOAFHTTPServlet -up-|> javax.servlet.http.HttpServlet
  io.radien.util.HttpConnectionUtil +-down- io.radien.util.HttpConnectionUtil.HeaderObj
  io.radien.util.OAFHttpRequest -up-|> javax.servlet.http.HttpServletRequestWrapper
  io.radien.util.OAFHttpResponse -up-|> javax.servlet.http.HttpServletResponseWrapper
  io.radien.util.ZoneComparator .up.|> java.util.Comparator


 

@enduml
