@startuml

title __CLIENT's Class Diagram__\n

  namespace  {
    namespace o.radien.ms.tenantmanagement.client {
      class io.radien.ms.tenantmanagement.client.TenantResponseExceptionMapper {
          + tenantHandles()
          + tenantToThrowable()
      }
    }
  }
  

  io.radien.ms.tenantmanagement.client.TenantResponseExceptionMapper -up-|> io.radien.exception.ModelResponseExceptionMapper







@enduml
