@startuml

title __PROVIDERS's Class Diagram__\n

  namespace io.radien.ms.rolemanagement.client.providers {
    class io.radien.ms.rolemanagement.client.providers.RoleMessageBodyReader {
        + isReadable()
        + readFrom()
    }
  }
  

  namespace io.radien.ms.rolemanagement.client.providers {
    class io.radien.ms.rolemanagement.client.providers.RoleMessageBodyWriter {
        + getSize()
        + isWriteable()
        + writeTo()
    }
  }
  

  namespace io.radien.ms.rolemanagement.client.providers {
    class io.radien.ms.rolemanagement.client.providers.TenantRoleMessageBodyReader {
        + isReadable()
        + readFrom()
    }
  }
  

  namespace io.radien.ms.rolemanagement.client.providers {
    class io.radien.ms.rolemanagement.client.providers.TenantRoleMessageBodyWriter {
        + getSize()
        + isWriteable()
        + writeTo()
    }
  }
  

  namespace io.radien.ms.rolemanagement.client.providers {
    class io.radien.ms.rolemanagement.client.providers.TenantRolePermissionMessageBodyReader {
        + isReadable()
        + readFrom()
    }
  }
  

  namespace io.radien.ms.rolemanagement.client.providers {
    class io.radien.ms.rolemanagement.client.providers.TenantRolePermissionMessageBodyWriter {
        + getSize()
        + isWriteable()
        + writeTo()
    }
  }
  

  namespace io.radien.ms.rolemanagement.client.providers {
    class io.radien.ms.rolemanagement.client.providers.TenantRoleUserMessageBodyReader {
        + isReadable()
        + readFrom()
    }
  }
  

  namespace io.radien.ms.rolemanagement.client.providers {
    class io.radien.ms.rolemanagement.client.providers.TenantRoleUserMessageBodyWriter {
        + getSize()
        + isWriteable()
        + writeTo()
    }
  }
  

  io.radien.ms.rolemanagement.client.providers.RoleMessageBodyReader .up.|> javax.ws.rs.ext.MessageBodyReader
  io.radien.ms.rolemanagement.client.providers.RoleMessageBodyWriter .up.|> javax.ws.rs.ext.MessageBodyWriter
  io.radien.ms.rolemanagement.client.providers.TenantRoleMessageBodyReader .up.|> javax.ws.rs.ext.MessageBodyReader
  io.radien.ms.rolemanagement.client.providers.TenantRoleMessageBodyWriter .up.|> javax.ws.rs.ext.MessageBodyWriter
  io.radien.ms.rolemanagement.client.providers.TenantRolePermissionMessageBodyReader .up.|> javax.ws.rs.ext.MessageBodyReader
  io.radien.ms.rolemanagement.client.providers.TenantRolePermissionMessageBodyWriter .up.|> javax.ws.rs.ext.MessageBodyWriter
  io.radien.ms.rolemanagement.client.providers.TenantRoleUserMessageBodyReader .up.|> javax.ws.rs.ext.MessageBodyReader
  io.radien.ms.rolemanagement.client.providers.TenantRoleUserMessageBodyWriter .up.|> javax.ws.rs.ext.MessageBodyWriter


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
