@startuml

title __SERVICES's Class Diagram__\n

  namespace io.radien.ms.permissionmanagement.client {
    namespace services {
      class io.radien.ms.permissionmanagement.client.services.ActionFactory {
          {static} + convert()
          {static} + convert()
          {static} + convertJsonToPage()
          {static} + convertToJsonObject()
          {static} + create()
      }
    }
  }
  

  namespace io.radien.ms.permissionmanagement.client {
    namespace services {
      class io.radien.ms.permissionmanagement.client.services.ActionRESTServiceClient {
          {static} - log : Logger
          {static} - serialVersionUID : long
          + create()
          + delete()
          + getActionById()
          + getActionByName()
          + getActionsByIds()
          + getAll()
          + getOAF()
          # map()
          - createRequest()
          - deleteRequest()
          - getActionByIdRequest()
          - getActionByNameRequest()
          - getActionsByIdsRequester()
          - getAllRequest()
      }
    }
  }
  

  namespace io.radien.ms.permissionmanagement.client {
    namespace services {
      interface io.radien.ms.permissionmanagement.client.services.ActionResourceClient {
          {abstract} + delete()
          {abstract} + getActions()
          {abstract} + getAll()
          {abstract} + getById()
          {abstract} + save()
      }
    }
  }
  

  namespace io.radien.ms.permissionmanagement.client {
    namespace services {
      class io.radien.ms.permissionmanagement.client.services.PermissionFactory {
          {static} + convert()
          {static} + convert()
          {static} + convertJsonToPage()
          {static} + convertToJsonObject()
          {static} + create()
      }
    }
  }
  

  namespace io.radien.ms.permissionmanagement.client {
    namespace services {
      class io.radien.ms.permissionmanagement.client.services.PermissionRESTServiceClient {
          {static} - serialVersionUID : long
          + create()
          + delete()
          + getAll()
          + getIdByResourceAndAction()
          + getOAF()
          + getPermissionByActionAndResource()
          + getPermissionById()
          + getPermissionByName()
          + getPermissions()
          + getPermissionsByIds()
          + getTotalRecordsCount()
          + isPermissionExistent()
          - createRequester()
          - deleteRequester()
          - getAllRequester()
          - getIdByResourceAndActionRequester()
          - getPermissionByActionAndResourceRequester()
          - getPermissionByIdRequester()
          - getPermissionByNameRequester()
          - getPermissionRequester()
          - getPermissionsByIdsRequester()
          - getTotalRecordsCountRequester()
          - isPermissionExistentRequester()
      }
    }
  }
  

  namespace io.radien.ms.permissionmanagement.client {
    namespace services {
      interface io.radien.ms.permissionmanagement.client.services.PermissionResourceClient {
          {abstract} + associate()
          {abstract} + delete()
          {abstract} + dissociate()
          {abstract} + exists()
          {abstract} + getAll()
          {abstract} + getById()
          {abstract} + getIdByResourceAndAction()
          {abstract} + getPermissions()
          {abstract} + getTotalRecordsCount()
          {abstract} + hasPermission()
          {abstract} + save()
      }
    }
  }
  

  namespace io.radien.ms.permissionmanagement.client {
    namespace services {
      class io.radien.ms.permissionmanagement.client.services.ResourceFactory {
          {static} + convert()
          {static} + convert()
          {static} + convertJsonToPage()
          {static} + convertToJsonObject()
          {static} + create()
      }
    }
  }
  

  namespace io.radien.ms.permissionmanagement.client {
    namespace services {
      class io.radien.ms.permissionmanagement.client.services.ResourceRESTServiceClient {
          {static} - log : Logger
          {static} - serialVersionUID : long
          + create()
          + delete()
          + getAll()
          + getOAF()
          + getResourceById()
          + getResourceByName()
          + getResourcesByIds()
          # map()
          - createRequester()
          - deleteRequester()
          - getAllRequester()
          - getResourceByIdRequester()
          - getResourceByNameRequester()
          - getResourcesByIdsRequester()
      }
    }
  }
  

  namespace io.radien.ms.permissionmanagement.client {
    namespace services {
      interface io.radien.ms.permissionmanagement.client.services.ResourceResourceClient {
          {abstract} + delete()
          {abstract} + getAll()
          {abstract} + getById()
          {abstract} + getResources()
          {abstract} + save()
      }
    }
  }
  

  io.radien.ms.permissionmanagement.client.services.ActionRESTServiceClient .up.|> io.radien.api.service.permission.ActionRESTServiceAccess
  io.radien.ms.permissionmanagement.client.services.ActionRESTServiceClient -up-|> io.radien.ms.authz.security.AuthorizationChecker
  io.radien.ms.permissionmanagement.client.services.ActionRESTServiceClient o-- io.radien.ms.permissionmanagement.client.util.ClientServiceUtil : clientServiceUtil
  io.radien.ms.permissionmanagement.client.services.ActionRESTServiceClient o-- io.radien.api.OAFAccess : oaf
  io.radien.ms.permissionmanagement.client.services.PermissionRESTServiceClient .up.|> io.radien.api.service.permission.PermissionRESTServiceAccess
  io.radien.ms.permissionmanagement.client.services.PermissionRESTServiceClient -up-|> io.radien.ms.authz.security.AuthorizationChecker
  io.radien.ms.permissionmanagement.client.services.PermissionRESTServiceClient o-- io.radien.ms.permissionmanagement.client.util.ClientServiceUtil : clientServiceUtil
  io.radien.ms.permissionmanagement.client.services.PermissionRESTServiceClient o-- io.radien.api.OAFAccess : oaf
  io.radien.ms.permissionmanagement.client.services.ResourceRESTServiceClient .up.|> io.radien.api.service.permission.ResourceRESTServiceAccess
  io.radien.ms.permissionmanagement.client.services.ResourceRESTServiceClient -up-|> io.radien.ms.authz.security.AuthorizationChecker
  io.radien.ms.permissionmanagement.client.services.ResourceRESTServiceClient o-- io.radien.ms.permissionmanagement.client.util.ClientServiceUtil : clientServiceUtil
  io.radien.ms.permissionmanagement.client.services.ResourceRESTServiceClient o-- io.radien.api.OAFAccess : oaf







@enduml
