@startuml

title __WEBAPP's Class Diagram__\n

  namespace io.radien.webapp {
    abstract class io.radien.webapp.AbstractManager {
        # log : Logger
        + getLog()
        # extractErrorMessage()
        # handleError()
        # handleMessage()
        # redirectToHomePage()
        # redirectToPage()
    }
  }
  

  namespace io.radien.webapp {
    enum DataModelEnum {
      ACTIONS_MESSAGE
      ACTION_CREATION_PAGE
      ACTION_DETAIL_PAGE
      ACTION_MAIN_PAGE
      ACTION_MESSAGE
      ACTION_NAME_IS_MANDATORY
      ACTION_NOT_FOUND_MESSAGE
      ACTION_SELECTED
      ACTIVE_TENANT_CHANGED_TO_NULL_VALUE
      ACTIVE_TENANT_CHANGED_VALUE
      ACTIVE_TENANT_HAS_BEEN_REMOVED
      CHOOSE_ACTIVE_TENANT_MESSAGE
      DELETE_ERROR
      DELETE_SUCCESS
      EDIT_ERROR_MESSAGE
      EDIT_SUCCESS
      EDIT_SUCCESS_MESSAGE
      ERROR_REDIRECTING
      ERROR_SELECT_RECORD_TO_DELETE
      GENERIC_ERROR_MESSAGE
      NO_ACTIVE_TENANT_MESSAGE
      ON_ROW_ROLE_EXPAND_ERROR
      PERMISSIONS_MESSAGE
      PERMISSION_DETAIL_PAGE
      PERMISSION_MAIN_PAGE
      PERMISSION_MESSAGE
      PERMISSION_NOT_FOUND_FOR_ACTION_RESOURCE_MESSAGE
      PERMISSION_NOT_FOUND_MESSAGE
      PRETTY_INDEX
      PRETTY_PROFILE
      PRETTY_USER
      PUBLIC_INDEX_PATH
      RESOURCE_CREATION_PAGE
      RESOURCE_DATA_TABLE_PAGE
      RESOURCE_DETAIL_PAGE
      RESOURCE_NAME_IS_MANDATORY
      RESOURCE_NOT_FOUND_MESSAGE
      RESOURCE_RD_TENANT
      RESOURCE_SELECTED
      RETRIEVE_ERROR_MESSAGE
      ROLES_MESSAGE
      ROLE_CREATION_PAGE
      ROLE_DETAIL_PAGE
      ROLE_MAIN_PAGE
      ROLE_MESSAGE
      ROLE_NAME_MANDATORY
      ROLE_NOT_FOUND_MESSAGE
      ROLE_SELECTED
      ROOT_TENANT
      ROW_SELECTED
      SAVE_ERROR_MESSAGE
      SAVE_SUCCESS_MESSAGE
      SELECT_RECORD_FIRST
      SENT_UPDATE_PASSWORD_EMAIL_ERROR
      SENT_UPDATE_PASSWORD_EMAIL_SUCCESS
      TENANT_CLIENT_ADDRESS_IS_MANDATORY
      TENANT_CLIENT_CITY_IS_MANDATORY
      TENANT_CLIENT_COUNTRY_IS_MANDATORY
      TENANT_CLIENT_EMAIL_IS_MANDATORY
      TENANT_CLIENT_PHONE_IS_MANDATORY
      TENANT_CLIENT_ZIP_CODE_IS_MANDATORY
      TENANT_CREATION_PAGE
      TENANT_DETAIL_PAGE
      TENANT_MAIN_PAGE
      TENANT_NOT_FOUND
      TENANT_NOT_FOUND_MESSAGE
      TENANT_RD_TENANT
      TENANT_RD_TENANTS
      TENANT_SELECTED_TENANT
      TENANT_USER_ASSOCIATION
      TENANT_USER_SESSION
      TRP_ASSOCIATION_ERROR_MESSAGE
      TRP_ASSOCIATION_NO_PERMISSION_SELECT_MESSAGE
      TRP_ASSOCIATION_SUCCESS_MESSAGE
      TRP_DISSOCIATION_ERROR_MESSAGE
      TRP_DISSOCIATION_NO_PERMISSION_SELECT_MESSAGE
      TRP_DISSOCIATION_SUCCESS_MESSAGE
      TRP_NO_ACTIVE_TENANT
      TRU_ASSOCIATION_ERROR_MESSAGE
      TRU_ASSOCIATION_NO_USER_SELECT_MESSAGE
      TRU_ASSOCIATION_SUCCESS_MESSAGE
      TRU_DISSOCIATION_ERROR_MESSAGE
      TRU_DISSOCIATION_NO_USER_SELECT_MESSAGE
      TRU_DISSOCIATION_SUCCESS_MESSAGE
      TR_ASSOCIATION
      TR_ASSOCIATIONS
      TR_ASSOCIATION_ID
      TR_ERROR_RETRIEVING_USER
      TR_PATH
      TR_TENANTS_FROM_USER
      UPDATE_ERROR_MESSAGE
      UPDATE_SUCCESS_MESSAGE
      USERS_DISPATCH_PATH
      USERS_MESSAGE
      USERS_PATH
      USERS_PROFILE_PATH
      USERS_ROLES_PATH
      USERS_SELECTED_MESSAGE
      USER_ACTIVE_TENANT_ROLE_PERMISSION_ASSIGNED_ERROR
      USER_ACTIVE_TENANT_ROLE_PERMISSION_ASSIGNED_SUCCESS
      USER_ACTIVE_TENANT_ROLE_PERMISSION_UNASSIGNED_ERROR
      USER_ACTIVE_TENANT_ROLE_PERMISSION_UNASSIGNED_SUCCESS
      USER_ASSIGNING_TENANT_ASSOCIATION_PATH
      USER_ASSIGNING_TENANT_ERROR
      USER_ASSIGNING_TENANT_SUCCESS
      USER_DELETE_PATH
      USER_MESSAGE
      USER_NOT_FOUND_MESSAGE
      USER_PATH
      USER_RD_ROOT_TENANT_ROLE_ADMINISTRATOR_ACCESS_ERROR
      USER_RD_TENANT_ROLE
      USER_RD_TENANT_ROLE_ASSIGNED_ERROR
      USER_RD_TENANT_ROLE_ASSIGNED_SUCCESS
      USER_RD_TENANT_ROLE_UNASSIGNED_ERROR
      USER_RD_TENANT_ROLE_UNASSIGNED_SUCCESS
      USER_RESET_PASSWORD_CONFIRM_MESSAGE
      USER_SEND_UPDATE_PASSWORD_EMAIL_ERROR
      USER_SEND_UPDATE_PASSWORD_EMAIL_SUCCESS
      USER_UN_ASSIGN_PATH
      value
    }
  }
  

  namespace io.radien.webapp {
    abstract class io.radien.webapp.LazyAbstractDataModel {
        # datasource : List<? extends T>
        {static} - log : Logger
        {static} - serialVersionUID : long
        {abstract} + getData()
        + getRowData()
        + getRowKey()
        + load()
    }
  }
  

  namespace io.radien.webapp {
    class io.radien.webapp.OafThemeManager {
        {static} + DEFAULT_THEME : String
        {static} # log : Logger
        - currentTheme : String
        {static} - serialVersionUID : long
        + getCurrentTheme()
        + getLogoResourcePath()
        + getOAF()
        + getPreloaderResourcePath()
        + getPreloaderSvgName()
        + getThemeCssClass()
        + setCurrentTheme()
    }
  }
  

  namespace io.radien.webapp {
    abstract class io.radien.webapp.PluginBridgingManager {
        {static} - serialVersionUID : long
        + getOAF()
        {abstract} + getThemeCssClass()
        + getUserSession()
        + isCmsDynamicMenuEnabled()
    }
  }
  

  namespace io.radien.webapp {
    class io.radien.webapp.WebApp {
        {static} - serialVersionUID : long
        + getOAF()
        + getProperty()
    }
  }
  

  io.radien.webapp.AbstractManager .up.|> java.io.Serializable
  io.radien.webapp.LazyAbstractDataModel -up-|> org.primefaces.model.LazyDataModel
  io.radien.webapp.OafThemeManager .up.|> java.io.Serializable
  io.radien.webapp.OafThemeManager -up-|> io.radien.webapp.PluginBridgingManager
  io.radien.webapp.OafThemeManager o-- io.radien.api.OAFAccess : oaf
  io.radien.webapp.PluginBridgingManager .up.|> java.io.Serializable
  io.radien.webapp.PluginBridgingManager o-- io.radien.api.OAFAccess : oaf
  io.radien.webapp.PluginBridgingManager o-- io.radien.webapp.security.UserSession : userSession
  io.radien.webapp.WebApp -up-|> io.radien.webapp.AbstractWebapp
  io.radien.webapp.WebApp o-- io.radien.api.OAFAccess : oaf







@enduml
