@startuml

title __SERVICE's Class Diagram__\n

  namespace io.radien.api {
    namespace service {
      interface io.radien.api.service.DataAccessLayer {
      }
    }
  }
  

  namespace io.radien.api {
    namespace service {
      interface io.radien.api.service.ServiceAccess {
      }
    }
  }
  








@enduml
