@startuml

title __EVENTBUS's Class Diagram__\n

  namespace io.radien.kernel {
    namespace eventbus {
      class io.radien.kernel.eventbus.EventBus {
          {static} # log : Logger
          {static} - serialVersionUID : long
          + fireEvent()
      }
    }
  }
  

  io.radien.kernel.eventbus.EventBus .up.|> java.io.Serializable







@enduml
