@startuml

title __SERVICE's Class Diagram__\n

  namespace io.radien.security.openid.service {
    interface io.radien.security.openid.service.AuthenticationService {
        {abstract} + authenticate()
        {abstract} + authenticate()
        {abstract} + authenticateExternal()
        + validate()
    }
  }
  

  namespace io.radien.security.openid.service {
    class io.radien.security.openid.service.PrivateService {
        {static} - PRIVATE_SERVICE_RESPONSE_TEXT : String
        + privateService()
    }
  }
  

  namespace io.radien.security.openid.service {
    class io.radien.security.openid.service.PublicService {
        {static} - PUBLIC_SERVICE_RESPONSE_TEXT : String
        + shared()
    }
  }
  



 

@enduml
