# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'adopt'
    - name: Build with Maven
      run: mvn clean test --file pom.xml -DKEYCLOAK_CLIENT_ID = ${{ secrets.KEYCLOAK_CLIENT_ID }} -DKEYCLOAK_IDP_URL = ${{ secrets.KEYCLOAK_IDP_URL }} -DKEYCLOAK_TOKEN_PATH = ${{ secrets.KEYCLOAK_TOKEN_PATH }} -DKEYCLOAK_USER_PATH = ${{ secrets.KEYCLOAK_USER_PATH }} -DREALMS_TOKEN_PATH = ${{ secrets.REALMS_TOKEN_PATH }} -DSCRIPT_CLIENT_ID = ${{ secrets.SCRIPT_CLIENT_ID }} -DSCRIPT_CLIENT_ID_VALUE = ${{ secrets.SCRIPT_CLIENT_ID_VALUE }} -DSCRIPT_CLIENT_SECRET = ${{ secrets.SCRIPT_CLIENT_SECRET }} -DSCRIPT_CLIENT_SECRET_VALUE = ${{ secrets.SCRIPT_CLIENT_SECRET_VALUE }} -DSCRIPT_REDIRECT_URL = ${{ secrets.SCRIPT_REDIRECT_URL }} -DSCRIPT_REDIRECT_URL_VALUE = ${{ secrets.SCRIPT_REDIRECT_URL_VALUE }} -DSCRIPT_GRANT_TYPE = ${{ secrets.SCRIPT_GRANT_TYPE }} -DSCRIPT_GRANT_TYPE_VALUE = ${{ secrets.SCRIPT_GRANT_TYPE_VALUE }} -DSCRIPT_USERNAME = ${{ secrets.SCRIPT_USERNAME }} -DSCRIPT_USERNAME_VALUE = ${{ secrets.SCRIPT_USERNAME_VALUE }} -DSCRIPT_PASSWORD = ${{ secrets.SCRIPT_PASSWORD }} -DSCRIPT_PASSWORD_VALUE = ${{ secrets.SCRIPT_PASSWORD_VALUE }} -DAUTHENTICATION_CLIENT_ID = ${{ secrets.AUTHENTICATION_CLIENT_ID }} -DAUTHENTICATION_CLIENT_SECRET = ${{ secrets.AUTHENTICATION_CLIENT_SECRET }} -DAUTHENTICATION_CLIENT_SCOPE = ${{ secrets.AUTHENTICATION_CLIENT_SCOPE }} -DAPPLICATION_AUTHENTICATION_CLIENT_SECRET = ${{ secrets.APPLICATION_AUTHENTICATION_CLIENT_SECRET }} -Dvalue = ${{ secrets.value }}
