@startuml

title __RD-MS-ROLEMANAGEMENT's Class Diagram__\n

  namespace io.radien.ms.rolemanagement {
    class io.radien.ms.rolemanagement.RoleApplication {
    }
  }
  

  namespace io.radien.ms.rolemanagement {
    namespace entities {
      class io.radien.ms.rolemanagement.entities.RoleEntity {
      }
    }
  }
  

  namespace io.radien.ms.rolemanagement {
    namespace entities {
      class io.radien.ms.rolemanagement.entities.TenantRoleEntity {
      }
    }
  }
  

  namespace io.radien.ms.rolemanagement {
    namespace entities {
      class io.radien.ms.rolemanagement.entities.TenantRolePermissionEntity {
      }
    }
  }
  

  namespace io.radien.ms.rolemanagement {
    namespace entities {
      class io.radien.ms.rolemanagement.entities.TenantRoleUserEntity {
      }
    }
  }
  

  namespace io.radien.ms.rolemanagement {
    namespace factory {
      class io.radien.ms.rolemanagement.factory.RoleFactory {
      }
    }
  }
  

  namespace io.radien.ms.rolemanagement {
    namespace providers {
      class io.radien.ms.rolemanagement.providers.RoleModelMessageBodyWriter {
      }
    }
  }
  

  namespace io.radien.ms.rolemanagement {
    namespace providers {
      class io.radien.ms.rolemanagement.providers.SystemRoleMessageBodyReader {
      }
    }
  }
  

  namespace io.radien.ms.rolemanagement {
    namespace services {
      abstract class io.radien.ms.rolemanagement.services.AbstractTenantRoleDomainBusinessService {
      }
    }
  }
  

  namespace io.radien.ms.rolemanagement {
    namespace services {
      abstract class io.radien.ms.rolemanagement.services.AbstractTenantRoleDomainService {
      }
    }
  }
  

  namespace io.radien.ms.rolemanagement {
    namespace services {
      class io.radien.ms.rolemanagement.services.RoleBusinessService {
      }
    }
  }
  

  namespace io.radien.ms.rolemanagement {
    namespace services {
      class io.radien.ms.rolemanagement.services.RoleResource {
      }
    }
  }
  

  namespace io.radien.ms.rolemanagement {
    namespace services {
      class io.radien.ms.rolemanagement.services.RoleService {
      }
    }
  }
  

  namespace io.radien.ms.rolemanagement {
    namespace services {
      class io.radien.ms.rolemanagement.services.TenantRoleBusinessService {
      }
    }
  }
  

  namespace io.radien.ms.rolemanagement {
    namespace services {
      class io.radien.ms.rolemanagement.services.TenantRolePermissionBusinessService {
      }
    }
  }
  

  namespace io.radien.ms.rolemanagement {
    namespace services {
      class io.radien.ms.rolemanagement.services.TenantRolePermissionResource {
      }
    }
  }
  

  namespace io.radien.ms.rolemanagement {
    namespace services {
      class io.radien.ms.rolemanagement.services.TenantRolePermissionService {
      }
    }
  }
  

  namespace io.radien.ms.rolemanagement {
    namespace services {
      class io.radien.ms.rolemanagement.services.TenantRoleResource {
      }
    }
  }
  

  namespace io.radien.ms.rolemanagement {
    namespace services {
      class io.radien.ms.rolemanagement.services.TenantRoleService {
      }
    }
  }
  

  namespace io.radien.ms.rolemanagement {
    namespace services {
      class io.radien.ms.rolemanagement.services.TenantRoleUserBusinessService {
      }
    }
  }
  

  namespace io.radien.ms.rolemanagement {
    namespace services {
      class io.radien.ms.rolemanagement.services.TenantRoleUserResource {
      }
    }
  }
  

  namespace io.radien.ms.rolemanagement {
    namespace services {
      class io.radien.ms.rolemanagement.services.TenantRoleUserService {
      }
    }
  }
  

  namespace io.radien.ms.rolemanagement {
    namespace util {
      class io.radien.ms.rolemanagement.util.RoleModelMapper {
      }
    }
  }
  

  io.radien.ms.rolemanagement.RoleApplication -up-|> javax.ws.rs.core.Application
  io.radien.ms.rolemanagement.entities.RoleEntity -up-|> io.radien.ms.rolemanagement.client.entities.Role
  io.radien.ms.rolemanagement.entities.TenantRoleEntity -up-|> io.radien.ms.rolemanagement.client.entities.TenantRole
  io.radien.ms.rolemanagement.entities.TenantRolePermissionEntity -up-|> io.radien.ms.rolemanagement.client.entities.TenantRolePermission
  io.radien.ms.rolemanagement.entities.TenantRoleUserEntity -up-|> io.radien.ms.rolemanagement.client.entities.TenantRoleUser
  io.radien.ms.rolemanagement.factory.RoleFactory .up.|> java.io.Serializable
  io.radien.ms.rolemanagement.providers.RoleModelMessageBodyWriter .up.|> javax.ws.rs.ext.MessageBodyWriter
  io.radien.ms.rolemanagement.providers.SystemRoleMessageBodyReader .up.|> javax.ws.rs.ext.MessageBodyReader
  io.radien.ms.rolemanagement.services.AbstractTenantRoleDomainBusinessService o-- io.radien.api.service.permission.PermissionRESTServiceAccess : permissionRESTServiceAccess
  io.radien.ms.rolemanagement.services.AbstractTenantRoleDomainBusinessService o-- io.radien.api.service.role.RoleServiceAccess : roleServiceAccess
  io.radien.ms.rolemanagement.services.AbstractTenantRoleDomainBusinessService o-- io.radien.api.service.tenant.TenantRESTServiceAccess : tenantRESTServiceAccess
  io.radien.ms.rolemanagement.services.AbstractTenantRoleDomainBusinessService o-- io.radien.api.service.tenantrole.TenantRoleServiceAccess : tenantRoleServiceAccess
  io.radien.ms.rolemanagement.services.RoleBusinessService .up.|> java.io.Serializable
  io.radien.ms.rolemanagement.services.RoleBusinessService o-- io.radien.api.service.role.RoleServiceAccess : roleServiceAccess
  io.radien.ms.rolemanagement.services.RoleResource .up.|> io.radien.ms.rolemanagement.client.services.RoleResourceClient
  io.radien.ms.rolemanagement.services.RoleResource o-- io.radien.ms.rolemanagement.services.RoleBusinessService : roleBusinessService
  io.radien.ms.rolemanagement.services.RoleService .up.|> io.radien.api.service.role.RoleServiceAccess
  io.radien.ms.rolemanagement.services.TenantRoleBusinessService -up-|> io.radien.ms.rolemanagement.services.AbstractTenantRoleDomainBusinessService
  io.radien.ms.rolemanagement.services.TenantRoleBusinessService o-- io.radien.api.service.tenantrole.TenantRoleUserServiceAccess : tenantRoleUserServiceAccess
  io.radien.ms.rolemanagement.services.TenantRolePermissionBusinessService .up.|> java.io.Serializable
  io.radien.ms.rolemanagement.services.TenantRolePermissionBusinessService -up-|> io.radien.ms.rolemanagement.services.AbstractTenantRoleDomainBusinessService
  io.radien.ms.rolemanagement.services.TenantRolePermissionBusinessService o-- io.radien.api.service.tenantrole.TenantRolePermissionServiceAccess : tenantRolePermissionService
  io.radien.ms.rolemanagement.services.TenantRolePermissionResource .up.|> io.radien.ms.rolemanagement.client.services.TenantRolePermissionResourceClient
  io.radien.ms.rolemanagement.services.TenantRolePermissionResource o-- io.radien.ms.rolemanagement.services.TenantRolePermissionBusinessService : tenantRolePermissionBusinessService
  io.radien.ms.rolemanagement.services.TenantRolePermissionService .up.|> io.radien.api.service.tenantrole.TenantRolePermissionServiceAccess
  io.radien.ms.rolemanagement.services.TenantRolePermissionService -up-|> io.radien.ms.rolemanagement.services.AbstractTenantRoleDomainService
  io.radien.ms.rolemanagement.services.TenantRoleResource .up.|> io.radien.ms.rolemanagement.client.services.TenantRoleResourceClient
  io.radien.ms.rolemanagement.services.TenantRoleResource o-- io.radien.ms.rolemanagement.services.TenantRoleBusinessService : tenantRoleBusinessService
  io.radien.ms.rolemanagement.services.TenantRoleService .up.|> io.radien.api.service.tenantrole.TenantRoleServiceAccess
  io.radien.ms.rolemanagement.services.TenantRoleUserBusinessService .up.|> java.io.Serializable
  io.radien.ms.rolemanagement.services.TenantRoleUserBusinessService -up-|> io.radien.ms.rolemanagement.services.AbstractTenantRoleDomainBusinessService
  io.radien.ms.rolemanagement.services.TenantRoleUserBusinessService o-- io.radien.api.service.tenant.ActiveTenantRESTServiceAccess : activeTenantRESTServiceAccess
  io.radien.ms.rolemanagement.services.TenantRoleUserBusinessService o-- io.radien.api.service.tenantrole.TenantRoleUserServiceAccess : tenantRoleUserServiceAccess
  io.radien.ms.rolemanagement.services.TenantRoleUserResource .up.|> io.radien.ms.rolemanagement.client.services.TenantRoleUserResourceClient
  io.radien.ms.rolemanagement.services.TenantRoleUserResource o-- io.radien.ms.rolemanagement.services.TenantRoleUserBusinessService : tenantRoleUserBusinessService
  io.radien.ms.rolemanagement.services.TenantRoleUserResource o-- io.radien.api.service.tenantrole.TenantRoleUserServiceAccess : tenantRoleUserServiceAccess
  io.radien.ms.rolemanagement.services.TenantRoleUserService .up.|> io.radien.api.service.tenantrole.TenantRoleUserServiceAccess
  io.radien.ms.rolemanagement.services.TenantRoleUserService -up-|> io.radien.ms.rolemanagement.services.AbstractTenantRoleDomainService


 

@enduml
