@startuml

title __UTIL's Class Diagram__\n

  namespace io.radien.ms.usermanagement.client {
    namespace util {
      class io.radien.ms.usermanagement.client.util.ClientServiceUtil {
          + getUserResourceClient()
      }
    }
  }
  

  namespace io.radien.ms.usermanagement.client {
    namespace util {
      class io.radien.ms.usermanagement.client.util.ListUserModelMapper {
          {static} + map()
      }
    }
  }
  

  namespace io.radien.ms.usermanagement.client {
    namespace util {
      class io.radien.ms.usermanagement.client.util.PageModelMapper {
          {static} + map()
          - PageModelMapper()
      }
    }
  }
  

  namespace io.radien.ms.usermanagement.client {
    namespace util {
      class io.radien.ms.usermanagement.client.util.UserFactoryUtil {
          {static} - serialVersionUID : long
          {static} + convertJsonObject()
          {static} + convertSystemUserToJsonObject()
          {static} + convertToUserPageObject()
          {static} + createUser()
      }
    }
  }
  

  namespace io.radien.ms.usermanagement.client {
    namespace util {
      class io.radien.ms.usermanagement.client.util.UserModelMapper {
          {static} + map()
          {static} + map()
          {static} + map()
          {static} + mapToPage()
      }
    }
  }
  

  io.radien.ms.usermanagement.client.util.UserFactoryUtil .up.|> java.io.Serializable







@enduml
